lowRISC/ibex

rtl/ibex_alu.sv
rtl/ibex_compressed_decoder.sv
rtl/ibex_controller.sv
rtl/ibex_core.sv
rtl/ibex_cs_registers.sv
rtl/ibex_decoder.sv
rtl/ibex_defines.sv
rtl/ibex_ex_block.sv
rtl/ibex_id_stage.sv
rtl/ibex_if_stage.sv
rtl/ibex_multdiv_fast.sv
rtl/ibex_multdiv_slow.sv
rtl/ibex_tracer.sv
rtl/ibex_tracer_defines.sv

Switch from parameters to enums where possible, and remove unused ones.

Some more ibex cleanup

---

rtl/ibex_core.sv
rtl/ibex_decoder.sv
rtl/ibex_defines.sv
rtl/ibex_id_stage.sv
rtl/ibex_tracer.sv

Code cleanup

---

doc/exception_interrupts.rst
rtl/ibex_alu.sv
rtl/ibex_controller.sv
rtl/ibex_core.sv
rtl/ibex_cs_registers.sv
rtl/ibex_decoder.sv
rtl/ibex_id_stage.sv
rtl/ibex_if_stage.sv
rtl/ibex_multdiv_fast.sv

This pull request addresses most of the points discussed in #150 in stwg-base and should fix most of the linting errors in ibex. Remaining linting errors related to the load/store unit and bus exceptions will be addressed separately.

Code cleanup, addresses #150 in stwg-base

---

doc/requirements.txt

Ensure to pickup the correct versions for wavedrom.

Fix wavedrom versions

---

rtl/ibex_id_stage.sv

Replaces #38 as the other one seemed to be messed up by GitHub

Fix synthesis ikarageo

---

rtl/ibex_multdiv_fast.sv

Simple drive-by I assume: I am pretty sure this is about the remainder of the operation. But not entirely ;)

Typo fix in muldiv: Reminder->Remainder

---

rtl/ibex_compressed_decoder.sv

Fix handling of HINTs in compressed instructions. 
Fixes #46 (and a bit more)
@taoliug can you re-test with these modifications?
@asb does my reading of the spec sound about right?

Compressed hints

---

vendor/google_riscv-dv.lock.hjson
vendor/google_riscv-dv/src/riscv_core_setting.sv
vendor/google_riscv-dv/src/riscv_instr_pkg.sv
vendor/google_riscv-dv/src/riscv_privileged_common_seq.sv

dv to revision be14080425cc3b9a5b33c6c29962893c890c62ee
* Merge pull request #23 from google/dev (taoliug)
* Add privileged CSR implementation configuration (Tao Liu)

Update google_riscv-dv to be14080

---

doc/index.rst
doc/rvfi.rst
rtl/ibex_core.sv
rtl/ibex_id_stage.sv
rtl/ibex_if_stage.sv

Interface for formal verification

RISC-V Formal Interface

---

doc/introduction.rst

Update documentation external link

---

vendor/google_riscv-dv.lock.hjson
vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
vendor/google_riscv-dv/src/riscv_core_setting.sv
vendor/google_riscv-dv/src/riscv_instr_pkg.sv
vendor/google_riscv-dv/testlist
vendor/patches/google_riscv-dv/0000-ibex-customization.patch

- Import riscv-dv @b4bd0c6cff0456111be966a11c1bd0aeec2d96e4
- Add ibex patches
- Update supported CSR
- Add redirection for trap handling

Import riscv-dv @b4bd0c6cff0456111be966a11c1bd0aeec2d96e4

---

rtl/ibex_cs_registers.sv

This PR fixes 3 linting errors.
Both Verilator and Vivado builds successfully tested.

Fix linting errors

---

rtl/ibex_cs_registers.sv

Without this change, the core can continue to write CSRs for multiple clock cycles when being stalled. This can corrupt CSR (e.g. performance counters).

Make sure CSR set/clear/write op only change the CSR during one cycle

---

rtl/ibex_core.sv

Update signal name to match b22a6a10defc7bad31dda7d8a33c7145d1a79a3b

Fix updated signal name

---

dv/uvm/sim

Add #!/usr/bin/env bash for the sim script

---

rtl/ibex_compressed_decoder.sv
rtl/ibex_decoder.sv
rtl/ibex_defines.sv
rtl/ibex_tracer_defines.sv

Update opcode enum

---

.gitignore
doc/examples.rst
examples/fpga/artya7-100/README.md
examples/fpga/artya7-100/data/pins_artya7.xdc
examples/fpga/artya7-100/rtl/clkgen_xil7series.sv
examples/fpga/artya7-100/rtl/prim_clock_gating.sv
examples/fpga/artya7-100/rtl/ram_1p.sv
examples/fpga/artya7-100/rtl/top_artya7_100.sv
examples/fpga/artya7-100/top_artya7_100.core
examples/sw/led/.gitignore
examples/sw/led/Makefile
examples/sw/led/crt0.S
examples/sw/led/led.c
examples/sw/led/link.ld

Simple example of how Ibex can be used to run software on a FPGA target.

Ibex example Arty A7-100T

---

vendor/google_riscv-dv.lock.hjson
vendor/google_riscv-dv/iss_sim
vendor/google_riscv-dv/run

dv to revision 084fa3a4debb682b34c9b7f9b17342bb06619a3b
* Merge pull request #35 from google/dev (taoliug)
* Add timeout mechanism for the regression script (Tao Liu)
* Merge pull request #34 from google/dev (taoliug)
* Add check for the toolchain path setup (Tao Liu)

Update google_riscv-dv to 084fa3a

---

rtl/ibex_controller.sv
rtl/ibex_cs_registers.sv

This PR contains two cleanup commits split out of PR #149.

Minor cleanup

---

dv/uvm/common/irq_agent/irq_if.sv
dv/uvm/common/irq_agent/irq_master_driver.sv
dv/uvm/common/irq_agent/irq_monitor.sv
dv/uvm/common/irq_agent/irq_seq_item.sv
dv/uvm/riscv_dv_extension/ibex_asm_program_gen.sv
dv/uvm/tb/core_ibex_tb_top.sv
dv/uvm/tests/core_ibex_seq_lib.sv

Update TB for the new interrupt interface, fix issue #187

Update TB for the new interrupt interface

---

src_files.yml

This PR contains a single commit to update the path of source files in the `src_files.yml` file used in the PULP world.

src_files.yml: correct path of source files

---

examples/sim/top_tracing_sim.core

- Updated the timescale option to not include "=" in between the
timescale directive and the value passed

Change sim timescale option - Fixes #181

---

vendor/google_riscv-dv.lock.hjson
vendor/google_riscv-dv/.gitignore
vendor/google_riscv-dv/README.md
vendor/google_riscv-dv/iss_cmp
vendor/google_riscv-dv/iss_sim
vendor/google_riscv-dv/questa_sim.tcl
vendor/google_riscv-dv/run
vendor/google_riscv-dv/run.py
vendor/google_riscv-dv/scripts/gen_csr_test.py
vendor/google_riscv-dv/scripts/instr_trace_compare.py
vendor/google_riscv-dv/scripts/lib.py
vendor/google_riscv-dv/scripts/ovpsim_log_to_trace_csv.py
vendor/google_riscv-dv/scripts/spike_log_to_trace_csv.py
vendor/google_riscv-dv/src/dv_defines.svh
vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
vendor/google_riscv-dv/src/riscv_illegal_instr.sv
vendor/google_riscv-dv/src/riscv_instr_base.sv
vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
vendor/google_riscv-dv/src/riscv_instr_sequence.sv
vendor/google_riscv-dv/src/riscv_page_table_list.sv
vendor/google_riscv-dv/src/riscv_rand_instr.sv
vendor/google_riscv-dv/yaml/csr_template.yaml
vendor/google_riscv-dv/yaml/iss.yaml
vendor/google_riscv-dv/yaml/simulator.yaml
vendor/google_riscv-dv/yaml/testlist.yaml

dv to revision a07e0a726edf0230314c08d31546eecbed23054b
* Merge pull request #53 from google/flow (taoliug)
* Update README file for the new flow (Tao Liu)
* Merge pull request #52 from google/flow (taoliug)
* Add timeout mechanism to the flow (Tao Liu)
* Merge pull request #51 from google/flow (taoliug)
* Simulation flow update (Tao Liu)
* Merge pull request #50 from udinator/master (taoliug)
* added license for csr_template.yaml (Udi)
* Merge pull request #49 from google/dev (taoliug)
* Update log process script (Tao Liu)
* Merge pull request #48 from google/dev (taoliug)
* Fix illegal instruction issue (Tao Liu)
* Merge pull request #47 from google/dev (taoliug)
* Refactor the simulation flow (Tao Liu)
* Merge pull …

Update google_riscv-dv to a07e0a7

---

doc/introduction.rst

Document specifications we aim to support

---

doc/exception_interrupts.rst
doc/instruction_fetch.rst
doc/integration.rst
dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
dv/uvm/tb/core_ibex_tb_top.sv
examples/fpga/artya7-100/rtl/top_artya7_100.sv
examples/sim/tb/ibex_tracing_tb.sv
rtl/ibex_controller.sv
rtl/ibex_core.sv
rtl/ibex_core_tracing.sv
rtl/ibex_fetch_fifo.sv
rtl/ibex_id_stage.sv
rtl/ibex_if_stage.sv
rtl/ibex_pkg.sv
rtl/ibex_prefetch_buffer.sv

- Add required signals to top-level
- Propagate error through fetch stages
- Add new exception type
- Update documentation for new exception type

[rtl] Add support for instruction fetch errors

---

vendor/google_riscv-dv.lock.hjson
vendor/google_riscv-dv/run.py

dv to revision 07599f689a385794cb73932922008bdbe8131d82
* Fix introduced TypeError in run.py (Udi)

Update google_riscv-dv to google/riscv-dv@07599f6

---

dv/uvm/riscv_dv_extension/ibex_asm_program_gen.sv
dv/uvm/riscv_dv_extension/ibex_core_setting.sv
dv/uvm/tb/core_ibex_tb_top.sv

[DV] Make mtvec writable, remove previous workaround

---

CREDITS.md
README.md
rtl/ibex_alu.sv
rtl/ibex_compressed_decoder.sv
rtl/ibex_controller.sv
rtl/ibex_core.sv
rtl/ibex_cs_registers.sv
rtl/ibex_decoder.sv
rtl/ibex_ex_block.sv
rtl/ibex_fetch_fifo.sv
rtl/ibex_id_stage.sv
rtl/ibex_if_stage.sv
rtl/ibex_load_store_unit.sv
rtl/ibex_multdiv_fast.sv
rtl/ibex_multdiv_slow.sv
rtl/ibex_pkg.sv
rtl/ibex_prefetch_buffer.sv
rtl/ibex_register_file_ff.sv
rtl/ibex_register_file_latch.sv
rtl/ibex_tracer.sv
rtl/ibex_tracer_pkg.sv

These changes have been approved by Luca and Frank. Review is needed for style and other non-content topics.

Update to the license headers

---

rtl/ibex_register_file_latch.sv

This commit updates the comments inside the latch-based register file. Some of them were outdated or just wrong.

Update comments in latch-based register file

---

doc/cs_registers.rst
doc/index.rst
doc/integration.rst
doc/introduction.rst
doc/pmp.rst
ibex_core.core
lint/verilator_waiver.vlt
rtl/ibex_core.sv
rtl/ibex_cs_registers.sv
rtl/ibex_if_stage.sv
rtl/ibex_load_store_unit.sv
rtl/ibex_pkg.sv
rtl/ibex_pmp.sv
rtl/ibex_prefetch_buffer.sv
src_files.yml

- Instantiate generic PMP module
- Wire up I-side and D-side PMP faults

[RTL] - Add PMP module

---

rtl/ibex_core_tracing.sv

Fix a syntax error introduced by #284, addresses the first part of #287

Fix syntax error

---

rtl/ibex_fetch_fifo.sv
rtl/ibex_prefetch_buffer.sv

- Assertion was added in the wrong file

[I-side] - Fix assertion error

---

dv/uvm/common/ibex_mem_intf_agent/ibex_mem_intf_slave_driver.sv

Update the timing of when the testbench sends grants to Ibex, partially addresses the assertion failures mentioned in #293.

Update slave_driver grant timing to pass Ibex assertion checks

---

rtl/ibex_fetch_fifo.sv
rtl/ibex_if_stage.sv
rtl/ibex_prefetch_buffer.sv

- Fixes #288
- Add missing grant qualification to stop spurious address updates
- Make RTL robust to spurious rvalid signalling

[I-side] - Fix issues found in tracing example

---

vendor/google_riscv-dv.lock.hjson
vendor/google_riscv-dv/README.md
vendor/google_riscv-dv/run.py
vendor/google_riscv-dv/scripts/lib.py
vendor/google_riscv-dv/src/riscv_amo_instr_lib.sv
vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
vendor/google_riscv-dv/src/riscv_callstack_gen.sv
vendor/google_riscv-dv/src/riscv_directed_instr_lib.sv
vendor/google_riscv-dv/src/riscv_instr_base.sv
vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
vendor/google_riscv-dv/src/riscv_instr_pkg.sv
vendor/google_riscv-dv/src/riscv_instr_sequence.sv
vendor/google_riscv-dv/src/riscv_instr_stream.sv
vendor/google_riscv-dv/src/riscv_load_store_instr_lib.sv
vendor/google_riscv-dv/test/riscv_instr_base_test.sv
vendor/google_riscv-dv/test/riscv_instr_test_pkg.sv
vendor/google_riscv-dv/user_extension/user_extension.svh
vendor/google_riscv-dv/yaml/simulator.yaml

dv to revision 0d2b5b7b8b1cdbce74d9e123a427052b12accd7b
* Add user extension support (google/riscv-dv#163) (taoliug)
* Update README (google/riscv-dv#162) (taoliug)
* Fix compilation issue (google/riscv-dv#161) (taoliug)
* Fix compilation issue (google/riscv-dv#160) (taoliug)
* Adding dsim support (google/riscv-dv#159) (taoliug)
* Fix RV64A typo (google/riscv-dv#158) (taoliug)

Update google_riscv-dv to google/riscv-dv@0d2b5b7

---

dv/uvm/common/irq_agent/irq_master_driver.sv
dv/uvm/env/core_ibex_env.sv
dv/uvm/tb/core_ibex_tb_top.sv

[DV] Drive external stimulus to 0 after reset

---

dv/uvm/env/core_ibex_env_pkg.sv
dv/uvm/env/core_ibex_rvfi_if.sv
dv/uvm/tb/core_ibex_tb_top.sv
dv/uvm/tests/core_ibex_base_test.sv
dv/uvm/tests/core_ibex_test_lib.sv

- Updated the logic for memory fault checking test
- Added virtual RVFI interface, TODO item to add some RVFI register checks to this test, waiting for #332

[DV] Fix memory error test logic

---

vendor/google_riscv-dv.lock.hjson
vendor/google_riscv-dv/README.md
vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
vendor/google_riscv-dv/src/riscv_privileged_common_seq.sv

dv to revision d3419444ca2fdb499a204587b2d36c6f5c1e0c44
* Update README (Udi)
* Add knob to enable full CSR randomization, fix mstatus.spp (Udi)

Update google_riscv-dv to google/riscv-dv@d341944

---

azure-pipelines.yml

Tracked in https://github.com/enthought/sat-solver/issues/270

CI: Unbreak build after simplesat breakage

---

rtl/ibex_cs_registers.sv

For write logic in ibex_cs_registers.sv:
- move `if (csr_we_int) begin` conditional outside `unique case` block to make code cleaner
- move `illegal_csr_write` assign to write logic block with assignments in appropriate places. Before it was just a general out of scope assign without too much meaning.

Cleaner `csr_we_int` conditional in CSR

---

rtl/ibex_controller.sv
rtl/ibex_id_stage.sv

Fixes #305
@udinator would you be able to run some tests on this change?  I've done some basic tests to ensure exceptions continue to function but if you had something more in-depth to try out that would be useful.

[RTL] Flop exc_req in controller to ease timing

---

dv/uvm/riscv_dv_extension/ibex_log_to_trace_csv.py

Log parsing update to match the new modifications to the tracer.
Will not merge until #360 is merged, to avoid breaking any current flows.

[DV] Update ibex log regex

---

doc/cs_registers.rst
doc/exception_interrupts.rst
doc/introduction.rst
lint/verilator_waiver.vlt
rtl/ibex_controller.sv
rtl/ibex_core.sv
rtl/ibex_cs_registers.sv
rtl/ibex_id_stage.sv
rtl/ibex_pkg.sv
rtl/ibex_pmp.sv

- General changes to suport U-mode  (fixes #88)
- Update documentation (also fixes #306)
- Add priv mode flops to CSRs module
- Propagate correct priv mode to PMP module
- Fix various address matching bugs in PMP module
- Implement CSR priv-mode permission checking
- Implement illegal U-mode instruction checking
- Add extra mstatus bits for U-mode (MPRV and TW)

[Priv modes] Add support for U-Mode

---

rtl/ibex_tracer.sv

New output looks like this:
118         55      00000154        6121    c.addi16sp      x2,64     x2:0x00000030  x2=0x00000070
Fixes #322

Include rs1 and rd in trace of c.addi16sp

---

dv/uvm/riscv_dv_extension/testlist.yaml
dv/uvm/tests/core_ibex_base_test.sv
dv/uvm/tests/core_ibex_test_lib.sv

- increase test timeout to 10M cycles
- increase number of tests involving external stimulus

[DV] Add interrupt wfi test to address coverage hole

---

dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.cc

Add description to usage output.
Add short option '-c'.

[DV] Update simulation terminate argument

---

rtl/ibex_tracer.sv

[RTL/Tracer] Fix compressed jump RD write

---

rtl/ibex_load_store_unit.sv

This commit replaces an obsolete assertion with one checking that response valid is received only if the LSU is ready to handle it.
This resolves lowRISC/ibex#421 reported by @udinator.

[rtl/lsu] Rework assertion checking response valid

---

rtl/ibex_core.sv
rtl/ibex_core_tracing.sv
rtl/ibex_ex_block.sv

Looks like my first PR regarding the error synthesis was ugly...
This one should be better now

Error synthesis in Vivado

---

dv/cs_registers/Makefile
dv/cs_registers/README.md
dv/cs_registers/env/env_dpi.cc
dv/cs_registers/env/env_dpi.sv
dv/cs_registers/env/register_environment.cc
dv/cs_registers/env/register_environment.h
dv/cs_registers/env/simctrl.cc
dv/cs_registers/env/simctrl.h
dv/cs_registers/model/base_register.cc
dv/cs_registers/model/base_register.h
dv/cs_registers/model/register_model.cc
dv/cs_registers/model/register_model.h
dv/cs_registers/reg_driver/reg_dpi.cc
dv/cs_registers/reg_driver/reg_dpi.sv
dv/cs_registers/reg_driver/register_driver.cc
dv/cs_registers/reg_driver/register_driver.h
dv/cs_registers/reg_driver/register_transaction.cc
dv/cs_registers/reg_driver/register_transaction.h
dv/cs_registers/rst_driver/reset_driver.cc
dv/cs_registers/rst_driver/reset_driver.h
dv/cs_registers/rst_driver/rst_dpi.cc
dv/cs_registers/rst_driver/rst_dpi.sv
dv/cs_registers/tb/tb_cs_registers.cc
dv/cs_registers/tb/tb_cs_registers.sv
dv/cs_registers/tb_cs_registers.core
dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.cc
dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.h

- Sample C++ unit testbench for system registers module
- Only tests a few PMP registers at the moment

[DV] Add registers testbench

---

vendor/google_riscv-dv.lock.hjson
vendor/google_riscv-dv/run.py
vendor/google_riscv-dv/yaml/iss.yaml

dv to revision 44bec7695fd2399166e181fa84b66a608b5f745f
* Re-enable custom OVPsim configuration files (google/riscv-dv#282)
(udinator)

Update google_riscv-dv to google/riscv-dv@44bec76

---

doc/verification.rst

- added some details about the trace log comparison process - either full register write comparison, or final register value comparison
- added information about the handshaking mechanism used to verify all situations involving external stimulus - linked the document in RISCV-DV for more detailed information

[Doc] Update verification documentation

---

examples/simple_system/README.md

Fix formatting of table in simple system

---

rtl/ibex_controller.sv

This PR contains two commits to remove coverage holes in the controller. The changes are non-functional.

[rtl/controller] Remove coverage holes

---

dv/uvm/Makefile
dv/uvm/env/core_ibex_dut_probe_if.sv
dv/uvm/riscv_dv_extension/riscv_core_setting.sv
dv/uvm/riscv_dv_extension/testlist.yaml
dv/uvm/tb/core_ibex_tb_top.sv
dv/uvm/tests/core_ibex_test_lib.sv

- Added privilege level checks throughout the existing test suite
- Added a basic U-mode instruction test
- All existing tests in the suite pass when booting from U-mode (after applying #465)

[DV] Enable user-mode in DV environment, add basic tests

---

rtl/ibex_fetch_fifo.sv
rtl/ibex_id_stage.sv
rtl/ibex_if_stage.sv
rtl/ibex_load_store_unit.sv

This PR updates the assertions to not fire while the core is in reset. This resolves #274. In addition, some assertions are updated and some new assertions are added.

[rtl] Update assertions

---

dv/riscv_compliance/ibex_riscv_compliance.cc

Check the return value and exit program execution.

[DV] Add exit check for setup call

---

dv/cs_registers/Makefile
dv/cs_registers/README.md
dv/cs_registers/env/env_dpi.cc
dv/cs_registers/env/env_dpi.sv
dv/cs_registers/env/register_environment.cc
dv/cs_registers/env/register_environment.h
dv/cs_registers/env/register_types.h
dv/cs_registers/model/register_model.cc
dv/cs_registers/model/register_model.h
dv/cs_registers/tb/tb_cs_registers.cc
dv/cs_registers/tb/tb_cs_registers.sv
dv/cs_registers/tb_cs_registers.core

- Switch from Makefile calling fusesoc to fusesoc calling Makefile
- Pass parameters through DPI rather than as env variables

[dv] Prepare CS registers TB for CI

---

dv/uvm/riscv_dv_extension/testlist.yaml
dv/uvm/tests/core_ibex_test_lib.sv

- Add test for accessing higher privilege mode CSRs from U-mode
- Refactor illegal instruction checking logic to a separate task

[DV] Test accesses to higher privileged CSRs

---

dv/uvm/Makefile
dv/uvm/riscv_dv_extension/ibex_log_to_trace_csv.py
dv/uvm/sim.py

[DV] Update flow to match RISCV-DV changes

---

dv/uvm/Makefile

[DV] streamline Makefile gen flow

---

vendor/google_riscv-dv.lock.hjson
vendor/google_riscv-dv/run.py
vendor/google_riscv-dv/src/riscv_rand_instr.sv

dv to revision d69190682078470bc6d5661d72f873ae9850ae53
* enable CSR randomization only for csr instructions (google/riscv-
dv#321) (udinator)
* fix csr test script pathname (Udi Jonnalagadda)
Addresses #485 

Update google_riscv-dv to google/riscv-dv@d691906

---

Makefile

New targets to build and run the testbench.
Minor cleanup for parallel make runs.

[make] Add CS Register testbench targets

---

azure-pipelines.yml
doc/introduction.rst
doc/pipeline_details.rst
rtl/ibex_decoder.sv
rtl/ibex_prefetch_buffer.sv

We should add stimulation of fence.i to the DV and ensure this gets a decent testing. I have done some basic testing with simple system and it looks to work ok.
(I'd be happy to look into the DV work but that won't happen til I return from Holiday)

Implement FENCE.I

---

azure-pipelines.yml
dv/cs_registers/env/env_dpi.cc
dv/cs_registers/env/env_dpi.sv
dv/cs_registers/env/register_environment.cc
dv/cs_registers/env/register_environment.h
dv/cs_registers/env/simctrl.cc
dv/cs_registers/env/simctrl.h
dv/cs_registers/tb/tb_cs_registers.cc
dv/cs_registers/tb/tb_cs_registers.sv

Build and run TB, checking for failures

[ci] Add CS registers TB to CI

---

examples/simple_system/README.md
examples/simple_system/ibex_simple_system.core
examples/simple_system/rtl/ibex_simple_system.sv
shared/rtl/sim/simulator_ctrl.sv

Add stimuli. Fix compile error for assignment from multiple blocks.

Add Synopsys VCS Support for Ibex Simple System

---

dv/uvm/ius.tcl
dv/uvm/yaml/rtl_simulation.yaml

RTL simulation script was extended to support Cadence simulator.

RTL simulation script upgrade

---

doc/performance_counters.rst

[doc] Add a comment on mhpmcounter optimization

---

dv/uvm/riscv_dv_extension/riscv_core_setting.sv

[DV] add support_unaligned_load_store setting

---

dv/cs_registers/tb/tb_cs_registers.sv
lint/verilator_waiver.vlt
rtl/ibex_controller.sv
rtl/ibex_core.sv
rtl/ibex_cs_registers.sv
rtl/ibex_id_stage.sv

Fixes #492
@udinator could you run the tests you saw failing in #492 again on this?

[RTL] Only restore from mstack in nmi mode

---

dv/uvm/tests/core_ibex_test_lib.sv

[DV] fix incorrect irq_seq handle name

---

dv/verilator/memutil/cpp/verilator_memutil.cc

As described in https://github.com/lowRISC/opentitan/issues/1245, the Ibex Verliator ELF processing does not exactly follow the algorithm for the "binary" target of objcopy (which it is intended to mimic). In particular, sections as denoted by program headers are laid down strictly sequentially, ignoring their specified `p_paddr` -- and resulting in a corrupted in-memory image for ELF images that have unordered program headers.

[verilator] Fix ELF processing

---

README.md
azure-pipelines.yml

- Only checks changed C source files
- Also add a note on C/C++ style to README
- Fixes #304

[ci] Add clang-format checking to CI

---

dv/uvm/riscv_dv_extension/ibex_log_to_trace_csv.py
dv/uvm/riscv_dv_extension/riscv_core_setting.sv

[DV] update ibex log parsing to match new riscv-dv csv format

---

examples/simple_system/README.md
examples/simple_system/rtl/ibex_simple_system.sv
examples/sw/simple_system/common/crt0.S
examples/sw/simple_system/common/simple_system_common.c
examples/sw/simple_system/common/simple_system_common.h
examples/sw/simple_system/common/simple_system_regs.h
examples/sw/simple_system/hello_test/hello_test.c
shared/rtl/timer.sv
shared/sim_shared.core

Not particularly useful in the current system, but gives an example of
how to handle interrupts.

[examples] Add timer example to simple system

---

ibex_core.core

[lint] Delete outdated comment in lint target

---

dv/uvm/Makefile
dv/uvm/cover.ccf
dv/uvm/sim.py
dv/uvm/yaml/rtl_simulation.yaml

Additionally created some new coverage targets to load coverage in VCS and IUS, respectively.

Enable coverage collection and merging for Incisive sims

---

dv/uvm/Makefile
dv/uvm/riscv_dv_extension/ml_testlist.yaml

[DV] Add riscv-dv target for ML

---

examples/simple_system/README.md

Improve wording in README of simple system

---

dv/uvm/riscv_dv_extension/testlist.yaml
dv/uvm/tests/core_ibex_test_lib.sv

[DV] Test debug requests during interrupt handler execution

---

dv/uvm/tests/core_ibex_test_lib.sv

Addresses the last issue brought up in #569

[dv] Fix a missed Riviera compile warning

---

examples/simple_system/README.md

@dawidzim does this look ok to you?

[doc] Riviera-PRO instructions for Simple System

---

dv/uvm/riscv_dv_extension/testlist.yaml

update testlist typo

---

azure-pipelines.yml

Fix failing pip install in CI

---

rtl/ibex_core.sv
rtl/ibex_id_stage.sv
rtl/ibex_load_store_unit.sv

Fixes #548
Fixes the long standing assertion problem from the linked issue as well as a new problem that was introduced with the branch target ALU.

[rtl] Fix assertion issues

---

syn/syn_yosys.sh

* prim_assert now an include so add appropriate include dir
* remove FPGA reg file from synthesised files

[syn] Fix synthesis script

---

dv/uvm/yaml/rtl_simulation.yaml

VCS compile fix

---

rtl/ibex_tracer.sv

hey!
this function should be automatic because `string desc = "";` is cleared only once at start

Tracer: Mark all functions "automatic"

---

ibex_core.core
lint/verilator_waiver.vlt
rtl/ibex_if_stage.sv
shared/rtl/timer.sv

A sequence of patches that fixes various verilator warnings. Note that this depends on PR #544.

Verilator warnings

---

dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_slave_seq_lib.sv

Fix qrun compile warning

---

doc/integration.rst
doc/pipeline_details.rst
dv/cs_registers/reg_driver/reg_dpi.cc
dv/cs_registers/reg_driver/reg_dpi.sv
dv/cs_registers/reg_driver/register_driver.cc
dv/cs_registers/reg_driver/register_driver.h
dv/cs_registers/tb/tb_cs_registers.sv
dv/riscv_compliance/ibex_riscv_compliance.core
dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
dv/uvm/core_ibex/ibex_dv.f
examples/simple_system/ibex_simple_system.core
examples/simple_system/rtl/ibex_simple_system.sv
ibex_core.core
rtl/ibex_controller.sv
rtl/ibex_core.sv
rtl/ibex_core_tracing.sv
rtl/ibex_cs_registers.sv
rtl/ibex_decoder.sv
rtl/ibex_ex_block.sv
rtl/ibex_fetch_fifo.sv
rtl/ibex_id_stage.sv
rtl/ibex_if_stage.sv
rtl/ibex_load_store_unit.sv
rtl/ibex_multdiv_fast.sv
rtl/ibex_multdiv_slow.sv
rtl/ibex_pkg.sv
rtl/ibex_wb_stage.sv

As the branch target ALU isn't in yet I'm afraid this PR is both branch target ALU and third pipeline stage, it will be rebased on master once that's in (i.e. this PR will be 3rd pipe stage only before it gets merged, it isn't intended to do both at once)
This is a draft for now as there's three things that must be done before it is committed:
* Update the documentation
* Run the riscv-dv testbench on UVM on the 2 stage configuration and check I haven't broken anything
* Check I haven't killed timing on the FPGA for two stage
I think performance counters may also be a bit dodgy.
riscv compliance passes for both 2 and 3 stage configs, coremark runs and gives around a 14.5% speed-up vs branch target ALU alone (when using a hacked up version of simple system that gives dual-port memory, I …

Third pipe stage

---

doc/icache.rst
doc/images/icache_block.svg
doc/images/icache_mux.svg
doc/index.rst
doc/introduction.rst
rtl/ibex_icache.sv

- Just the working prototype of RTL, documentation will follow
- Still many TODOs to be dealt with

[I-Cache] Initial commit of prototype RTL

---

dv/uvm/core_ibex/yaml/rtl_simulation.yaml

Hi, I make PR to support for qrun simulator. I try to run; however, I got a lot of warning for compilation, and optimization. I attach the output file. Could you help me take the look? I hope qrun can support for running `ibex`. Thank you
[qrun_compile_optimize.log](https://github.com/lowRISC/ibex/files/4238391/qrun_compile_optimize.log)

Add support for Qrun Questa

---

dv/uvm/core_ibex/tests/core_ibex_test_lib.sv

[dv] update timeout for INITIALIZED response

---

dv/uvm/core_ibex/riscv_dv_extension/ml_testlist.yaml

[ml] fix irq test for ML

---

rtl/ibex_if_stage.sv

- ready_i input to the prefetch buffer factored both it's own valid_o
output and the pc_set branch signal, neither of which are required.
- Refactoring the ready_i signal to just id_in_ready_i improves timing
significantly for the icache.
- Also removed offset_in_init signal which appeared to serve no purpose.

[rtl] IF stage timing fix

---

rtl/ibex_id_stage.sv
rtl/ibex_multdiv_fast.sv

* single cycle multiplier configuration needlessly stalled for a cycle
* mult_hold wasn't being set in mult state machine in single cycle
multiplier

[rtl] Fixes for single-cycle mutiply

---

dv/uvm/core_ibex/yaml/rtl_simulation.yaml

I make PR to suppress warning vlog-2583 for silence warning
Fixed: #696

Questa qrun: Extra checking for conflicts with always_comb and always_latch variables is done at vopt time

---

dv/uvm/core_ibex/Makefile

Explicitly use bash in UVM Makefile

---

dv/uvm/core_ibex/yaml/rtl_simulation.yaml

[dv] workaround for dsim compile error

---

dv/uvm/core_ibex/Makefile
dv/uvm/core_ibex/yaml/rtl_simulation.yaml

Hey!
In UVM makefile, I added passing parameter value from macro and in `rtl_simulation.yaml` sv_seed in cmd option

Added simulation option , added sv_seed in sim cmd for Riviera

---

doc/concierge.rst
doc/index.rst

Add a document how we plan to run the Ibex Concierge duty.

[doc] Add Ibex Concierge documentation

---

doc/icache.rst

The new information is:
- Branch addresses must be 16-bit aligned.
- Explicitly allow top 16 bits of rdata to change when lower 16 bits
contain a compressed instruction.
- Explicitly allow the core to drop ready without valid.
I've also rejigged the layout slightly, improving (I think!) the
description of compressed and uncompressed instructions.

Clarifications in icache detailed documentation

---

doc/verification.rst

Signed-off-by: Michael Gielda <mgielda@antmicro.com>

Fix rst syntax

---

rtl/ibex_icache.sv

- Requests receiving a PMP error need to output a valid indicator, even
though they will not have received any beats of data

[rtl] Fix icache PMP error handling

---

shared/rtl/bus.sv
shared/rtl/ram_1p.sv
shared/rtl/ram_2p.sv

Need these fixes to pass Xcelium compile in OpenTitan
Signed-off-by: Weicai Yang <weicai@google.com>

[dv] Fix Xcelium compilation

---

rtl/ibex_icache.sv

[rtl/icache] Fix typo in ram req

---

dv/uvm/data/sim.mk
dv/uvm/icache/dv/Makefile
vendor/lowrisc_dvsim.lock.hjson
vendor/lowrisc_ip/dvsim/Deploy.py
vendor/lowrisc_ip/dvsim/FlowCfg.py
vendor/lowrisc_ip/dvsim/LintCfg.py
vendor/lowrisc_ip/dvsim/Modes.py
vendor/lowrisc_ip/dvsim/OneShotCfg.py
vendor/lowrisc_ip/dvsim/SimCfg.py
vendor/lowrisc_ip/dvsim/SynCfg.py
vendor/lowrisc_ip/dvsim/dvsim.py
vendor/lowrisc_ip/dvsim/sim_utils.py
vendor/lowrisc_ip/dvsim/testplanner.py
vendor/lowrisc_ip/dvsim/testplanner/class_defs.py
vendor/lowrisc_ip/dvsim/testplanner/testplan_utils.py
vendor/lowrisc_ip/dvsim/utils.py

This is two patches, because the dvsim command line has changed slightly (the `--skip-ral` argument) and there's a change needed in `uvm/data/sim.mk`. I'm not sure whether this approach (two patches) is better or whether the two changes should be squashed into a single patch to avoid breaking bisection. Thoughts?

Vendor in latest version of dvsim from OpenTitan

---

rtl/ibex_id_stage.sv

- Stalls due to preceding memory accesses in the WB stage shouldn't
cause the jump signal to remain high.
- The jump signal being stuck high causes repeated memory accesses to
the same address, and unnecessary stalling.
- Fixes lowRISC/opentitan#2099

[rtl] Fix jump signal stuck high during stall

---

dv/uvm/core_ibex/riscv_dv_extension/ibex_log_to_trace_csv.py

Currently the riscv-dv functional coverage flow errors out when run on Ibex trace logs. This is because the operand string that this coverage flow analyzes is assumed to contain ABI register names, but Ibex does not display registers in ABI, thus the coverage test decides that it doesn't understand the Ibex CSV trace and exits out.
This PR fixes this issue by converting all register names in this operand string to ABI format, allowing the functional coverage flow to proceed as normal.

[dv/fcov] Fix Ibex log parsing script

---

dv/uvm/data/common_project_cfg.hjson
dv/uvm/data/common_sim_cfg.hjson
dv/uvm/data/fusesoc.hjson
dv/uvm/data/sim.mk
dv/uvm/data/vcs/vcs.hjson
dv/uvm/data/xcelium/xcelium.hjson

As per the discussion in #840, I've aligned the dvsim config files in `dv/uvm/data` as much as possible with their updated counterparts in the main OpenTitan repository.

[dv] Manually update dvsim config files

---

dv/cs_registers/tb/tb_cs_registers.sv

- Only specifying the signals that the TB cares about means people will
no longer have to update this file every time the cs_regs port list
changes

[dv/cs_registers] Remove .* binding

---

vendor/google_riscv-dv.lock.hjson
vendor/google_riscv-dv/pygen/experimental/README.md
vendor/google_riscv-dv/pygen/experimental/riscv_asm_program_gen.py
vendor/google_riscv-dv/pygen/experimental/riscv_callstack_gen.py
vendor/google_riscv-dv/pygen/experimental/riscv_data_page_gen.py
vendor/google_riscv-dv/pygen/experimental/riscv_directed_instr_lib.py
vendor/google_riscv-dv/pygen/experimental/riscv_instr_base.py
vendor/google_riscv-dv/pygen/experimental/riscv_instr_sequence.py
vendor/google_riscv-dv/pygen/experimental/riscv_instr_stream.py
vendor/google_riscv-dv/pygen/experimental/riscv_load_store_instr_lib.py
vendor/google_riscv-dv/pygen/experimental/riscv_rand_instr.py
vendor/google_riscv-dv/pygen/experimental/utils.py
vendor/google_riscv-dv/run.py
vendor/google_riscv-dv/src/riscv_pmp_cfg.sv

dv to revision 162ea7312d21ac0b8ae73669fb68bf284b68f851
* Add experimental python based generator (google/riscv-dv#567)
(taoliug)
* Check return code for ovpsim (google/riscv-dv#566) (taoliug)
* fix bug in PMP handler routine (google/riscv-dv#562) (udinator)

Update google_riscv-dv to google/riscv-dv@162ea73

---

doc/icache.rst
dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_protocol_checker.sv

Tom, could you have a look at the 2nd patch in particular, to check that it matches what you think should be going on?

Fix two bugs in the icache <-> core protocol checker

---

dv/uvm/core_ibex/Makefile

See issue #852 for discussion.

Print commands in core_ibex/Makefile when VERBOSE=1

---

rtl/ibex_controller.sv

- The controller state machine could only progress to FLUSH to handle an
exception if instr_valid_i was set
- When the exception comes from a load/store in the Writeback stage, and
no new instruction has been driven into the ID stage, this could cause
exception to be missed
- The instr_valid_i qualification is therefore removed from the state
machine as all relevant signals inside that if block are already
qualified by instr_valid_i anyway
- Fixes #849

[rtl] Fix instr_valid_i exception issue

---

dv/uvm/icache/dv/ibex_icache_mem_agent/seq_lib/ibex_icache_mem_resp_seq.sv

These patches fix two bugs that cropped up when I started branching in a constrained way as part of writing the "passthru" test.

Two bug-fixes in icache memory model

---

syn/tcl/lr_synth_flow_var_setup.tcl
syn/tcl/sta_utils.tcl
syn/tcl/yosys_run_synth.tcl

Used the synthesis flow recently which resulted in me adding these additions.
The flow is actually broken out of the box currently, there's some RTL issues to investigate which I haven't had time to do but could be quickly hacked around for getting the flow going.

Syn additions

---

dv/uvm/icache/dv/tb/tb.sv

- Fixes #904
- Will need a future update to drive the new signal properly

[dv] Add missing signal to i$ tb

---

dv/uvm/data/riviera/riviera.hjson
dv/uvm/data/riviera/riviera_run.do
dv/uvm/icache/dv/Makefile

Hey!
This is new PR for support Riviera-PRO in Icache mode.
Should I open another pull request in OpenTitan for change in file `vendor/lowrisc_ip/common_ifs/clk_rst_if.sv` ?

new version of Icache for Riviera-PRO

---

dv/uvm/icache/data/ibex_icache_testplan.hjson
dv/uvm/icache/dv/env/ibex_icache_env.core
dv/uvm/icache/dv/env/ibex_icache_scoreboard.sv
dv/uvm/icache/dv/env/seq_lib/ibex_icache_caching_vseq.sv
dv/uvm/icache/dv/env/seq_lib/ibex_icache_passthru_vseq.sv
dv/uvm/icache/dv/env/seq_lib/ibex_icache_vseq_list.sv
dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_driver.sv
dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_req_item.sv
dv/uvm/icache/dv/ibex_icache_core_agent/seq_lib/ibex_icache_core_base_seq.sv
dv/uvm/icache/dv/ibex_icache_sim_cfg.hjson

This matches the "caching" test on the test plan.

Add a "caching" sequence to ICache UVM tests

---

vendor/lowrisc_ip.lock.hjson
vendor/lowrisc_ip/common_ifs/clk_rst_if.sv
vendor/lowrisc_ip/dv_lib/dv_base_monitor.sv
vendor/lowrisc_ip/dvsim/FlowCfg.py
vendor/lowrisc_ip/dvsim/Modes.py
vendor/lowrisc_ip/dvsim/OneShotCfg.py
vendor/lowrisc_ip/dvsim/SimCfg.py
vendor/lowrisc_ip/dvsim/dvsim.py
vendor/lowrisc_ip/dvsim/testplanner/README.md
vendor/lowrisc_ip/prim/rtl/prim_arbiter_ppc.sv
vendor/lowrisc_ip/prim/rtl/prim_filter.sv
vendor/lowrisc_ip/prim/util/primgen.py

Update code from upstream repository
https://github.com/lowRISC/opentitan to revision
d78da129c7f2b115ccabd1c3af199e0e5812f365
* [dv] Fix loop when waiting for end of run phase in dv_base_monitor
(Rupert Swarbrick)
* [util] Remove docgen references (Tobias Wölfel)
* [dvsim] Small tidy-ups in dvsim.py command line parsing (Rupert
Swarbrick)
* [dvsim] Tidy up wave dumping logic (Rupert Swarbrick)
* [dv/xbar] Add chip-level xbar support (Weicai Yang)
* [prim] Fix lint errors (Pirmin Vogel)
* [prim] Rework how primgen.py writes out parameter lists for
instantiations (Pirmin Vogel)
Signed-off-by: Rupert Swarbrick <rswarbrick@lowrisc.org>

Update lowrisc_ip to lowRISC/opentitan@d78da129

---

rtl/ibex_wb_stage.sv

- unpacked array decending order
- unspecified generate block

Fix Writeback stage lint errors

---

python-requirements.txt

Add missing dependency on python3-bitstring to python-requirements

---

README.md
ibex_configs.yaml

- Some basic info about a few possible design points and their
area/perf/dv status

[doc] Add top-level status table

---

dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_driver.sv

This signal already got driven (to 1) when signalling a branch with
the interface's branch_to task. This patch now drives the `branch_spec`
line occasionally even if we don't actually do a branch. (One cycle in
64, for now).

Drive the branch_spec line in ICache UVM tests

---

rtl/ibex_decoder.sv

Signed-off-by: Bert Pieters <bert.pieters@gmail.com>
for fox issue https://github.com/lowRISC/ibex/issues/30

fix for #30

---

dv/riscv_compliance/ibex_riscv_compliance.core
dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
examples/simple_system/ibex_simple_system.core
examples/simple_system/rtl/ibex_simple_system.sv
examples/sw/simple_system/pa_test/Makefile
examples/sw/simple_system/pa_test/pa_test.c
ibex_core.core
rtl/ibex_cipher.sv
rtl/ibex_core.sv
rtl/ibex_core_tracing.sv
rtl/ibex_cs_registers.sv
rtl/ibex_decoder.sv
rtl/ibex_id_stage.sv
rtl/ibex_pkg.sv
rtl/ibex_pointer_authentication.sv

I'm participating in a project called "Proof-of-concept integration of pointer authentication support in Ibex" in GSoC 2020.
- Instantiate Pointer Authentication module
- Add basic Pointer Authentication test

Add Pointer Authentication module

---

syn/lec_sv2v.do
syn/lec_sv2v.sh

This adds an LEC script to check if the Verilog generated by sv2v is logically equivalent to the original SystemVerilog.

Add LEC script to formally verify sv2v translation

---

rtl/ibex_controller.sv
rtl/ibex_core.sv
rtl/ibex_id_stage.sv

Fixes lowRISC#957
Signed-off-by: Bert Pieters <bert.pieters@gmail.com>

[rtl] disable clock between reset and fetch_enable_i

---

rtl/ibex_tracer.sv
rtl/ibex_tracer_pkg.sv

I update tracer for pac and aut instructions. Currently, for simplicity, only mnemonic is displayed.

Update tracer for PAC and AUT

---

doc/performance_counters.rst
dv/verilator/pcount/cpp/ibex_pcounts.cc
examples/sw/benchmarks/coremark/ibex/core_portme.c
rtl/ibex_core.sv
rtl/ibex_cs_registers.sv
rtl/ibex_id_stage.sv

I add the following to the counter.
- Number of pac instructions retired     
- Number of aut instructions retired

Add PAC and AUT counters

---

rtl/ibex_icache.sv

The Icache might not be fully perfect, but it's certainly not a draft
any more.

Icache: It's not a draft any more

---

azure-pipelines.yml
examples/simple_system/rtl/ibex_simple_system.sv

The existing setup had a couple mixups in them which failed them to be effective.

Enforce lint of simple system in CI

---

dv/uvm/data/riviera/riviera.hjson

Hey!
Can we increase time of simulation in Icache tests?

increase time in Icache simulation

---

doc/security.rst
rtl/ibex_core.sv
rtl/ibex_if_stage.sv

- Checks that PC increments as expected
- Raises an alert if not

[rtl] Add security hardened PC

---

dv/uvm/core_ibex/tests/core_ibex_test_lib.sv

These typos cause compilation failures.

[dv] Fix typos

---

dv/uvm/core_ibex/riscv_dv_extension/csr_description.yaml

This is related to lowRISC/ibex#1038. It does not yet do the trick and @udinator mentioned that some more work in riscv-dv is required for this. Thus, I am leaving this as a draft.

[dv] Add custom CSRs to yaml description file

---

CREDITS.md

Add myself to CREDITS.md

---

doc/introduction.rst

Clarify FPGA register file situation in introduction.

[doc] Update FPGA Synthesis Paragraph in Intro

---

dv/uvm/core_ibex/riscv_dv_extension/ml_testlist.yaml

-adds the PMP CSR write sequence to all tests
-enables B-extension instructions in all tests

[ibex/ml] Update the ML testlist

---

syn/python/get_kge.py
syn/syn_yosys.sh

[syn] Add script to print kGE equivalent

---

dv/uvm/core_ibex/riscv_dv_extension/ibex_log_to_trace_csv.py

This PR makes a few changes to how we convert the Ibex trace logs into
CSV format for the riscv-dv functional coverage flow.
1) We now write an entry for every executed instruction into the output
CSV file, as not doing this will skew functional coverage results.
2) We now parse and organize instruction operands a little differently,
to match recent updates to the CSV format (in the upstream riscv-dv
repo).
Operands for instructions that look like this:
`<instr> <rd>, <rs1>(<imm>)`
are now displayed in the CSV file as `<rd>,<rs1>,<imm>` whereas
previously they were displayed as `<rd>,<imm>,<rs1>`.
3) The parsing script now supports bitmanipulation pseudo-instructions.

[ibex/dv] Update CSV log conversion script

---

.svlint.toml
dv/cs_registers/tb/tb_cs_registers.sv
dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
dv/riscv_compliance/rtl/riscv_testutil.sv
dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_if.sv
examples/simple_system/rtl/ibex_simple_system.sv

Fixed linter issues found by the `svlint` tool.

Fix lint issues

---

doc/03_reference/security.rst
rtl/ibex_core.sv
rtl/ibex_cs_registers.sv

Instantiate shadow CSRs and wire up to the alert output.

[rtl] Instantiate shadow CSRs

---

rtl/ibex_cs_registers.sv

- Reduce the size of the PMP address configuration registers to the permissible minimum depending on granularity.
- Ensure consistency between PMP address CSR reads and the addresses forwarded to the PMP module.
- Follow the specification more strictly, by returning bits pmpaddr[G-2:0] as all ones when pmpcfg.A[1] is set (i.e. mode is NAPOT or NA4, though the latter is invalid for G > 0) and bits pmpaddr[G-1:0] as all zeros when pmpcfg.A[0] is clear (i.e. mode is OFF or TOR).
- Fixes #1181

[rtl] Reduce size of PMP addr CSRs to minimum

---

dv/uvm/core_ibex/sim_makefrag_gen.py
dv/uvm/core_ibex/yaml/rtl_simulation.yaml
util/ibex_config.py

[dv/ibex] add support for DSim

---

Bender.yml

Hi @vogelpi,
This pull request adds a `Bender.yml` file for updated dependency management in PULP. It allows dependency management for the core using [bender](https://github.com/fabianschuiki/bender).

Add Bender.yml for PULP

---

syn/syn_yosys.sh

Path to primitives has been updated

[syn] Fix path in synthesis script

---

dv/uvm/core_ibex/riscv_dv_extension/ibex_log_to_trace_csv.py
dv/uvm/core_ibex/sim.py

This fixes up a few frustrations I've had with the way the regression reporting works. We could clean things up further and improve the python but we're a bit constrained by the way `compare_trace_csv` works from RISCV DV. It outputs to a named logfile and directly reports [PASSED] or [FAILED] into the log so we can't alter how that works nor easily redirect its output somewhere unless we use a temp file for it to write to and we read back from it. I think we're better off changing `compare_trace_csv` in RISCV DV to be more flexible for reporting or reimplementing it on our side.
* Handle missing log files with error messages rather than terminating
on unhandled exceptions
* Output potential failure causes from sim log file into regression log
* Alter per test output to make it clearer …

[dv] Improve sim.py error reporting

---

dv/uvm/core_ibex/sim.py

The UVM log should be checked for failures before attempting to process
the core trace log. A simulation failure could mean the trace log
doesn't exist and is is preferable to report the simulation error from
the log rather than trace not found as a failure cause.

[dv] Reorder checks in sim.py

---

rtl/ibex_controller.sv

* `if` in `DBG_TAKEN_IF` is needless as the conditions it checks will be
true if controller enters `DBG_TAKEN_IF` state
* flop `enter_debug_mode` so `FLUSH` state looks at what
`enter_debug_mode` was when it was seen in `DECODE` state rather than
what it has become. In particular the controller could enter `FLUSH`
on the basis of performing a WFI then divert down the debug control
path due to a new debug request being raised. In this instance it is
preferable for the WFI to complete entering `SLEEP` before the debug
request wakes the core back up.

[rtl] Debug mode controller changes

---

rtl/ibex_alu.sv
rtl/ibex_controller.sv
rtl/ibex_cs_registers.sv
rtl/ibex_decoder.sv

Fixes up some of the issues from the OpenTitan Ascent lint report (https://reports.opentitan.org/hw/ip/rv_core_ibex/lint/ascentlint/latest/results.html)
A couple of issues on that report relate to things in the OT repository, others I think are either tool issues or should be waived.

[rtl] Lint fixes for Ascent lint issues

---

doc/02_user/integration.rst
dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
examples/fpga/artya7/rtl/top_artya7.sv
examples/simple_system/rtl/ibex_simple_system.sv
rtl/ibex_core.sv
rtl/ibex_core_tracing.sv
rtl/ibex_pkg.sv

Relates to lowrisc/opentitan#4618

[rtl] Add crash dump outputs

---

rtl/ibex_cs_registers.sv
rtl/ibex_pkg.sv

edited ibex_cs_registers.sv

---

rtl/ibex_core.sv

[rtl] Minor lint fix in ibex_core.sv

---

doc/02_user/system_requirements.rst
doc/conf.py
tool_requirements.py
util/check_tool_requirements.py

[util] Document minimum VCS version

---

dv/uvm/core_ibex/tests/core_ibex_test_lib.sv

This will produce a 'KNOWN FAILURE' message when we hit the #1313
This still turns into a failure for the regression. I don't think it should become a pass but if we're happy with this we can modify 'sim.py' to have a third known failure category using regexs to match against errors to decide which failures are known failures.

[dv] Add known failure detection to riscv_debug_ebreakmu_test

---

rtl/ibex_cs_registers.sv
rtl/ibex_id_stage.sv

The read enables should only be asserted where an actual RF read will
occur. Where there is an illegal instruction or a fetch error the raw
decoder signals might still be asserted but should be squashed before
they become the true enable signals.

[rtl] Fix RF read enables for illegal instruction/fetch error

---

dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
rtl/ibex_controller.sv

A previous PR (#1329) has the RTL fixes, this is just to review the fcov changes. Other PR will get merged first.

Ibex fcov2

---

rtl/ibex_top.sv

Signed-off-by: Timothy Chen <timothytim@google.com>

[ibex] Fix buffer instantiations

---

doc/02_user/integration.rst
rtl/ibex_lockstep.sv
rtl/ibex_top.sv
rtl/ibex_top_tracing.sv

Signed-off-by: Timothy Chen <timothytim@google.com>

[ibex] Add reset bypass controls

---

rtl/ibex_icache.sv

No functional change.
This is needed to get the code AscentLint clean when vendored into OpenTitan.

[rtl] Break long lines in icache

---

rtl/ibex_top.sv

See lint report here: https://reports.opentitan.org/hw/ip/rv_core_ibex/lint/ascentlint/2021.04.28_15.08.13/results.html

[rtl] Fix lint issues

---

dv/uvm/core_ibex/yaml/rtl_simulation.yaml

Hey!
Few changes in Riviera-PRO compilation and simulation command

Changes simulation command for Riviera 2021.04

---

doc/02_user/system_requirements.rst

Triggered by the question at #1365.

Describe where to find a RISC-V toolchain

---

dv/uvm/core_ibex/Makefile
dv/uvm/core_ibex/riscv_dv_extension/csr_description.yaml
rtl/ibex_decoder.sv
rtl/ibex_lockstep.sv

Small fixes to the RTL and testbench to fix issues seen in nightly runs

Various fixes for known simulation issues

---

doc/02_user/integration.rst
dv/uvm/core_ibex/common/irq_agent/irq_request_driver.sv
dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
dv/uvm/core_ibex/tests/core_ibex_base_test.sv
rtl/ibex_core.sv
rtl/ibex_lockstep.sv
rtl/ibex_top.sv

Minor rtl and testbench updates to extend the functionality of fetch_en_i

Update the meaning of fetch_en_i

---

python-requirements.txt

From OpenTitan pull request #6769

Avoid premailer 3.9.0 due to API breakage

---

ibex_top.core
ibex_top_tracing.core

This configuration is the closest we can get to our style guide right
now, so let's go with that.

Copy verible-format configuration from OpenTitan

---

rtl/ibex_wb_stage.sv

Hey!
In this PR I added cast to enum, because we can't assign non-enum to enum LRM 6.19.3

Added cast to enum

---

dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_monitor.sv

Previously the monitor would emit write transactions the cycle the
request is seen and emit read transactions the cycle the response is
seen. This allowed later write transactions to be emitted before earlier
reads (where a new write transaction is started the cycle a read
response returns).
Now both read and write transactions are emitted when their response is
seen.
In addition the error field from the response is copied into the
transaction.

[dv] Fix transaction ordering in ibex_mem_intf_monitor

---

rtl/ibex_controller.sv
rtl/ibex_core.sv
rtl/ibex_counter.sv
rtl/ibex_cs_registers.sv
rtl/ibex_id_stage.sv
rtl/ibex_wb_stage.sv

A couple of small fixes that came up whilst working on the cosim DV

Ibex fixes

---

rtl/ibex_top_tracing.sv

Add missing parameters to ibex_top_tracing

---

azure-pipelines.yml
ci/ibex-rtl-ci-steps.yml
ci/install-build-deps.sh
doc/03_reference/cosim.rst
dv/cosim/cosim.h
dv/cosim/cosim_dpi.cc
dv/cosim/cosim_dpi.h
dv/cosim/cosim_dpi.svh
dv/cosim/spike_cosim.cc
dv/cosim/spike_cosim.h
dv/uvm/core_ibex/common/ibex_cosim_agent/ibex_cosim_scoreboard.sv
dv/uvm/core_ibex/yaml/rtl_simulation.yaml
dv/verilator/simple_system_cosim/README.md
dv/verilator/simple_system_cosim/ibex_cosim_setup_check.core
dv/verilator/simple_system_cosim/ibex_simple_system_cosim.core
dv/verilator/simple_system_cosim/ibex_simple_system_cosim_checker.sv
dv/verilator/simple_system_cosim/ibex_simple_system_cosim_checker_bind.sv
dv/verilator/simple_system_cosim/simple_system_cosim.cc
dv/verilator/simple_system_cosim/util/ibex_cosim_setup_check.sh
examples/simple_system/ibex_simple_system.cc
examples/simple_system/ibex_simple_system.core
examples/simple_system/ibex_simple_system.h
examples/simple_system/ibex_simple_system_core.core
examples/simple_system/ibex_simple_system_main.cc
examples/sw/benchmarks/coremark/ibex/core_portme.c
examples/sw/benchmarks/coremark/ibex/core_portme.mak

Simple system cosim

---

rtl/ibex_icache.sv

This PR resolves a couple of AscentLint errors we are seeing in OpenTitan.

[lint] Fix some AscentLint errors

---

doc/03_reference/coverage_plan.rst
doc/03_reference/index.rst
doc/03_reference/verification.rst

We may want to directly name coverpoints in this document so you can easily tie what's implemented to what's written here but for now I've left this out.

[dv] Add initial coverage plan

---

doc/03_reference/pmp.rst
ibex_core.core
rtl/ibex_cs_registers.sv
rtl/ibex_pmp_reset_default.svh

[rtl,doc] Add customisable PMP reset values

---

doc/02_user/integration.rst

[doc] Fix RV32B enum description

---

examples/simple_system/README.md

[doc] Add srecord as simple_system prerequisite in README

---

doc/03_reference/verification.rst
dv/uvm/core_ibex/Makefile
dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml

Also tweak the `verification.rst` documentation a little bit to reflect how things now work (ovpsim won't).

Re-enable bitmanip tests

---

doc/03_reference/icache.rst
doc/03_reference/security.rst
dv/uvm/icache/dv/tb/ic_top.sv
rtl/ibex_core.sv
rtl/ibex_cs_registers.sv
rtl/ibex_dummy_instr.sv
rtl/ibex_icache.sv
rtl/ibex_id_stage.sv
rtl/ibex_if_stage.sv
rtl/ibex_lockstep.sv
rtl/ibex_multdiv_fast.sv
rtl/ibex_multdiv_slow.sv
rtl/ibex_register_file_ff.sv
rtl/ibex_register_file_latch.sv
rtl/ibex_top.sv

These are used by the OpenTitan project to track the implementation of
security countermeasures

[rtl] Add SEC_CM markers for security features

---

dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_monitor.sv
dv/uvm/icache/dv/ibex_icache_sim_cfg.hjson
dv/uvm/icache/dv/tb/tb.sv

Fixed some trivial issues regarding hierarchical accesses and removed setting of some parameters from ibex_icache_sim_cfg.hjson file.

[icache, dv] Made changes required to make TB compatible with Xcelium

---

dv/uvm/icache/dv/env/ibex_icache_scoreboard.sv

There was issue with rtespect to calculating number of instructions per
word and this commit fixes that issue.
Number of instructions per word = 1/4*1 + 3/4(1/4*3/2 + 3/4*2) = 53/32.
Earlier th5s was calculated as 7/4.
Ideal window length needed to calculate fetch ratio percentage is
calculated as 53/32*C*2 = 848. Earlier it was calculated to be 300.

[icache, dv] Fixed regression failure in ibex_icache_back_line

---

dv/uvm/icache/dv/env/ibex_icache_env.core
vendor/lowrisc_ip.vendor.hjson
vendor/lowrisc_ip/dv/sv/push_pull_agent/README.md
vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_agent.core
vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_agent.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_agent_cfg.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_agent_cov.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_agent_pkg.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_driver_lib.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_if.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_item.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_monitor.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_sequencer.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/seq_lib/push_pull_base_seq.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/seq_lib/push_pull_device_seq.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/seq_lib/push_pull_host_seq.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/seq_lib/push_pull_indefinite_host_seq.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/seq_lib/push_pull_seq_list.sv

Update code from upstream repository
https://github.com/lowRISC/opentitan to revision
7c4f8b3fde4bb625ac3330ff52d3f66507190fe5
Signed-off-by: Prajwala Puttappa <prajwalaputtappa@lowrisc.org>

Update lowrisc_ip to lowRISC/opentitan@7c4f8b3fd

---

dv/uvm/core_ibex/Makefile
dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
dv/uvm/core_ibex/sim.py
dv/uvm/core_ibex/yaml/rtl_simulation.yaml

Enables coverage collection while running the ibex-dv with xcelium.

Coverage support with Cadence Tools

---

rtl/ibex_alu.sv
rtl/ibex_lockstep.sv

[lint] Minor fixes

---

dv/uvm/core_ibex/Makefile

This PR also reworks some comments for clarity around creating dependencies on Makefile variables.

Add better dependencies for the coverage gen and merge targets in core-ibex dv

---

dv/uvm/core_ibex/scripts/compile-tb.py
dv/uvm/core_ibex/yaml/rtl_simulation.yaml

This makes things much easier for OpenTitan integration.

Allow compiling the TB when the working directory isn't core_ibex

---

dv/uvm/core_ibex/Makefile
dv/uvm/core_ibex/list_tests.py

This fixes a bug introduced by 14c400c, where I sort of half made this
change but didn't follow through the whole way!

Don't pass --iterations to list_tests.py if not overriding it

---

dv/uvm/core_ibex/Makefile
dv/uvm/core_ibex/scripts/compile-tb.py
dv/uvm/core_ibex/scripts/merge-cov.py
dv/uvm/core_ibex/scripts/run-rtl.py
dv/uvm/core_ibex/yaml/rtl_simulation.yaml

Makes coverage work for VCS and XLM.

[dv] Coverage fixes

---

dv/riscv_compliance/ibex_riscv_compliance.core
dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
dv/verilator/simple_system_cosim/ibex_simple_system_cosim.core
examples/simple_system/ibex_simple_system.core
examples/simple_system/rtl/ibex_simple_system.sv
ibex_configs.yaml
ibex_core.core
ibex_top.core
ibex_top_tracing.core
util/ibex_config.py

Updated the parameters with respect to top_earlgrey.hjson in OpenTitan
repository. For other builds, kept the previously undeclared parameters
as their default values.

Updating parameters for OpenTitan option

---

ci/ibex-rtl-ci-steps.yml
doc/03_reference/cosim.rst
doc/03_reference/verification.rst
dv/uvm/core_ibex/Makefile
dv/uvm/core_ibex/scripts/compile-tb.py
dv/uvm/core_ibex/tests/core_ibex_base_test.sv
dv/uvm/core_ibex/yaml/rtl_simulation.yaml
dv/verilator/simple_system_cosim/ibex_cosim_setup_check.core

Updated version of pr #1613 , as the build scripts have been significantly refactored underneath.

Cosim rebase

---

rtl/ibex_top.sv

Opening a PR to resolve issue #1514. Plain (ie. not scrambled) memory primitives are instantiated conditionally when parameter ICacheScramble=0. This change eliminates some unused logic when scrambling is disabled.
I have successfully run riscv_machine_mode_rand_test with and without ICache enabled, as well as with and without ICache scrambling enabled. I have also run synthesis and see a minor reduction in cell area about 10-15% when ICache is enabled without scrambling, not including memory area itself.

Instantiate plain memory primitives for ICache when ICache scrambling is disabled

---

doc/03_reference/coverage_plan.rst
dv/uvm/core_ibex/fcov/core_ibex_csr_categories.svh
dv/uvm/core_ibex/fcov/core_ibex_fcov_bind.sv
dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv
dv/uvm/core_ibex/riscv_dv_extension/ibex_asm_program_gen.sv
dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
rtl/ibex_controller.sv
rtl/ibex_core.sv
rtl/ibex_pmp.sv

PMP related coverage points are not included in this PR.

[dv] Various functional coverage point additions

---

doc/03_reference/coverage_plan.rst
dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv

Involves documentation changes and elaborated interrupt coverage.

[fcov] Implementing Interrupts section of coverage plan

---

doc/03_reference/coverage_plan.rst
dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv
rtl/ibex_load_store_unit.sv

Adding MSECCFG CSR related functionality also some write checks etc.

[dv] PMP related functional coverage points

---

dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_seq_lib.sv

If you call the `read()` function on the memory model with an
uninitialised word, it generates a UVM error.
This is reasonable for data memory (where we never want to read
something without an architectural value) but is not reasonable for
IMEM, where Ibex runs ahead. Squash the error in this case, but force
bad integrity for the fetch to make sure we see something explode.
This was inspired by trying to debug riscv_csr_test. It still fails after this change, but for different reasons :-) Specifically, it's designed so that if a check fails then it jumps to the end of its instructions and loops forever. Before this change, it then died immediately when Ibex read ahead. Now it hangs (arguably not much of an improvement!)

[dv,core_ibex] Allow instructions near the top of initialised IMEM

---

doc/03_reference/coverage_plan.rst
dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv

This fixes up some minor issues in the functional coverage plan and implemented cover points

[dv/doc] Tweaks/fixes to functional coverage

---

dv/uvm/core_ibex/common/irq_agent/irq_request_driver.sv
dv/uvm/core_ibex/env/core_ibex_vseqr.sv
dv/uvm/core_ibex/tests/core_ibex_base_test.sv
dv/uvm/core_ibex/tests/core_ibex_new_seq_lib.sv
dv/uvm/core_ibex/tests/core_ibex_seq_lib.sv
dv/uvm/core_ibex/tests/core_ibex_test_pkg.sv
dv/uvm/core_ibex/tests/core_ibex_vseq.sv

- Adds comments for explanations of test and library functionality
- Refactor types and naming of control knob signals for clarity
- Move constraints from MEMBER to CLASS for more flexibility
- Add missing license header

Commenting UVM testbench code, tidy formatting, minor refactoring

---

azure-pipelines.yml
ci/ibex-rtl-ci-steps.yml
examples/sw/simple_system/pmp_smoke_test/Makefile
examples/sw/simple_system/pmp_smoke_test/pmp_smoke_test.c
util/ibex_config.py

As I'd already written it thought it may be worth adding as a test for CI.
I've actually got a far more comprehensive PMP smoke test (and Silvestrs also had something he was working on before he left https://github.com/lowRISC/ibex/pull/1524). I think some form of that would be useful to add but more work to be done.

Pmp exception test

---

rtl/ibex_id_stage.sv

Registering instruction fetch errors causes problem in the case of seeing
a PMP execution access block. ID/EX stage learns about
the instruction that it executed should be blocked a
cycle late. This commit fixes that.
Found this one while working on fixing https://github.com/lowRISC/ibex/issues/1720. However it does not fully solves the issue because we are still seeing some mismatches because of some self modifying code problems.

[rtl] Do not register instruction fetch errors

---

rtl/ibex_cs_registers.sv

A rule that allows M mode execution (either M mode only or shared M/U
mode) cannot be added when MML is set, unless RLB is also set.
Fixes #1740

[rtl] Cannot add M mode executable PMP regions when MML = 1

---

rtl/ibex_cs_registers.sv
rtl/ibex_icache.sv

[lint] Make case statements unique case

---

rtl/ibex_register_file_ff.sv

Previously it had two packed dimensions. In general we prefer the use of unpacked arrays for this kind of usage. In particular this had an impact on trace viewing in GTKWave, the two dimensions were flattened into a single large bus which made determining individual register values tricky.
I did some git archeology and it looks like it has been this way since Ibex was created from Zero-riscy. I can't see any reason it needs to be two packed dimensions. @msfschaffner adding you as a reviewer to comment in case there's something I'm missing.

[rtl] Switch FF RF to use unpacked arrays

---

dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
dv/uvm/core_ibex/ibex_dv.f
dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
examples/simple_system/rtl/ibex_simple_system.sv
formal/riscv-formal/Makefile
ibex_core.core
rtl/ibex_controller.sv
rtl/ibex_core.f
rtl/ibex_core.sv
rtl/ibex_cs_registers.sv
rtl/ibex_decoder.sv
rtl/ibex_id_stage.sv
rtl/ibex_lockstep.sv
rtl/ibex_pkg.sv
rtl/ibex_top.sv
rtl/ibex_top_tracing.sv
rtl/ibex_xif_issue_commit_buffer.sv
src_files.yml

This pull request adds issue interface, commit interface, and result interface of the Core-V X-Interface for Ibex.
This commit passes the verification without accelerator and with an external pseudo accelerator.
This is still a draft of the implementation, I am keep working on further verification.

CORE-V Extension Interface - Add Issue, Commit, and Result Interface

---

dv/riscv_compliance/ibex_riscv_compliance.core
dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
dv/verilator/simple_system_cosim/ibex_simple_system_cosim.core
examples/simple_system/ibex_simple_system.core
examples/simple_system/rtl/ibex_simple_system.sv
ibex_configs.yaml
ibex_core.core
ibex_top.core
ibex_top_tracing.core
rtl/ibex_alu.sv
rtl/ibex_core.sv
rtl/ibex_ex_block.sv
rtl/ibex_id_stage.sv
rtl/ibex_load_store_unit.sv
rtl/ibex_lockstep.sv
rtl/ibex_pkg.sv
rtl/ibex_top.sv
rtl/ibex_top_tracing.sv
rtl/ibex_wb_stage.sv
rtl/ibex_xif_issue_commit_buffer.sv

This commit adds memory interface and memory result interface
of the RISC-V Extension Interface.

 CORE-V Extension Interface - Add memory and memory result interfaces

---

azure-pipelines.yml
ci/install-build-deps.sh
ci/vars.yml

Draft PR to start with so I can test out the CI

[ci] Switch to downloading verilator from GCP bucket

---

dv/uvm/core_ibex/scripts/objdump.sh
dv/uvm/core_ibex/scripts/prettify.sh

- Shellcheck objdump script
- Check for RISCV_TOOLCHAIN variable
- Shellcheck prettify script

[dv] Improve objdump and prettify scripts

---

ci/install-build-deps.sh
dv/verilator/simple_system_cosim/util/ibex_cosim_setup_check.sh
examples/simple_system/spike-simple-system.sh
syn/lec_sv2v.sh
syn/syn_setup.example.sh
syn/syn_yosys.sh
syn/translate_timing_rpts.sh

I ran shellcheck on the bash scripts in the repository: https://www.shellcheck.net/

[lint] Shellcheck bash scripts in repo

---

doc/03_reference/coverage_plan.rst
dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
rtl/ibex_controller.sv

This fixes https://github.com/lowRISC/ibex/issues/1863

Misc fixes

---

doc/03_reference/security.rst

[doc] Add RF write enable glitch detection

---

dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_seq_lib.sv

Previously the memory model writes didn't work correctly leaving an incoherent view of memory.

[dv] Fix random data on uninit accesses

---

dv/uvm/core_ibex/riscv_dv_extension/ibex_asm_program_gen.sv

The tests `riscv_epmp_mmwp_test` and `riscv_epmp_mml_test` were failing due to timeouts because the `test_done` section was generated after the kernel stack, which is not marked as executable by default. This PR moves the `test_done` and `test_fail` section to before the main test program, which is marked as executable by default.

[dv,pmp] Put test done/fail sections before main for PMP tests

---

rtl/ibex_top.sv

This refactors the code to avoid a -1 index access that caused no issues in functional verification but caused lint errors and is problematic for formal tools.
Fixes #1799

[fpv] Fix linting issues in oustanding access tracking logic

---

dv/uvm/icache/doc/ibex_icache_dv_plan.md
dv/uvm/icache/dv/Makefile
dv/uvm/icache/dv/fcov/ibex_icache_fcov.core
dv/uvm/icache/dv/fcov/ibex_icache_fcov_bind.sv
dv/uvm/icache/dv/fcov/ibex_icache_fcov_if.sv
dv/uvm/icache/dv/ibex_icache_sim.core
dv/uvm/icache/dv/ibex_icache_sim_cfg.hjson
vendor/lowrisc_ip.lock.hjson
vendor/lowrisc_ip/dv/sv/mem_bkdr_util/mem_bkdr_util__rom.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_agent_cfg.sv
vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_driver_lib.sv
vendor/lowrisc_ip/dv/tools/dvsim/common_sim_cfg.hjson
vendor/lowrisc_ip/dv/tools/dvsim/sim.mk
vendor/lowrisc_ip/dv/tools/xcelium/cov_merge.tcl
vendor/lowrisc_ip/ip/prim/lint/prim_flop_2sync.waiver
vendor/lowrisc_ip/ip/prim/prim_lc_and_hardened.core
vendor/lowrisc_ip/ip/prim/prim_lc_or_hardened.core
vendor/lowrisc_ip/ip/prim/rtl/prim_lc_and_hardened.sv
vendor/lowrisc_ip/ip/prim/rtl/prim_lc_or_hardened.sv
vendor/lowrisc_ip/ip/prim/rtl/prim_sync_reqack.sv
vendor/lowrisc_ip/ip/prim/rtl/prim_sync_reqack_data.sv
vendor/lowrisc_ip/util/dvsim/Deploy.py
vendor/lowrisc_ip/util/dvsim/RdcCfg.py
vendor/patches/lowrisc_ip/dv_tools/0001-Change-xcelium-cov_merge.tcl-to-pass-databases-in-ru.patch

This may be a tricky one to review as I'm the only one familiar with the inner workings of the icache (I think?).
I should also add a coverplan to the icache DV documentation but wanted to get the rest of it out as a PR ASAP

Icache fcov

---

rtl/ibex_top.sv

This commit adds two assertions in `ibex_top` to ensure that the scramble key is correctly applied to the icache scrambled memory primitives.  Those assertions previously existed in the module that instantiated Ibex in OpenTitan, but the reference into the generate loops was problematic for some EDA tools; see lowRISC/opentitan#17155.

[rtl/dv] Add assertions for icache scramble keys

---

dv/uvm/core_ibex/scripts/collect_results.py
dv/uvm/core_ibex/scripts/ibex_sim.mk
dv/uvm/core_ibex/scripts/metadata.py
dv/uvm/core_ibex/scripts/report_lib/dvsim_json.py
dv/uvm/core_ibex/scripts/report_lib/html.py
dv/uvm/core_ibex/scripts/report_lib/junit_xml.py
dv/uvm/core_ibex/scripts/report_lib/regression_report.tpl.html
dv/uvm/core_ibex/scripts/report_lib/svg.py
dv/uvm/core_ibex/scripts/report_lib/text.py
dv/uvm/core_ibex/scripts/report_lib/util.py
dv/uvm/core_ibex/wrapper.mk
python-requirements.txt

New reports provide HTML, dvsim compatible json and an SVG summary dashboard.

[dv] Refactor reporting and add additional reports

---

examples/simple_system/README.md

This should avoid some of the confusion that caused issue #2101.

[doc] Describe counters more explicitly in simple_system README

---

doc/03_reference/instruction_decode_execute.rst

[doc] fix a typo.

---

rtl/ibex_core.sv

[rtl] fix a typo.

---

dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml

This adds a test item (commented out as the test isn't implemented yet) for #2233.

[dv] Plan test for DM accesses in debug mode
