- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_id_stage.sv
This PR fixes to remaining issues related to the recent introduction of enum types for previously hard-coded parameters:
1. Before assigning literals to enum types, Vivado expects an explicit type cast and otherwise throws an error. (#33)
2. There were instances of `csr_op` signals in `id_stage` which still were using the previous logic types leading to illegal signal assignments (#34).
The changes have been tested using Verilator and Vivado (synthesis and implementation ran through without issues).
> Fix missing enum casts

- rtl/ibex_alu.sv
- rtl/ibex_controller.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_multdiv_fast.sv
- rtl/ibex_multdiv_slow.sv
This PR contains a couple of fixes related to linting errors. First of all, the width of literals later cast to enums is specified. Second, before doing a part select, signed signals are converted to unsigned signals. Also, this PR clarifies that some MSBs in the ALU and the multiplier can safely be ignored (some linting tools also produce errors because of these MSBs being ignored).
> Code cleanup

- doc/requirements.txt
Using figures in admonitions did not work so far. A patch was created
and merge is pending. As long as it is not merged, use custom sphinx.
Fixes #24
> Temporarily switch to custom sphinx

- rtl/ibex_tracer.sv
The `nop` instruction ( `32'h00_00_00_13` ) cannot be distinguished from masked `addi` ( `17'b?, 3'b000, 5'b?, 7'h13` ) in `unique casex` statement. The other way around is not a problem, as `addi` cannot have both registers as 0x0. 
This can be also fixed by replacing `unique casex` with `priority casex`. However, in my opinion, it is not a good solution as it may hide future bugs like this.
> Fix non-unique case bug in tracer.

- rtl/ibex_compressed_decoder.sv
Hints encoded in these compressed instructions must decode into hints
in the corresponding base instructions. This resolves #51.
> Fix decoding of C.LI, C.LUI, C.SRLI, C.SRAI, C.SSLI

- doc/requirements.txt
Upstream has now released a new version which includes Stefan's patch to
correctly build the PDFs.
Fixes #41
> Doc: Switch back to upstream Sphinx

- rtl/ibex_core.sv
This updates the name of a signal which was renamed in the process of https://github.com/lowRISC/ibex/pull/61
> Fix RVFI signal name

- rtl/ibex_cs_registers.sv
- rtl/ibex_defines.sv
This PR solves two problems in the performance counters:
1. Fix increment of performance counters
2. Make sure performance counters are not accidentally optimized away during synthesis. Only those are optimized away, which are disabled.
It resolves #80.
The changes have been tested using Verilator and Vivado.
> Fix perf counters

- doc/instruction_fetch.rst
- doc/load_store_unit.rst
- rtl/ibex_if_stage.sv
- rtl/ibex_load_store_unit.sv
- rtl/ibex_prefetch_buffer.sv
This PR adds two commits to ensure the data and instruction address output by the core is always word aligned.
The core handles unaligned accesses by issuing two separate, aligned accesses. However, without these commits, the core still outputs unaligned addresses for the two accesses and relies on the memory to ignore the address LSBs.
Tested with Verilator and Vivado.
> Align data and instruction address output

- doc/integration.rst
- doc/performance_counters.rst
- rtl/ibex_core.sv
Performance counters are an optional feature. Disable them by default to
avoid users having them enabled unknowingly and paying the (rather
large) area price for it.
> Disable performance counters by default

- rtl/ibex_cs_registers.sv
- rtl/ibex_register_file_ff.sv
Verilator displays the following lint warnings:
```
%Warning-WIDTH: ../src/lowrisc_ibex_ibex_0.1/rtl/ibex_cs_registers.sv:100: Operator SHIFTL expects 32 bits on the LHS, but LHS's VARREF 'RV32E' generates 1 bits.
... Use "/* verilator lint_off WIDTH */" and lint_on around source to disable this message.
%Warning-WIDTH: ../src/lowrisc_ibex_ibex_0.1/rtl/ibex_cs_registers.sv:103: Operator SHIFTL expects 32 bits on the LHS, but LHS's VARREF 'RV32M' generates 1 bits.
%Warning-WIDTH: ../src/lowrisc_ibex_ibex_0.1/rtl/ibex_cs_registers.sv:108: Operator SHIFTL expects 32 bits on the LHS, but LHS's VARREF 'MXL' generates 2 bits.
%Warning-WIDTH: ../src/lowrisc_ibex_ibex_0.1/rtl/ibex_register_file_ff.sv:63: Operator EQ expects 32 bits on the LHS, but LHS's VARREF 'waddr_a_i' generates 5 bits.
``` …
> Avoid WIDTH lint warnings in Verilator

- doc/cs_registers.rst
- doc/exception_interrupts.rst
- doc/performance_counters.rst
- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_decoder.sv
- rtl/ibex_defines.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_load_store_unit.sv
This PR mainly modifies the trap handling infrastructure to comply with the RISC-V privileged spec, draft versions 1.11. To this end, additional CSRs were added.
All exceptions now jump to the base address of the trap-vector table. Interrupts are handled in vectored mode and jump to the base address + 4*irq_id. The exception cause is stored in `mcause` and `mtval` has been added to hold additional information (illegal instruction for illegal instruction exception, address of faulting transaction part for LSU errors).
To implement these changes the AGU mux for misaligned loads/stores has been reworked.
In addition, the `mscratch` CSR has been implemented.
This PR resolves: #97 and #70.
> Spec compliant trap handling

- rtl/ibex_core.sv
The original query was (rvfi_rd_we_id == 1'b0), so this fixes the incorrect transformation.
> Fix RVFI rd write enable

- rtl/ibex_core.sv
This got forgotten when renaming the signal inside ID stage in
commit  b22a6a10defc7bad31dda7d8a33c7145d1a79a3b.
This fixes #112 .
> Switch to new signal name in tracer instantiation

- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_decoder.sv
- rtl/ibex_defines.sv
- rtl/ibex_ex_block.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_multdiv_fast.sv
- rtl/ibex_multdiv_slow.sv
This PR contains a major cleanup of the ID stage and the decoder. Control logic (e.g. for stalls) that depends not on the decoder exclusively, is moved out of the decoder. Similarly, logic inside the ID stage that is strictly related to instruction decoding (immediate & register file address generation and checking) is moved into the decoder. 
As a result, the ID stage now instantiates the modules of the controller, decoder and registers, and contains the the main muxes, the write-back (WB) FSM to handle multicycle instructions and minimal glue logic, only.
This will ease future work on any of these parts. 
Finally, the WB FSM inside the ID stage is cleaned up to remove circular dependencies between FSM and decoder. This resolves #103 .
> Cleanup ID stage and decoder

- rtl/ibex_core.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_load_store_unit.sv
- rtl/ibex_register_file_ff.sv
- rtl/ibex_tracer.sv
I prepared this PR to get urgent stuff fixed before the bigger changes for the controller and interrupts/exceptions.
This PR contains two commits:
- The first one is a cleanup of the LSU that also fixes a critical error. Previously, misaligned loads/stores were broken as the byte enable generation and read data alignment for the second transaction part were not working. These operations rely on the updated input address having the same alignment as the original address, whereas the LSU provided the aligned output address to the AGU.
- The second one fixes recently introduced linting errors.
Tested using Verilator and Vivado.
> Fix LSU + lint errors

- rtl/ibex_decoder.sv
According to the spec, these two fields must be 0 for `ecall`, `ebreak`, `mret`, `dret` and `wfi` instructions.
This PR adds a commit to generate an illegal instruction exception if they are not zero.
> Check `rs1` & `rd` for non-CSR system instructions

- rtl/ibex_compressed_decoder.sv
- rtl/ibex_decoder.sv
This PR adds register address checks to the decoder for RV32E configurations. In such a configurations, registers x16-x31 are not available. If accessed, the core now generates an illegal instruction exception as discussed in #105 .
Without this PR, the core just ignores the MSB of register file addresses which is problematic and masks the actual problem.
> Check register address for RV32E

- doc/cs_registers.rst
misa is WARL, but hard-wired. mtvec is WARL rather than read-only (but is also hard wired). The patches in this PR adjust the documentation to reflect this.
> Improve documentation for misa and mtvec CSRs

- doc/cs_registers.rst
Fixes a doc typo introduced in #128. As penance for this mistake, I added another minor improvement - the CSR page now links to the performance counters page for documentation on those registers.
> Trivial doc cleanups

- rtl/ibex_decoder.sv
This PR solves problems reported by @jeanlouismaquet in #130.
> Decoder: fix drive conflict, set `jump_set_o` for JALR

- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_decoder.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_if_stage.sv
This PR contains a series commits to cleanup the main processor controller inside `ibex_controller.sv` and solve related issues.
The main changes are:
- Interrupt and debug requests no longer interrupt/abort multicycle instructions such as loads, stores, jumps, branches etc. Instead such instructions are first finished and if they cause an exception, the core jumps into the handler before serving the debug or interrupt requests. This fixes issues #108 and #121 .
- Exceptions are prioritized according to the spec inside the controller FSM.
- Obsolete signals between ID stage, IF stage and controller have been removed which simplifies the design.
- The interplay of IF stage and controller has been streamlined.
> Cleanup main processor controller

- rtl/ibex_core.sv
- rtl/ibex_id_stage.sv
This commit moves the generation of these signals into the ID stage to generate it with more accurate timing. More precisely, an instruction is now considered as retired once it has been completely executed and not once the next instruction is pushed into the IF-ID pipeline register.
Also, it no longer depends on whether the instruction was valid or illegal. For RVFI and the tracer, also illegal instructions must be considered.
> Generate `instr_ret/compressed` inside ID stage

- rtl/ibex_controller.sv
This PR lets the core also check `debug_req_i` and `debug_single_step_i` while entering debug mode to avoid entering debug mode without setting up the debug CSRs properly (which anyway depend on these signals), if these signals go low during the procedure.
This resolves #153 .
> Fix dpc CSR not updated

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/setting/riscv_core_setting.sv
- vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
dv to revision 2e5a40145a367ac3b04f78fee02c5011022719fd
* Merge pull request #36 from google/dev (taoliug)
* Add basic debug mode support (Tao Liu)
> Update google_riscv-dv to 2e5a401

- rtl/ibex_core.sv
`illegal_insn_id` and `id_out_valid` are only used if the RVFI is enabled. This PR removes linting errors happening when the RVFI is disabled.
> Remove linting errors for RVFI-related signals

- examples/sim/tb/ibex_tracer_tb.sv
- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_core_tracer.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_if_stage.sv
This PR changes how RVFI signals are generated (https://github.com/lowRISC/ibex/issues/151, fixes https://github.com/lowRISC/ibex/issues/147).
It also forwards the uncompressed instruction to the tracer (https://github.com/lowRISC/ibex/issues/154).
As those commits are all closely coupled I think it is easier to do it in one PR.
@taoliug could you please test this before it is merged?
> Tracer based on RVFI

- rtl/ibex_decoder.sv
This commit fixes two bugs in the decoder:
1. For illegal branch condition selections, the illegal instruction
condition must be signaled as long as the instruction is being executed
and not just during the first cycle, as the controller cannot interrupt
multicycle instructions.
2. Illegal instructions should also be signaled when `instr[28]` is set
for register-register ALU operations. Previously, these were not
signaled as the original design used `instr[28]` to encode custom bit-
manipulation instructions.
These bugs were discovered by @taoliug. This resolves issue #163.
> Decoder: fix signaling and detection of illegal instructions

- rtl/ibex_controller.sv
This commit changes the controller to save the PC of the next
instruction to the dpc CSR when entering debug mode upon a halt
request instead of the PC of the current instruction (only valid
for EBREAK instructions).
This bug was reported by @taoliug. This resolves #164.
> Controller: save next PC to dpc CSR upon a halt request

- ibex.core
The tracer defines are not used by ibex on its own.
> Remove unneeded tracer define

- rtl/ibex_id_stage.sv
This commit fixes the write back FSM to not store values returned from
memory to the register file when the LSU is reporting a load error.
This bug was reported by @ivanmgribeiro. This commit resolves #162.
> ID/EX stage: do not write to register file upon load errors

- rtl/ibex_decoder.sv
Without this commit, the PC is still set to a possible wrong jump target on illegal JALR instructions ultimately causing the wrong PC being saved to `mepc` during the illegal instruction exception.
This bug has been reported by @taoliug. This commit resolves #170.
> Decoder: avoid setting PC upon illegal JALR instructions

- rtl/ibex_decoder.sv
The custom reg-reg instruction was added in the original design but is
no longer needed. This commit removes it. Also, load instructions with
`instr[14:12] == 3'b110` are now decoded as illegal.
This resolves #25.
> Decoder: remove reg-reg load, make LWU illegal

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/run
- vendor/google_riscv-dv/src/riscv_illegal_instr.sv
- vendor/google_riscv-dv/src/riscv_instr_pkg.sv
dv to revision 4e0d063fea574cfae55c5bb627771b69d9899899
* Merge pull request #38 from google/dev (taoliug)
* Fix illegal instruction test issue Fix Xcelium compile failure #37
(Tao Liu)
> Update google_riscv-dv to 4e0d063

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
- vendor/google_riscv-dv/src/riscv_rand_instr.sv
- vendor/google_riscv-dv/test/riscv_instr_test_lib.sv
dv to revision 112dcc2e669f124dfe48c35a09477603c3ccb180
* Merge pull request #39 from google/dev (taoliug)
* CSR instruction update (Tao Liu)
> Update google_riscv-dv to 112dcc2

- doc/tracer.rst
- dv/uvm/ibex_dv.f
- dv/uvm/tb/core_ibex_tb_top.sv
- examples/fpga/artya7-100/top_artya7_100.core
- examples/sim/README.md
- examples/sim/tb/ibex_tracing_tb.sv
- examples/sim/top_tracing_sim.core
- ibex_core.core
- ibex_core_tracing.core
- ibex_tracer.core
- rtl/ibex_core_tracing.sv
- rtl/ibex_tracer.sv
Painful, but needed for symmetry and to reduce confusion: rename the cores in the fusesoc core files.
This PR requires RVFI to be defined globally if the ibex_core_tracing.sv is used to avoid potential design bugs caused by differing tool behavior. It's better to be explicit here.
If RVFI is not set and the ibex_core_tracing.sv file is used a compile error will be thrown as the file includes invalid syntax. I'm not yet sure that this is the right way to go, but it seems that there's no universally understood way to convince a Verilog parser to issue a compile-time fatal error.
> Rename cores for fusesoc, mainly tracer

- examples/fpga/artya7-100/rtl/top_artya7_100.sv
- examples/sim/tb/ibex_tracing_tb.sv
- rtl/ibex_core.sv
- rtl/ibex_core_tracing.sv
This PR also adapts the interrupt interface in the Arty example, the tracer and the tracer TB.
A follow-up PR will contain the required changes for the UVM infrastructure.
This PR is related to #187 .
> Adapt interrupt interface for Arty example, tracer and TB

- rtl/ibex_core.sv
- rtl/ibex_core_tracing.sv
This PR re-adds the signal `rvfi_intr` part of the RVFI after it got accidentally removed in PR #188.
This signal is now set during the first instruction after the PC has been set to enter a trap handler.
> RVFI: re-add accidentally removed `rvfi_intr` signal

- rtl/ibex_pkg.sv
This bug has beed reported by @taoliug. This resolves #195.
> Correct cause number for illegal instruction exception

- rtl/ibex_decoder.sv
This PR contains a single commit removing a couple of linting errors in the decoder.
> Avoid linting errors

- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_pkg.sv
This PR contains two cleanup commits affecting the CSRs:
1. Remove define for `mstatus` CSR by bit index parameters in `ibex_pkg.sv`.
2. Remove `csr_restore_dret_id_o` signal. This signal was used to restore the `mstatus` CSR when exiting debug mode. This is not needed as the `mstatus` CSR is not modified when entering debug mode.
> Cleanup CSRs

- ibex_core.core
- lint/verilator_waiver.vlt
Setup Verilator lint and waivers
This adds Verilator lint support to our fusesoc core file. A waiver file
is created to waive all well-understood lint warnings. The UNOPTFLAT
warnings are not well understood at the moment, they are waived for now
and further discussion is expected to happen in a GH issue (referenced
in the waiver).
Run with
```
fusesoc --cores-root . run --target=lint lowrisc:ibex:ibex_core
```
The waiver file support requires edalize >= 0.1.5.
> Setup Verilator lint and waivers

- dv/riscv_compliance/README.md
- dv/riscv_compliance/ibex_riscv_compliance.cc
- dv/riscv_compliance/ibex_riscv_compliance.core
- dv/riscv_compliance/rtl/bus.sv
- dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
- dv/riscv_compliance/rtl/prim_clock_gating.sv
- dv/riscv_compliance/rtl/ram_1p.sv
- dv/riscv_compliance/rtl/riscv_testutil.sv
- dv/verilator/simutil_verilator/cpp/verilated_toplevel.h
- dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.cc
- dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.h
- dv/verilator/simutil_verilator/simutil_verilator.core
This adds a Verilator simulation of Ibex for use in RISC-V Compliance
Testing. In addition to ibex itself, the simulation contains a RAM and
a memory-mapped helper module for the test software to interact with the
outside world. The test framework uses this to dump a "test signature",
which is written to a certain part of the memory, and to end the
simulation. (In the future, this could be extended to include printf()
like functionality.)
Fixes https://github.com/lowRISC/ibex/issues/99
Note that this requires changes to the compliance test suite itself, please see #99 for more discussion.
> Provide simulation to run RISC-V Compliance test

- rtl/ibex_id_stage.sv
This PR makes sure the signal `instr_multicycle_done_q` is only evaluated when the decoder currently has a multicycle instruction (load/store, mult/div, branch, jump). If this signal is evaluated
for single-cycle instructions, it can prevent the reg file write enable from being de-asserted in the case of stalls due to the IF stage.
@udinator: Could you please verify that this actually fixes the bug you reported in #216 before we merge it?
> Fix IF stalls preventing deassertion of regfile write enable

- rtl/ibex_cs_registers.sv
This PR adds a prefix to the members of the `Interrupts_t` struct to avoid linting errors in AMS mode (timer is a key word).
> CSRs: add `irq_` prefix to `Interrupts_t` members

- dv/uvm/Makefile
- dv/uvm/riscv_dv_extension/csr_description.yaml
- dv/uvm/riscv_dv_extension/ibex_log_to_trace_csv.py
- dv/uvm/riscv_dv_extension/testlist.yaml
- dv/uvm/sim.py
Integrated ibex simulation flow with `riscv-dv` privileged CSR test
- Added options for CSR test generation script to `Makefile`
- Added `csr_description.yaml`, containing YAML descriptions of all implemented CSRs, as per `docs/cs_registers.rst` for use in privileged CSR testing
- Modified license of `testlist.yaml` to match standard Ibex licenses
- Modified `sim.py` to deal with the optional `no_post_compare` license
- Updated  `ibex_log_to_trace_csv.py` to add functionality to parse UVM sim logs for the new report messages
> Update ibex simulation flow

- dv/uvm/Makefile
- dv/uvm/common/irq_agent/irq_master_driver.sv
- dv/uvm/env/core_ibex_env_cfg.sv
- dv/uvm/riscv_dv_extension/csr_description.yaml
- dv/uvm/tb/core_ibex_tb_top.sv
- dv/uvm/tests/core_ibex_base_test.sv
- dv/uvm/tests/core_ibex_csr_test.sv
- dv/uvm/tests/core_ibex_report_server.sv
- dv/uvm/tests/core_ibex_test_pkg.sv
- Added a new register file interface, to enable monitoring for any register state updates
- Added a new `core_ibex_csr_test`, to be run with the privileged CSR test generation in `riscv-dv`, that uses this regfile interface to monitor for writes to x3 at the end of test to determine success or failure
- Extended the `uvm_default_report_server` to create a custom reporting class that reports whether simulation has passed or failed (will report for all risc-v simulations, and is just a measure of whether the DV UVM simulation has completed without errors/failures, and as such is useful for self-checking tests)
- Modified interrupt driver to now assert interrupts for 2 cycles, which ensures that Ibex will actually respond to all asserted interrupts, as they are treated as level sensitive
> Update ibex testbench

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/.gitignore
- vendor/google_riscv-dv/README.md
- vendor/google_riscv-dv/run.py
- vendor/google_riscv-dv/scripts/gen_csr_test.py
- vendor/google_riscv-dv/scripts/lib.py
- vendor/google_riscv-dv/scripts/ovpsim_log_to_trace_csv.py
- vendor/google_riscv-dv/scripts/spike_log_to_trace_csv.py
- vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
- vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
- vendor/google_riscv-dv/src/riscv_load_store_instr_lib.sv
- vendor/google_riscv-dv/test/riscv_instr_base_test.sv
- vendor/google_riscv-dv/yaml/csr_template.yaml
- vendor/google_riscv-dv/yaml/simulator.yaml
- vendor/google_riscv-dv/yaml/testlist.yaml
dv to revision e905e9f134e0b7cf7da491218d1a30c75ce8649a
* add pass_val and fail_val into csr test flow for EOT correctness
checking (Udi)
* Support unaligned load/store (Tao Liu)
* refactored test generation logic (Udi)
* refactored test generation logic (Udi)
* Give error when mutually exclusive between -co, and -so argument
(dang hai)
* documentation, and small fixes (Udi)
* no_iss bug (Udi)
* no_iss/no_post_compare optional, CSR read_only is now only specified
at field level granularity (Udi)
* made no_iss optional (Udi)
* rm print (Udi)
* setup_logging call (Udi)
* undo overriding --verbose in run.py, comment cleanup in csr gen
script (Udi)
* missed verbose arguments (Udi)
* verbose arg (Udi)
* updated csr …
> Update google_riscv-dv to google/riscv-dv@e905e9f

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/run.py
- vendor/google_riscv-dv/scripts/gen_csr_test.py
- vendor/google_riscv-dv/src/riscv_instr_sequence.sv
- vendor/google_riscv-dv/src/riscv_load_store_instr_lib.sv
- vendor/google_riscv-dv/src/riscv_rand_instr.sv
dv to revision 63fa0ca922ecf10f3cd733d15a0a79a7937a591e
* Merge pull request #74 from google/dev (taoliug)
* Add gcc compile options, fix unaligned load/store (Tao Liu)
* Merge pull request #72 from google/dev (taoliug)
* Properly disable branch instruction in push/pop stack operations
(Tao Liu)
> Update google_riscv-dv to 63fa0ca

- dv/uvm/Makefile
- dv/uvm/riscv_dv_extension/testlist.yaml
- dv/uvm/sim.py
- dv/uvm/tests/core_ibex_base_test.sv
- Modified sim.py to correctly process any sim_opts and compare_opts passed specified in the testlist
- Removed shared utility functions from sim.py (duplicates of functions in lib.py)
- Changed location of vseq.stop() call in testbench to prevent debug or interrupt signal assertions after ecall has been detected
> Add basic debug test and modify sim flow

- lint/verilator_waiver.vlt
This PR contains a single commit to adapt some line numbers in the Verilator lint waiver file. These
got out of sync with the RTL recently.
> Adapt line numbers in Verilator lint waiver

- rtl/ibex_controller.sv
- rtl/ibex_decoder.sv
- rtl/ibex_id_stage.sv
This commit clarifies why CSR-related pipeline flushes are needed (e.g. when enabling interrupts), only introduces them when doing the critical modifications (write/set bits in `mstatus` and `mie` CSRs
for enabling interrupts, reads and clears are uncritical for these CSRs), and makes sure the controller is actually able to start handling interrupts while doing a CSR-related pipeline flush.
This resolves lowrisc/ibex#6.
> Rework CSR-related pipeline flushes

- README.md
- azure-pipelines.yml
This sets up Azure Pipelines to run the following two tasks:
- Run Verilator lint on the SystemVerilog code.
- Run the RISC-V compliance test suite for RV32IMC
> CI: Use Azure Pipelines to run lint and some DV

- rtl/ibex_core.sv
- rtl/ibex_decoder.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_load_store_unit.sv
This removes an unused which was hardwired to ```2'b0``` in the decoder and was passed through to the LSU.
This addresses https://github.com/lowRISC/ibex/issues/229
> Remove unused signal data_reg_offset

- examples/fpga/artya7-100/rtl/ram_1p.sv
This signal must also be set in case of write transactions as it is a request valid and not a read valid.
> `ram_1p.sv`: Fix `rvalid_o` generation

- src_files.yml
This file is needed when using the tracer.
> `src_files.yml`: Add `ibex_core_tracing.sv`

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/README.md
- vendor/google_riscv-dv/scripts/spike_log_to_trace_csv.py
- vendor/google_riscv-dv/setting/riscv_core_setting.sv
- vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
- vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
- vendor/google_riscv-dv/src/riscv_instr_pkg.sv
- vendor/google_riscv-dv/yaml/csr_template.yaml
- vendor/google_riscv-dv/yaml/iss.yaml
- vendor/google_riscv-dv/yaml/simulator.yaml
- vendor/google_riscv-dv/yaml/testlist.yaml
dv to revision 73274f227000f1316cb201a8503aad437e427948
* Merge pull request #88 from google/dev (taoliug)
* Fix spike log processing issue (Tao Liu)
* Merge pull request #87 from google/dev (udinator)
* Add vectored interrupt support (Tao Liu)
* Merge pull request #85 from udinator/debug (udinator)
* Add debug sub-programs, and extra options to generator (Udi)
* Merge pull request #84 from imphil/fix-apache-urls (taoliug)
* Fix license URLs in comments (Philipp Wagner)
> Update google_riscv-dv to 73274f2

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
dv to revision e81acc9ab4f692ff205a207c2dc3d9f2b0284d39
* Merge pull request #89 from google/dev (taoliug)
* Fix mtvec alignement (Tao Liu)
> Update google_riscv-dv to e81acc9

- azure-pipelines.yml
- dv/riscv_compliance/README.md
rv32imc doesn't include all i and m tests, we need to call the test
suite on these extensions separately.
> CI: Run the compliance tests for all ISA variants

- lint/verilator_waiver.vlt
PR #236 broke the Verilator lint since lines changed. Fix that.
> Lint: Update Verilator waiver file

- rtl/ibex_controller.sv
Executing a DRET instruction outside of debug mode now causes an illegal instruction exception as mandated by the Debug Spec v0.13.2 p.41.
This resolves lowRISC/ibex#270.
> Fix behavior of DRET executed outside debug mode

- lint/verilator_waiver.vlt
- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_id_stage.sv
- The RISC-V Debug Spec v.0.13.2 (p.41) mandates that the core
debug CSRs dcsr, dpc, dscratch0 and dscratch1 must not be
accessible if not in debug mode. Fixes #275
> CSR: Access checks on Debug CSRs

- doc/integration.rst
- dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
- dv/uvm/tb/core_ibex_tb_top.sv
- examples/fpga/artya7-100/rtl/top_artya7_100.sv
- examples/sim/tb/ibex_tracing_tb.sv
- lint/verilator_waiver.vlt
- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_core_tracing.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_tracer.sv
Uncertain if we actually want a HartIDWidth parameter or just hard-code it to 32 bit.
> Replace cluster_id/core_id with hart_id (Fixes #29)

- doc/load_store_unit.rst
- rtl/ibex_load_store_unit.sv
- External signals data_rvalid_i and data_err_i were factored
into the external data_req_o signal
- To improve timing, these signals are decoupled
- The second part of an unaligned transaction will now be issued
even if the first received an error response
- The state machine will service the abandoned requests
- pmp_err_q fixed to only update at specific times
> [RTL] - Remove timing loop in LSU

- doc/integration.rst
- dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
- examples/fpga/artya7-100/rtl/top_artya7_100.sv
- examples/sim/tb/ibex_tracing_tb.sv
- rtl/ibex_core.sv
- rtl/ibex_core_tracing.sv
Signals the core is totally idle (WFI with no outstanding memory
transactions).
> Add core_sleep_o to ibex interface (fixes #258)

- rtl/ibex_fetch_fifo.sv
- rtl/ibex_prefetch_buffer.sv
- See issue #265 (partially fixes)
- Remove path from instr_rvalid_i to instr_req_o
- Prefetch buffer unit can now issue up to two outstanding requests
- Structure moved from state machine to request queue
- Change fetch fifo to use an unaligned flag rather than updating
the address each time
> [RTL] Fix I-side timing loop

- rtl/ibex_cs_registers.sv
This field is read only and should be set to the right value straight away.
This fixes lowRISC/ibex#285.
> CSRs: reset `dcsr.XDEBUGVER` to `XDEBUGVER_STD` instead of 0

- lint/verilator_waiver.vlt
- rtl/ibex_core.sv
- rtl/ibex_core_tracing.sv
- rtl/ibex_tracer.sv
- rtl/ibex_tracer_pkg.sv
Added compressed instruction decoder in ibex:tracer. This allows tracer to correctly trace both compressed and uncompressed instructions. With this support the tracer no long depends on the non-standard `rvfi_insn_uncompressed` signal. See #197 for further details.
> Adding Compressed Instruction support in tracer

- rtl/ibex_controller.sv
This commit fixes the generation of the exception cause ID of fast interrupt. Without this commit, the core tries to handle fast interrupts using the handlers of other interrupts like external, software, and timer interrupts.
This commit resolves lowRISC/ibex#290 reported by @udinator.
> Controller: Fix exception cause ID of fast interrupts

- rtl/ibex_controller.sv
Without this commit, the `nmi_mode` register is continuously cleared and set again, and the core can never handle the NMI.
This resolves lowRISC/ibex#300 reported by @udinator.
> Controller: fix `nmi_mode` default assignment

- .clang-format
- dv/riscv_compliance/ibex_riscv_compliance.cc
- dv/verilator/simutil_verilator/cpp/verilated_toplevel.h
- dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.cc
- dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.h
We have more and more C/C++ code in this repository. Add a clang-format configuration following the standard lowRISC coding style to help developers format their code consistently.
> Add clang-format configuration for C/C++ files

- dv/riscv_compliance/ibex_riscv_compliance.cc
- dv/riscv_compliance/ibex_riscv_compliance.core
- dv/verilator/simutil_verilator/cpp/verilated_toplevel.cc
- dv/verilator/simutil_verilator/cpp/verilated_toplevel.h
- dv/verilator/simutil_verilator/simutil_verilator.core
Currently, we generate a toplevel class (I'll call it topname here), inheriting from the Verilator-generated toplevel class (V*), and from the VerilatedToplevel abstract class. This allows us to pass around pointers to VerilatedToplevel whenever we need any toplevel, e.g. to call `eval()` on.
```
topname
/          \
VerilatedTopevel      Vtopname
public eval()   public: clk_i, rst_ni, etc.
public eval(), etc.
```
We now want to access the members of Vtopname from a pointer to VerilatedToplevel. That's achievable by casting VerilatedToplevel* to topname*, and then simply accessing the inherited members:
```cpp
void dosomething(VerilatedToplevel* top) {
dynamic_cast<topname*>(top)->clk_i = 1;
// (or, using a convenience method in this PR)
top->dut()->clk_i = 1;
}
```
(Edited for new …
> Verilator simulation utility: Make it easier to use generated toplevel class

- .gitignore
Also removes the include/riscv_config.sv.bak line, which was added
in 346d14c5. We have no code that generates this file any more.
> Ignore common editor files in Git

- ibex_core.core
- rtl/ibex_core.sv
Extend verilator lint checks to RVFI-conditional code, and fix warnings that come up when doing so.
> Lint: Remove some lint warnings

- dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
Give higher priority to data accesses from the CPU to improve
performance. This is the recommended setup for Ibex.
> Compliance test suite: Prefer D over I accesses

- rtl/ibex_core_tracing.sv
The syntax of this statement is not correct without the `$fatal()` SV construct. This causes errors in some tools even if the error condition is not met.
> Tracing: Wrap fatal error message with `$fatal()`

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/scripts/spike_log_to_trace_csv.py
- vendor/google_riscv-dv/src/riscv_illegal_instr.sv
- vendor/google_riscv-dv/src/riscv_instr_cov_item.sv
- vendor/google_riscv-dv/src/riscv_instr_cover_group.sv
- vendor/google_riscv-dv/src/riscv_instr_pkg.sv
- vendor/google_riscv-dv/test/riscv_instr_cov_test.sv
dv to revision e3e1e308cfc3d718aeb94bb3463371979d9a31ae
* Disable full trace in the run script (google/riscv-dv#180) (taoliug)
* Fix spike logging issue (google/riscv-dv#179) (taoliug)
* Add functional coverage for HINT instructions (google/riscv-dv#177)
(taoliug)
* Add functional coverage for various hazard conditions (google/riscv-
dv#176) (taoliug)
> Update google_riscv-dv to google/riscv-dv@e3e1e30

- rtl/ibex_core.sv
Added missing parameter assignment for PMPEnable of ibex_cs_registers.
> [rtl/ibex_core] Added missing parameter assignment

- doc/instruction_fetch.rst
- lint/verilator_waiver.vlt
- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_fetch_fifo.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_prefetch_buffer.sv
- Fix incorrect address output to mepc on interrupt (fixes #320)
- Fix instruction address changing before grant (fixes #296)
- Remove excess address flops in fetch_fifo
- Remove restriction on outstanding requests
> [Prefetch buffer] - various bug fixes

- rtl/ibex_tracer.sv
In this file I missed updating the ETH/UniBo copyright notice to include
a reference to the CREDITS.md. Fixing that for consistency.
> Tracer: Update copyright notice to match other files

- rtl/ibex_tracer.sv
We document the default file name to be trace_core_00000000.log, but
actually used trace_core__00000000.log. Fix that.
> Tracer: Fix default file name

- rtl/ibex_cs_registers.sv
Vivado doesn't compile the design without this cast.
> Add missing enum cast

- dv/uvm/cover.cfg
- dv/uvm/riscv_dv_extension/ibex_log_to_trace_csv.py
1) Enable toggle coverage of only top level I/O pins
2) Tighten ibex log regex to exclude writes to `x0`
> [DV] Top level toggle coverage

- rtl/ibex_tracer.sv
This miscompilation is now reported and fixed, mention it in the code to
refer back to it when we can revert back to the old code (which will
take a couple months until we can require a newer Verilator version).
Fixes #372
> Tracer: Reference Verilator bug for miscompilation

- doc/examples.rst
The testbench does not exist anymore. Was removed with #360
> Remove reference to simulation

- dv/riscv_compliance/README.md
The RISC-V compliance test system requires an absolute path to the
executable or one which starts at `riscv-test-suite/*`.
I would be happy if someone could verify that a relative path starting in `$RISCV_COMPLIANCE_REPO_BASE` does not work.
> Update description for running RISC-V compliance

- dv/uvm/riscv_dv_extension/testlist.yaml
1) Enable unaligned memory ops in mem_error test
2) Increase test iterations for some debug tests
> [DV] Added unaligned memory error test

- rtl/ibex_load_store_unit.sv
- If an error is signalled in the first part of an unaligned
transaction, the second part is issued anyway (to avoid a
timing loop from data_err_i -> data_req_o)
- Previously, the error was signalled and an exception was taken
as soon as the first transaction completed. This commits makes
the core wait until both transactions have completed.
- This prevents strange behaviour caused by the lsu and controller
being out of sync (fixes #374).
> [RTL LSU] Change unaligned error behaviour

- azure-pipelines.yml
simplesat (required by fusesoc) was broken by an update to the attrs
library. Now simplesat 0.8.2 has been released which fixes the issue, we
can remove the explicit pinning of the old attrs version.
> [CI] Stop pinning an old attrs version

- rtl/ibex_cs_registers.sv
Current documentation lists `mstatus.tw` as a `RW` field, but this readability is not reflected in RTL, this PR allows `mstatus.tw` to be read.
> [RTL] Enable reading mstatus.tw

- dv/uvm/common/ibex_mem_intf_agent/ibex_mem_intf_monitor.sv
- dv/uvm/common/ibex_mem_intf_agent/ibex_mem_intf_slave_agent.sv
- dv/uvm/common/ibex_mem_intf_agent/ibex_mem_intf_slave_driver.sv
- dv/uvm/common/ibex_mem_intf_agent/ibex_mem_intf_slave_sequencer.sv
- dv/uvm/common/irq_agent/irq_master_driver.sv
- dv/uvm/common/irq_agent/irq_monitor.sv
- dv/uvm/common/utils/clk_if.sv
- dv/uvm/env/core_ibex_dut_probe_if.sv
- dv/uvm/env/core_ibex_env.sv
- dv/uvm/riscv_dv_extension/testlist.yaml
- dv/uvm/tb/core_ibex_tb_top.sv
- dv/uvm/tests/core_ibex_test_lib.sv
- Major changes to driver/monitor components throughout the testbench to allow for mid-test reset stimulus to be driven
- Modifications to tb_top to move all clock and initial reset stimulus to `initial begin...end` blocks in the `clk_if`.
> [DV] Add reset test

- rtl/ibex_cs_registers.sv
Debug register access sets illegal_csr if not in debug mode but CSR
write still went ahead. This modifies the CSR write to ensure that
anything that results in an illegal CSR instruction being signalled will
prevent a CSR write.
> [RTL] Prevent CSR write on any illegal CSR reason

- rtl/ibex_controller.sv
When we single step over an instruction that causes an exception DPC
should be set to point to the exception handler (where we would have
gone were we not single stepping).
As discussed on Zulip this looks to be the correct behaviour, see response to issue on riscv-debug-spec here https://github.com/riscv/riscv-debug-spec/issues/497
> [RTL] Fix single stepping on exceptions

- doc/verification.rst
Having just tried running the DV stuff for the first time thought this tweak to the getting started information would help (the RISC-DV document has lots of irrelevant information so I thought it was better to point to the relevant sections)
> [Doc] Added extra setup info for Verification

- rtl/ibex_tracer.sv
> Tracer: Decode an all-zero instruction as INVALID

- lint/verilator_waiver.vlt
- rtl/ibex_alu.sv
- rtl/ibex_pkg.sv
These operations (ALU_GT, ALU_GTU, ALU_LE, ALU_LEU) are remnants of of the original OpenRISC design. RISC-V does not have these instructions and instead implements the operations by reversing operands for ALU_LT, ALU_LTU, ALU_GE, ALU_GEU.
This resolves lowRISC/ibex#420 reported by @udinator.
> [rtl/alu] Remove unused comparison operations

- dv/uvm/Makefile
- dv/uvm/riscv_dv_extension/riscvOVPsim.ic
- dv/uvm/riscv_dv_extension/testlist.yaml
Additionally:
1) Add configuration file for OVPsim, and update Makefile to pass correct config file into iss_sim target
2) Additionally, changed default ISS to OVPsim, it has been fully configured for Ibex, and can handle `mie.mtie` being enabled without any weird side-effects.
> [DV] Increase number of illegal instructions generated

- dv/uvm/env/core_ibex_csr_if.sv
- dv/uvm/env/core_ibex_env_pkg.sv
- dv/uvm/riscv_dv_extension/testlist.yaml
- dv/uvm/tb/core_ibex_tb_top.sv
- dv/uvm/tests/core_ibex_base_test.sv
- dv/uvm/tests/core_ibex_test_lib.sv
Added two new tests to assert interrupts and debug mode requests while the core is handling a pipeline flush due to CSR write instructions dealing with xSTATUS and xIE.
This PR relies on the riscv-dv generator changes added in [this PR](https://github.com/google/riscv-dv/pull/273).
> [DV] Assert interrupt during write to MSTATUS and MIE

- lint/verilator_waiver.vlt
- rtl/ibex_alu.sv
- rtl/ibex_pkg.sv
These operations (ALU_SLET, ALU_SLETU) are remnants of of the original OpenRISC design. RISC-V just has set-less-than (ALU_SLT, ALU_SLTU).
This resolves lowRISC/ibex#432 reported by @udinator.
> [rtl] Remove unused set-less-or-equal-than ALU ops

- dv/cs_registers/tb/tb_cs_registers.sv
- dv/cs_registers/tb_cs_registers.core
- dv/riscv_compliance/ibex_riscv_compliance.core
- Speed up compile time by only optimizing hot code
- Fix some incorrect references in tb_cs_registers
- Add a comment for FST vs VCD tracing
> [verilator] Fix a few verilator DV issues

- dv/uvm/Makefile
- dv/uvm/riscv_dv_extension/ibex_log_to_trace_csv.py
- dv/uvm/sim.py
- Update parsing of ibex tracer log to extract all register information (rs1/rs2/rd) if available
- enable riscv_csr_test trace logs to get converted to CSV format for functional coverage
Note: depends on https://github.com/google/riscv-dv/pull/291
> [funct_cov] Update Ibex log parsing

- azure-pipelines.yml
[riscv-compliance] changes the tests for rv32i.
Update the expected output.
[riscv-compliance]: https://github.com/riscv/riscv-compliance/commit/df18fa8d95e78f2c54d7a5d59a8b94b3f19967ef
> Update expected failure for riscv-compliance

- rtl/ibex_cs_registers.sv
Without this PR, writes to `dpc` with the LSB set are completely ignored. This PR changes the implementation to ignore the LSB only. This is the same behavior as seen required for `mepc`. This resolves lowRISC/ibex#444.
> [rtl] Ignore LSB only for writes to `dpc`

- lint/verilator_waiver.vlt
- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_id_stage.sv
This commit reworks the generation of the `core_busy` signal used to control the main clock gate of the core. Without this commit, the controller generates a separate `first_fetch` signal only asserted in the FIRST_FETCH state that directly controls `core_busy` and thus the main clock gate. This is problematic as it introduces a feedback to from the controller state into the clock.
This commit removes the problematic signal and changes the generation of `ctrl_busy` in the FIRST_FETCH state of the controller. This signal is now used to control the main clock gate in all states (previously all except FIRST_FETCH) but it gets registered, thus it does not introduce the feedback into the clock.
This resolves lowRISC/ibex#211.
> [rtl] Rework `core_busy` signals, remove feedback to clk

- shared/rtl/sim/simulator_ctrl.sv
The tracer needs time to log the final instruction.
Introduce a counter to delay calling the simulation finish.
@imphil is that what you had in mind?
> Delay simulator finish

- dv/cs_registers/reg_driver/csr_listing.def
- dv/cs_registers/reg_driver/register_transaction.cc
- dv/cs_registers/reg_driver/register_transaction.h
- dv/cs_registers/tb/tb_cs_registers.sv
All CSR addresses supported by the TB are now delared as an X
macro list. This list is then used to autogenerate the enum
type, string print helper and an array of all addresses.
The array of addresses can now be used by the randomize generator
to turn an arbitrary integer index into an address. This removes
the restriction on only generating contiguous address ranges noted
in #443.
Add missing signal csr_restore_dtret_i
> CS registers tb enhancements

- dv/uvm/riscv_dv_extension/testlist.yaml
- dv/uvm/tests/core_ibex_test_lib.sv
- Add mstatus.tw test for U-mode - core jumps into illegal instruction handler correctly after seeing `wfi`
- refactored mcause checking in several places in the test class hierarchy
> [DV] umode_tw test

- doc/cs_registers.rst
- doc/debug.rst
- doc/exception_interrupts.rst
- doc/integration.rst
- doc/verification.rst
- rtl/ibex_cs_registers.sv
This PR consists of three small commits which implement the following changes:
- Exceptions in debug mode shall not modify any CSRs. This resolves #168 and is related to #365.
- Document debug CSRs. This resolves #307.
- Update documentation of `mhartid` CSR. Previously, the doc was still describing the cluster and core ID bit fields.
> Fix behavior of exceptions in debug mode, document debug CSRs

- Makefile
This PR is optional. Using the Makefile was helpful for me lately and maybe it could be useful for others, so please give feedback.
One reason to not add this: It might confuse people not familiar with the project structure. Instead of following the documentation, using a target of the Makfile without a set-up will fail.
But the intention of this file is not to create an automatic build flow, just a way to run some tasks for the experienced user.
Instead of copying the commands from the documentation or using the
shell history to find the commands use a Makefile as a convenience to
run some common tasks.
A shell's completion system can make use of the targets and provide tab
completion.
> Proposal: Add Makefile for common tasks

- azure-pipelines.yml
- dv/cs_registers/tb/tb_cs_registers.cc
- dv/cs_registers/tb_cs_registers.core
- dv/riscv_compliance/ibex_riscv_compliance.cc
- dv/riscv_compliance/ibex_riscv_compliance.core
- dv/verilator/simutil_verilator/cpp/verilated_toplevel.cc
- dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.cc
- dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.h
- examples/simple_system/ibex_simple_system.cc
- examples/simple_system/ibex_simple_system.core
- shared/rtl/ram_1p.sv
Allow loading ELF files within Verilator. Support for vmem is still available, but changes to the interface of the simulator are made.
The original arguments are preserved so adoption (riscv-compliance) is easier.
The additional arguments can be removed at a later point.
> ELF support for Verilator simulation

- dv/cs_registers/tb/tb_cs_registers.cc
- dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.cc
- shared/rtl/ram_1p.sv
All functions in simutil_verilator return booleans to indicate
success/failure, where 1 == true, and 0 == false.
simutil_verilator_set_mem() returns an int due to DPI interface
restrictions. Before, 0 meant success, and 1 meant error.
To keep things nice and consistent, turn things around and align with
the bool meaning.
> Reverse return code of simutil_verilator_set_mem()

- syn/cmos_cells.lib
- syn/prim_clock_gating.v
- syn/syn.ys
- syn/syn_yosys.sh
This PR includes the following:
- add script syn_yosys.sh, which runs sv2v and yosys for ibex_core
- add example std. cell lib cmos_cells.lib (copied from yosys repo)
- add dummy prim_clock_gating.v module
- add initial yosys synthesis script syn.ys
> [syn] Add initial Yosys synthesis script with example lib

- dv/cs_registers/tb/tb_cs_registers.cc
- dv/riscv_compliance/ibex_riscv_compliance.cc
- dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.cc
- dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.h
- examples/simple_system/ibex_simple_system.cc
The VerilatorSimCtrl class was always intended to be used only once in
an application, since it sets up a global signal handler and needs to be
accessible from DPI modules. This accessibility was achieved through a
global variable `simctrl`.
With this commit the VerilatorSimCtrl is switched to a singleton class.
The instance is accessible through `VerilatorSimCtrl::GetInstance()`.
The downside of that approach is that we loose the constructor
arguments, and need to deal with a class which potentially hasn't top or
the clock and reset signals set.
> Make VerilatorSimCtrl class a singleton

- examples/simple_system/ibex_simple_system.cc
The fstream header is needed for `ofstream()` in ibex_simple_system.
> [examples] Add fstream header

- dv/uvm/env/core_ibex_env_cfg.sv
This commit fixes $value$plusargs sytem function error described in #497.
> Pluseargs parsing fix

- dv/verilator/simutil_verilator/README.md
- dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.cc
Add a requirement for the software loaded by the simulator for zero-ing
the BSS section.
Fixes lowRISC/ibex#496
> [verilator] Clarify ELF BSS handling

- doc/cs_registers.rst
- doc/debug.rst
- doc/integration.rst
- dv/cs_registers/tb/tb_cs_registers.sv
- lint/verilator_waiver.vlt
- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_core_tracing.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_pkg.sv
- Add the minimum amount of trigger system to support GDB hbreak
- Only a single trigger is implemented
- Only instruction address matching
- Only break into debug mode (no native debug)
- Fixes #382
> [dbg] Add minimal hardware breakpoint support

- dv/uvm/Makefile
- dv/uvm/env/core_ibex_env_cfg.sv
- dv/uvm/riscv_dv_extension/testlist.yaml
- dv/uvm/tests/core_ibex_base_test.sv
- dv/uvm/tests/core_ibex_seq_lib.sv
- dv/uvm/tests/core_ibex_test_lib.sv
- dv/uvm/tests/core_ibex_vseq.sv
- update error messaging for handshake functions to make more clear
- combine `wait (dut_vif.mret === 1'b1)` and `wait_dret(...)` into one task `wait_ret(...)` and update testbench accordingly
- add privilege mode checking to testbench in tests that involve trapping between privilege modes
- update irq/debug sequences to report if they have been started or not to prevent hanging when killing sequences at EOT
- simplify enabling irq/debug sequences by turning on either `enable_irq_seq` or `enable_debug_seq` from the testlist and letting the UVM environment do the rest, instead of previous approach of enabling the particular sequence from the testbench
> [DV] Fix xRET wait checks

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
- vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
- vendor/google_riscv-dv/src/riscv_instr_stream.sv
dv to revision 74b8cb65838f575d6e59e1c80a145d305fbca381
* fix ebreak generation in debug ROM (Udi Jonnalagadda)
* enable nested traps (Udi Jonnalagadda)
> Update google_riscv-dv to google/riscv-dv@74b8cb6

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/src/riscv_load_store_instr_lib.sv
dv to revision 9ecee87bbc41650ca0f8846de9a277bec2783e18
* fix mmu_stress_test generation failure (Udi Jonnalagadda)
> Update google_riscv-dv to google/riscv-dv@9ecee87

- dv/uvm/common/ibex_mem_intf_agent/ibex_mem_intf_slave_seq_lib.sv
- dv/uvm/tests/core_ibex_vseq.sv
Currently, when the testbench returns a read response to the core, for either a load instruction or instruction fetch response, the testbench will perform a whole word read of the requested address, after word-alignment.
However, for byte or halfword loads, this is not ideal, since it is possible that the extraneous bytes read by the testbench outside of the requested byte/halfword are not initialized in the testbench system memory.
This PR fixes this issue by having the dmem_intf_sequence only read bytes from the system memory that correspond to high bits in the `byte_enable` signal that the core outputs on LSU transactions to ensure that only valid byte addresses are accessed.
> [DV] Fix TB read responses

- dv/uvm/ibex_dv.f
- ibex_core.core
- lint/verilator_waiver.vlt
- rtl/ibex_compressed_decoder.sv
- rtl/ibex_controller.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_decoder.sv
- rtl/ibex_fetch_fifo.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_load_store_unit.sv
- rtl/ibex_multdiv_fast.sv
- rtl/ibex_multdiv_slow.sv
- shared/prim_assert.core
- shared/rtl/prim_assert.sv
This PR:
- Replaces all X assignments in the RTL with defined values. 
- Imports a new file from OpenTitan containing macros for SystemVerilog assertions (SVAs).
- Rewrites existing SVAs using these macros.
- Adds SVAs to catch invalid signal values in simulation.
> [rtl] Replace X assignments

- dv/verilator/simutil_verilator/cpp/sim_ctrl_extension.h
This base class needs a default destructor for potential future extensions.
> SimCtrlExtension: Add a default destructor

- dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.cc
In case one of the arguments is '-h' the parsing of the arguments is
aborted and only `PrintHelp()` of *verilator_sim_ctrl.cc* is executed.
Do not abort at this point in order to forward the arguments to the
registered extensions. This allows to execute the respective
`PrintHelp()` function and print the help message. For example
`VerilatorMemUtil` needs to parse the arguments in order to print the
help message.
The execution of the simulation is still terminated as `exit_app` is set
and then evaluated after parsing of the registered extensions.
> [DV] Continue argument parsing

- rtl/ibex_compressed_decoder.sv
- rtl/ibex_if_stage.sv
This PR ensures that the assertions in the compressed decoder do not fire if the compressed decoder sees invalid data from the prefetch buffer.
> [rtl] Trigger C decoder assertions only if instr valid

- doc/performance_counters.rst
- examples/simple_system/rtl/ibex_simple_system.sv
- rtl/ibex_cs_registers.sv
Refactors performance counters so only flops that are required from the
given parameters are explicitly elaborated without relying on
optimization to remove unused flops.
Fixes #473
The previous RTL produced a circuit where the value of all mhpmcounter flops would be maintained, unused bits would be reset to 0 and written 0 but before reset they could be some other value. Whilst it was possible for synthesis tools to decide this meant they could be ignored and seen as constant 0 values it requires setting optimization to 'high' or similar in some tools (see discussion on #473). My yosys flow couldn't perform the necessary optimization at all so synthesized many unused flops. This alters things so it's explicit what gets elaborated and doesn't rather than relying on apparently complex …
> [rtl] Don't elaborate unused mhpmcounter flops

- shared/rtl/prim_assert.sv
This updates the assertion macros in `prim_assert` to coincide with the ones used in OpenTitan. 
@udinator, could you do me a favor and double check whether this introduces any issues with your DV environment?
> [rtl] Update prim assert with OpenTitan version

- doc/register_file.rst
- ibex_core.core
- lint/verilator_waiver.vlt
- rtl/ibex_register_file_fpga.sv
This commit adds a register file designed to be synthesized into FPGA
synchronous-write / asynchronous-read design elements.
For the artya7-100 example, the register file is implemented by 12
RAM32M primitives, conserving approximately 600 Logic LUTs and 1000
flip-flops at the expense of 48 LUTRAMs.
> [rtl] Add FPGA Register File

- rtl/ibex_register_file_fpga.sv
* Line 46: `baddr_b_i` > `raddr_b_i`.
> [rtl] Fix Typo in FPGA Register File

- syn/ibex_core_lr_synth_conf.tcl
- syn/tcl/lr_synth_flow_var_setup.tcl
- syn/tcl/yosys_run_synth.tcl
Adds an 'uprate' clock period which is subtracted off the desired period
and given to ABC as the target clock period. This gives better overal
timing results with minimal area impact.
> [syn] Feed ABC faster clock for better results

- dv/uvm/env/core_ibex_env_cfg.sv
- dv/uvm/riscv_dv_extension/testlist.yaml
- dv/uvm/tests/core_ibex_seq_lib.sv
- dv/uvm/tests/core_ibex_test_lib.sv
- dv/uvm/tests/core_ibex_vseq.sv
Tests scenarios where Ibex is executing an interrupt handler and receives a second set of interrupts in the middle of the first handler.
As per the discussion in #557, I have eliminated nested NMI interrupt test scenarios from this testcase.
This PR relies on https://github.com/google/riscv-dv/pull/444 to be functionally correct, so will only merge this PR after vendoring the latest riscv-dv copy.
> [DV] Test nested interrupts

- dv/uvm/ibex_dv.f
- examples/simple_system/rtl/ibex_simple_system.sv
- lint/verilator_waiver.vlt
- rtl/ibex_compressed_decoder.sv
- rtl/ibex_controller.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_decoder.sv
- rtl/ibex_fetch_fifo.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_load_store_unit.sv
- rtl/ibex_multdiv_fast.sv
- rtl/ibex_multdiv_slow.sv
- shared/prim_assert.core
- shared/rtl/prim_assert.sv
- shared/rtl/timer.sv
This is a spin-off from https://github.com/lowRISC/ibex/pull/566 with only the fixes that affect RTL. All issues were caught when running Riviera 2019.10 on our code base.
The fixes are generally and not related to Riviera per se, keeping them in this PR to reduce the dependency chain. Support for Riviera running DV will come in a follow-up.
> RTL fixes discovered by running Riviera

- dv/uvm/ibex_dv.f
- dv/uvm/tests/core_ibex_test_lib.sv
- dv/uvm/yaml/rtl_simulation.yaml
The first commit fixes a VCS compile-time issue introduced by #570 where the `prim_assert.sv` file wasn't recognized by the compiler.
The second commit addressed #569 and fixes the missing enum casts.
@danielmlynek - can you pull these changes into your Riviera environment and check the compilation again?
> Riviera compile warnings

- examples/simple_system/rtl/ibex_simple_system.sv
- shared/rtl/bus.sv
- shared/rtl/ram_2p.sv
- shared/sim_shared.core
This commit adds a separate memory ports for instruction and data
fetches to the Simple System example.
* Add Dual-Port RAM with 1 cycle read/write delay, 32 bit words.
* Introduce parametric signal width definitions for bus implementation
to work with a single host / device.
* Modify Simple System top module to instantiate the new dual-port RAM.
> [examples] Add Dual-Port Memory to Simple System

- dv/uvm/riscv_dv_extension/riscv_core_setting.sv
- dv/uvm/tests/core_ibex_seq_lib.sv
- dv/uvm/yaml/rtl_simulation.yaml
Initial support for Riviera 2019.10 and some issue fixed in ibex it self.
There is also riscv-dv changed to work with Riviera added.
> Support for Riviera 2019 10

- doc/exception_interrupts.rst
- rtl/ibex_controller.sv
This is related to lowRISC/ibex#557.
> Ignore all interrupts in NMI mode, clarify documentation

- Makefile
For some reason the part number between the Arty A7-35T and the Arty
A7-100T differs by 1 letter (TICSG vs TCSG). This patch fixes the part
number for the Arty A7-100T to remove the "i".
Signed-off-by: Stephano Cetola <scetola@linuxfoundation.org>
> Fix FPGA part number for Arty A7-100T

- dv/verilator/memutil/cpp/verilator_memutil.cc
In `VerilatorMemUtil::WriteElfToMem`, the verilator memory is written
with the ELF segment data, 4 bytes at a time . If the segment size isn't
a multiple of 4 (e.g. when using the RISC-V C extension) the last word
wouldn't be written. This patch rounds the size up to a multiple of 4,
solving that issue.
> [verilator] Fix ELF loading

- src_files.yml
This PR fixes `incdirs` of `src_files.yml`.
#570 added `` `include "prim_assert.sv"``, but no incdir added.
> Fix incdirs of src_files.yml

- dv/riscv_compliance/README.md
Include all tests in the description which can be executed for Ibex and
riscv-compliance.
> Extend riscv-compliance description

- dv/cs_registers/tb/tb_cs_registers.sv
- lint/verilator_waiver.vlt
- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_pkg.sv
This PR modifies the `mip` CSR to not depend on the `mie` CSR. While the values of both these CSRs are combined to decide whether an interrupt shall be handled, the RISC-V spec does not state that the content of of `mip` should depend on `mie`. This commit better aligns Ibex with other open-source RISC-V cores.
This resolves lowRISC/ibex#567 reported by @pfmooney.
> [rtl] Decouple `mip` and `mie` CSRs

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/README.md
- vendor/google_riscv-dv/docs/source/configuration.rst
- vendor/google_riscv-dv/docs/source/coverage_model.rst
- vendor/google_riscv-dv/docs/source/getting_started.rst
- vendor/google_riscv-dv/src/dv_defines.svh
- vendor/google_riscv-dv/src/riscv_amo_instr_lib.sv
- vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
- vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
- vendor/google_riscv-dv/src/riscv_instr_pkg.sv
- vendor/google_riscv-dv/src/riscv_pmp_cfg.sv
- vendor/google_riscv-dv/target/ml/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv32i/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv32imc/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv64gc/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv64gcv/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv64imc/riscv_core_setting.sv
dv to revision e63c5427b0bf543aebb9c62bba8217065b029a76
* Add pmp configuration object (Udi Jonnalagadda)
* add path for the prebuilt document (google/riscv-dv#469) (taoliug)
* Update document for directed assembly/C test (google/riscv-dv#467)
(taoliug)
* Fix broken document link (google/riscv-dv#466) (taoliug)
* Add a runtime option to fix stack pointer (google/riscv-dv#465)
(taoliug)
* Fix LR/SC instruction issue for RV32A (google/riscv-dv#464)
(taoliug)
> Update google_riscv-dv to google/riscv-dv@e63c542

- dv/uvm/ibex_dv.f
- dv/uvm/riscv_dv_extension/riscv_core_setting.sv
- dv/uvm/riscv_dv_extension/testlist.yaml
- dv/uvm/tb/core_ibex_tb_top.sv
-enable the ibex PMP module to be included in simulations
-add basic PMP test
-set some initial default value to the rtl PMP configuration parameters
-simulations with this setup pass successfully with cosimulating with OVPsim
> [dv] enable PMP

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/src/riscv_pmp_cfg.sv
dv to revision 6e2bc2e01fb20799c9eff29a26852eb1917b977a
* fix a missed syntax error in pmp_cfg (Udi Jonnalagadda)
> Update google_riscv-dv to google/riscv-dv@6e2bc2e

- rtl/ibex_compressed_decoder.sv
- rtl/ibex_controller.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_decoder.sv
- rtl/ibex_fetch_fifo.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_load_store_unit.sv
- rtl/ibex_multdiv_fast.sv
- shared/rtl/prim_assert.sv
This mirrors the change made in OpenTitan
(https://github.com/lowRISC/opentitan/pull/1485)
> [rtl] Introduce default clk/reset to prim_assert

- dv/uvm/Makefile
- dv/uvm/tb/core_ibex_tb_top.sv
- PMP options num_regions and granularity are needed to parameterize the RTL at compile time, and are also needed by the riscv-dv generator and ISS simulator, so these options are now controlled through the Makefile and their defaults are set accordingly
- Cleaned up Makefile slightly to have consistent use of plaintext variables for ease of use
- The ISS options code is also implemented in the generator, in PR https://github.com/google/riscv-dv/pull/474
> [dv] add command line PMP option configurability

- doc/instruction_decode_execute.rst
- doc/pipeline_details.rst
- rtl/ibex_multdiv_slow.sv
- The slow multiplier is modified to terminate iterations early instead
of always going the full 32 iterations.
- Multiplications now terminate early after clog2(`op_b`) iterations.
- The slow multiplier can be further optimized by swapping the smaller
operand into `op_b` when in the `MD_IDLE` state.
> :zap: Reduce latency of slow multiplier

- doc/instruction_decode_execute.rst
- doc/integration.rst
- doc/pipeline_details.rst
- lint/verilator_waiver.vlt
- rtl/ibex_ex_block.sv
- rtl/ibex_multdiv_fast.sv
This commit adds a single cycle multiplier implementation designed to be
synthesized into DSP block primitives.
For the artya7-100 example the multiplier is implemented by 4 DSP48E1
slices. Savings in terms of logic LUTs is minimal, however faster
multiplication capability will result in higher IPC.
> [rtl] Add Single Cycle Multiplier for FPGA

- lint/verilator_waiver.vlt
- rtl/ibex_multdiv_fast.sv
Use of case inside in always_ff block does not meet style guide
recomendations. Refactored to remove this.
Signed-off-by: Greg Chadwick <gac@lowrisc.org>
> [rtl] Alter multdiv to better match style guide

- rtl/ibex_cs_registers.sv
Following RISC-V privileged architecture version 1.11,
the "E" bit of misa should return the complement of the "I" bit.
Set the "I" bit only if RV32E is not used.
Closes lowRISC/ibex#612.
> [rtl] Change misa for RV32E

- azure-pipelines.yml
Recently changes in the RISC-V compliance repo have caused our tests to
fail. That indicent highlighted the issue that we use the latest master
version of the compliance suite without pinning the version.
This PR fixes that by pinning to a specific version where our tests
still succeeded.
Upstream PR to fix actual failure: https://github.com/riscv/riscv-compliance/pull/92
Works around #608
> CI: Pin riscv-compliance repo to specific commit

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/README.md
- vendor/google_riscv-dv/run.py
- vendor/google_riscv-dv/src/isa/riscv_compressed_instr.sv
- vendor/google_riscv-dv/src/isa/riscv_instr.sv
- vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
- vendor/google_riscv-dv/src/riscv_debug_rom_gen.sv
- vendor/google_riscv-dv/src/riscv_illegal_instr.sv
- vendor/google_riscv-dv/src/riscv_instr_cov_item.sv
- vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
- vendor/google_riscv-dv/src/riscv_instr_pkg.sv
- vendor/google_riscv-dv/src/riscv_page_table_entry.sv
- vendor/google_riscv-dv/src/riscv_page_table_list.sv
- vendor/google_riscv-dv/src/riscv_pmp_cfg.sv
- vendor/google_riscv-dv/target/ml/riscvOVPsim.ic
- vendor/google_riscv-dv/target/rv32i/riscvOVPsim.ic
- vendor/google_riscv-dv/target/rv32imc/riscvOVPsim.ic
- vendor/google_riscv-dv/target/rv32imc/testlist.yaml
- vendor/google_riscv-dv/target/rv64gc/riscvOVPsim.ic
- vendor/google_riscv-dv/target/rv64gcv/riscvOVPsim.ic
- vendor/google_riscv-dv/target/rv64imc/riscvOVPsim.ic
- vendor/google_riscv-dv/verilog_style/build-verible.sh
- vendor/google_riscv-dv/verilog_style/exclude_filelist.f
- vendor/google_riscv-dv/verilog_style/run.sh
- vendor/google_riscv-dv/yaml/iss.yaml
- vendor/google_riscv-dv/yaml/simulator.yaml
dv to revision 6bd323385d454858ea5e50dedd42a563b37931fe
* VCS compile option fix (Udi Jonnalagadda)
* Improve pmp config object - enable cmdline args (Udi Jonnalagadda)
* Fix ovpsim setting (google/riscv-dv#478) (taoliug)
* IUS - enable rand structs in simulation (google/riscv-dv#477)
(udinator)
* fix macro definition compile issue (Udi Jonnalagadda)
* add ISS command line options (google/riscv-dv#474) (udinator)
* Add style check (Weicai Yang)
> Update google_riscv-dv to google/riscv-dv@6bd3233

- examples/simple_system/README.md
Missing "can" (which sounds a bit like a pirate!) and full stop.
> Tiny docs fix in examples/simple_system

- dv/uvm/core_ibex/vcs.tcl
If VERDI_HOME is not set, calling fsdbDumpfile makes VCS hang with an
error message. This patch checks whether we think FSDB dumping is
actually going to work and, if not, dumps with the default VCD+
format (also called VPD) instead.
> Dump to VPD in dv/uvm if Verdi is not available

- doc/verification.rst
The important change is that we now tell the user to configure spike
with --enable-misaligned. This is needed because Ibex handles
misaligned loads and stores rather than jumping to a trap handler (the
default behaviour in spike).
This patch also points a user at the manual from the riscv-dv
repository, rather than duplicating the list of steps here.
> Improve docs for getting started in verification.rst

- examples/sw/simple_system/common/link.ld
This is part of work to run binaries created for the simple system
under Spike. Spike's default behaviour (after a weird 'rom' trampoline
at 0x1000) is to obey the entry point given in the ELF file. So let's
set it correctly.
> Set the ELF entry point in simple system linker script

- dv/uvm/core_ibex/Makefile
As per some discussions in #620 , this PR removes the `0x` prefixing for the signature_addr in various steps of the Makefile flow.
> [dv] remove usage of 0x from sim flow

- dv/uvm/core_ibex/sim.py
The process_regression_list function from riscv-dv is really chatty.
When we're just compiling the testbench, we don't actually need to
figure out what tests we're running, since we'll never run them
anyway. So don't call it.
> Make sim.py less chatty when just compiling the testbench

- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
Adds explicitly void return type for some dcsr checking functions and resructures some core_ibex_tb_top dut connections to address #622.
These changes do not have any effect on VCS simulations.
> [dv] fix qrun compile warnings

- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
I was seeing various failures due to these timeouts. Upon looking at the waves seems things were working fine it just needed more time to get to the store instructions that output the CSR info wait_for_csr_write is waiting for. So I added a large timeout increase here (it'll still die pretty quickly if we actually need the timeout).
Surprised this has only just become an issue, perhaps we're seeing a greater range of delays on the iside interface so the instruction sequence leading up to the SW that outputs what we're waiting for takes longer?
> [dv] Increase timeouts to fix failures

- dv/uvm/core_ibex/riscv_dv_extension/ibex_log_to_trace_csv.py
This is a sequence of patches spurred on by the work I'm doing trying to make it easy to run simple_system binaries with Spike and then compare trace logs with Ibex.
The first patch fixes a simple bug (it wasn't possible to run the Python script except from directories exactly two components below the ibex root).
The second patch makes the command line interface a bit nicer (relevant to me, because that's how I'm running it!). Now, running without any arguments converts data from stdin to stdout (rather than exploding with a mysterious error).
The final two patches tidy things up in general, getting the code PEP8 compliant and simplifying log checking. Honestly, this is mostly just indentation changes, but there were also some dead variables to delete and I made imports explicit (which …
> Improvements in ibex_log_to_trace_csv.py

- dv/riscv_compliance/ibex_riscv_compliance.core
- dv/riscv_compliance/lint/verilator_waiver.vlt
- dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
- dv/riscv_compliance/rtl/riscv_testutil.sv
- examples/simple_system/ibex_simple_system.core
- examples/simple_system/lint/verilator_waiver.vlt
- examples/simple_system/rtl/ibex_simple_system.sv
Fix a few last verilator warnings. The first two patches are just waivers. The third seems to be an actual bug.
> Verilator warnings

- examples/simple_system/spike-simple-system.sh
The main point of this is that it's somewhere we can store what it
calls "ss_opts": the options that we must pass to Spike to tell it the
memory layout of the simple_system environment.
While we're at it, I've tried to make this reasonably pleasant to use.
So you can do
spike-simple-system.sh <elf-file>
just to run the thing. To pass stuff to Spike without the
bash script getting in the way, use '--':
spike-simple-system.sh -- my option -h --here <elf-file>
> Add a wrapper script to run a simple_system binary under Spike

- dv/uvm/core_ibex/Makefile
The --end_signature_addr argument doesn't go to Verilog; instead it
makes it through run.py (vendored-in, so hard to change) and
eventually gets inserted into some assembly code.
Before this patch,
make ITERATIONS=1 TEST=riscv_csr_test ISS=spike SEED=123
failed with:
out/seed-123/instr_gen/asm_tests/riscv_csr_test_0.S: Assembler messages:
out/seed-123/instr_gen/asm_tests/riscv_csr_test_0.S:526: Error: illegal operands `li x2,8ffffffc'
out/seed-123/instr_gen/asm_tests/riscv_csr_test_0.S:533: Error: illegal operands `li x2,8ffffffc'
> Re-instate an 0x in dv/uvm/core_ibex/Makefile

- rtl/ibex_id_stage.sv
This seems to cause lint errors with ncsim (see bug #650).
> Remove stray semicolon

- doc/performance_counters.rst
- dv/uvm/core_ibex/ibex_dv.f
- examples/fpga/artya7/top_artya7.core
- ibex_core.core
- lint/verilator_waiver.vlt
- rtl/ibex_core.f
- rtl/ibex_counters.sv
- rtl/ibex_cs_registers.sv
This commit modifies the cs_registers module to allow inference of DSP
slices to absorb counter logic. A preprocessor variable is introduced
to include the required synthesis pragma. DSP inferrence is supported
for Xilinx FPGA devices featuring DSP48E1 slices or similar and for
counter widths up to 48 bit.
The resulting relative logic utilizations with respect to the non-DSP
32 bit counter implementation are 84% and 90% respectively for 32 and
48 bit counters. For 32 bit counters only, the corresponding
flip-flops can be incorporated into the DSP's output pipeline
register, resulting in a reduction of the number of flip-flops to 50%.
In order to infer DSP slices for performance counters, define the
preprocessor variable XILINX_DSP_COUNTERS.
> Modifiy Performance Counter for DSP Inference

- dv/uvm/core_ibex/Makefile
This reverts commit c32a088f0cd0bdf903d38eb9772e55fd670e08cb.
The bug fixed by this was also fixed in riscv-dv leading to two 0x being
inserted into generated .S files.
Fixes #661
I felt it was better to fix this in Ibex rather than attempting to revert things in the riscv-dv repository as there will be other downstream users effected by changes there.
> Revert "Re-instate an 0x in dv/uvm/core_ibex/Makefile"

- syn/ibex_core_abc.nangate.sdc
- syn/tcl/lr_synth_flow_var_setup.tcl
- syn/tcl/yosys_run_synth.tcl
Correcting some small issues that cause newer versions of OpenSTA to
fail (previously it issued an error and continued).
- ABC/OpenSTA disagree how set_driving_cell command works so introduce
seperate ABC SDC file
- Run clean before generating STA netlist, otherwise yosys generates
some assignements to unused wires that OpenSTA's verilog parser dislikes
> [syn] Synthesis fixes

- dv/uvm/core_ibex/riscv_dv_extension/ml_testlist.yaml
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
Currently only the riscv_rand_test target fully works with RTL simulation, the other two test targets both fail RTL simulation due to some testbench error, which I think was introduced by a previous commit, will debug this issue.
> [ml] add condensed test targets for ML (and constraints)

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/test/riscv_instr_test_lib.sv
dv to revision 3f584adef07b7f04edda8a6ba1dfc01a14df5d98
* update ebreak generation for ML test (Udi Jonnalagadda)
> Update google_riscv-dv to google/riscv-dv@3f584ad

- dv/uvm/core_ibex/riscv_dv_extension/riscvOVPsim.ic
This PR updates the riscvOVPsim ISS configuration file to disable the semihosting mode, otherwise EBREAK instructions will cause end of test to be reached.
> update riscvOVPsim.ic for semihosting mode

- dv/uvm/core_ibex/Makefile
This adds a dependency on $(TESTLIST) (which is that file) for each
target that depends on $(TEST_OPTS), a set of command line options
that includes --testlist=$(TESTLIST).
In practice, we could actually just add the dependency to the
$(metadata)/instr_gen.gen.stamp target, since all the other affected
targets transitively depend on that, but this seems a little confusing
so I've made the dependency explicit.
> Add missing Makefile dependencies on testlist.yaml

- dv/uvm/core_ibex/Makefile
> Fix typo in uvm/core_ibex/Makefile

- doc/verification.rst
The files moved; also add an explicit `cd` to the command listing to
help people only skimming the docs.
> [doc] Fix paths in verification documentation

- syn/README.md
- syn/syn_setup.example.sh
syn/ filling up with result directories is a little annoying, this sets
up the default so everything ends up generated under syn/syn_out/. Flow
users can easily change this to meet their personal requirements.
> [syn] Place result directories in sub-directory

- doc/verification.rst
Without this, Sphinx spits out a warning message and swallows the
block.
> Add missing space after code-block directive

- rtl/ibex_counters.sv
Verible doesn't do real pre-processing currently, and fails to parse
code if define sections span across headers of blocks, as we did.
Use another syntax instead for the one case where we did that to work
around this limitation. The code isn't less readable as result, making
this an acceptable trade-off.
Works around https://github.com/google/verible/issues/228
> Use a syntax compatible with Verible

- shared/rtl/prim_assert.sv
Assert macros in prim_assert.sv report the asserted property as part of
the error message if the assertion fails. Doing that requires us to
stringify the property. If the property is multi-line in the source
code, this produces a multi-line string. According to the
SystemVerilog standard, a multi-line string requires a backslash (`\`)
at the end of a line. Adding this backslash through a macro is not
possible (at least to my knowledge), giving us no way to produce a
standards-compliant implementation of the `ASSERT` macros that report
the property as string.
This commit therefore removes the property from the error message if an
assertion fails. It makes these messages less useful, but the
information can still be recovered in a less convenient way through the
name of the assertion, and …
> Remove property from assert message

- doc/icache.rst
- rtl/ibex_icache.sv
This also adds a couple of comments splitting up the ports in
ibex_icache.sv that I found helpful when working out what everything
did.
> Notes on the ICache specification

- dv/uvm/core_ibex/sim.py
- dv/uvm/core_ibex/vcs.tcl
- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
This fixes a bug mentioned in issue #674, where dumped wave files were
ending up in dv/uvm/core_ibex, rather than a test-specific output
directory.
It turns out that this is because of my change in commit 08fc2a4,
which runs the simulator in the top core_ibex directory, rather than
changing directories each time. We have to do this to make the
parallel LSF flow work (which presumably has never actually been run,
otherwise we'd have noticed it was broken).
There are two ways I can think of getting this to work. Probably the
cleanest approach is to generate a script for each test, which looks
something like "cd test_dir; setup_stuff; run_simulator". This would
work (and is how I've seen it done in the past), but doesn't really
fit in with the string interpolation/YAML stuff we've got here. …
> Explicitly pass <out> directory to VCS's UCLI TCL

- dv/uvm/core_ibex/Makefile
When we run sim.py, we get commands to run the simulator from the YAML
file named by the --simulator_yaml argument, which defaults to
yaml/rtl_simulation.yaml.
This patch makes the argument explicit in the Makefile and adds a
dependency on that file for commands that read it.
> Add missing dependencies in uvm/core_ibex/Makefile

- azure-pipelines.yml
Azure pipelines has stopped triggering, the issue is being fixed but
this works around it for now.
> [CI] Add explicit trigger for branches/PRs

- rtl/ibex_icache.sv
The design currently relies on fill_done remaining set in the cycle
after the fill buffer completes to ensure the fill_older_q entry gets
cleared (when a fill buffer completes in the same cycle that one is
allocated). This fix makes the behaviour a bit more consistent and easy
to reason about.
> [rtl/icache] Make age matrix more consistent

- dv/uvm/core_ibex/Makefile
- dv/uvm/core_ibex/sim.py
- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
Add a step to the simulation flow for merged coverage generation.
Additionally changed the naming of coverage databases created by VCS to `test_<test_name>_<iterations>`  to make unique each database name and avoid overwriting, since seeds are generated in the top level Makefile.
> [dv] coverage generation

- azure-pipelines.yml
- ibex_core.core
- ibex_core_tracing.core
- python-requirements.txt
This extends the core file to be able to call Verible for lint.
This requires an updated version of edalize with
https://github.com/olofk/edalize/issues/95 fixed. For the time being, we
use the same 'ot' branches of those tools as we do in OpenTitan. Once
Verible becomes officially supported we need to ensure that released
versions of fusesoc and edalize exist, and that this requirement is
properly documented.
> Add Verible lint and format to fusesoc and CI

- dv/uvm/core_ibex/Makefile
Fix the extraneous forward slash in the makefile coverage generation step to allow OUT to be full paths, instead of constraining them to relative paths.
> [cov] fix extra backslash in makefile path

- doc/icache.rst
- rtl/ibex_icache.sv
Instruction requests triggering PMP errors have their external request
suppressed. The beat counting logic therefore needs to know that these
requests will never receive any rvalid data responses.
This fix stops the external request counter from incrementing, and marks
all external requests complete as soon as any error is received.
The data in the cache line beyond the error is not required since the
core cannot access it without consuming the error first.
> [rtl/icache] Fix PMP error logic

- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_fetch_fifo.sv
- rtl/ibex_icache.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_prefetch_buffer.sv
mtval should record which half of the instruction caused the error
rather than just recording the PC.
An extra signal is added in the IF stage to indicate when an error is
caused by the second half of an unaligned instruction. This signal is
then used to increment the PC by 2 for mtval capture on an error.
Fixes #709
> [rtl] Fix mtval for unaligned instr errors

- dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.cc
The option to limit the verilator simulation's maximum number of cycles was
implemented in terms of the `time_` variable, which counts half cycles. This
patch makes the limit respect the requested number of full cycles.
The patch divides `time_` by 2, instead of multiplying `term_after_cycles_`
by 2, as that better conveys the intended semantics, and slightly increases
the range of the limit. Related computations were modified for consistency.
> [verilator] Fix --term-after-cycles

- rtl/ibex_icache.sv
- Speculative requests observing a PMP error shouldn't increment the
external request counter
- Remove redundant logic on fill_rvd_exp
> [rtl/icache] Fix a couple of icache bugs

- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
Tighten up the interrupt raise/drop timings in irq_in_debug_mode_test to fix test failures.
> [dv] fix irq timing in irq_in_debug_mode_test

- rtl/ibex_id_stage.sv
- Branches don't need to stall with the branch target ALU
> [rtl] Remove stall cycle with BT ALU

- rtl/ibex_icache.sv
- valid_o could be asserted for one cycle then dropped when receiving
rvalid data for a request which has branched into  the middle of a
line.
- This fix keeps valid_o asserted by using the offset version of
fill_rvd_cnt_q (fill_rvd_beat) to compare against fill_out_cnt_q
(which is also offset by the branch).
> [rtl/icache] Fix an inconsistency in data output

- rtl/ibex_core.sv
- rtl/ibex_decoder.sv
- rtl/ibex_ex_block.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_pkg.sv
- Create separate operand muxes for the branch/jump target ALU
- Complete jump instructions in one cycle when BT ALU configured
> [rtl] Extend BT ALU to be used for all jumps

- rtl/ibex_controller.sv
- Before this fix, the branch signal was qualified by the illegal
instruction signal and the illegal csr signal.
- This patch removes both of these since the decoder already masks
branches with illegal isntruction, and a branch cannot be a CSR op.
- This improves the worst path in the design significantly without the
branch target ALU.
> [rtl] Branch signal timing fix

- dv/uvm/core_ibex/sim.py
Currently, if post_compare step fails, the entire makefile will error out, and coverage will not be generated.
Since coverage generation technically does not rely on the result of the post_compare stage, I now have each stage of the sim flow return RET_SUCCESS, to indicate that the step itself was able to run to completion; incorrect comparison results etc... will be logged to the terminal upon any failures and will now not prevent coverage from being generated.
> [dv] remove return value from the compare() step

- doc/pmp.rst
The `+2` part should have been part of the exponent, as indicated by the
RISC-V spec.
> Correct PMP granularity equation

- dv/uvm/core_ibex/Makefile
This permanently sets the `mtvec.base` field to be 256-byte aligned as per the Ibex CSR specification.
Addresses #730 from the Ibex DV side of things.
> [dv] update mtvec alignment in Makefile

- ibex_core.core
- ibex_pkg.core
The ibex_pkg.sv file is effectively a "header" with useful defines;
we need them in ibex_tracer_pkg.sv, and in other places around Ibex.
Currently, the dependency between ibex_tracer_pkg.sv and ibex_pkg.sv
wasn't covered in a FuseSoC core file, leading to unstable behavior.
This patch adds this dependency by
- factoring out the ibex_pkg.sv file into a separate core file,
ibex_pkg.core, and
- adding a dependency on the new ibex_pkg core to the ibex_tracer core.
> Factor out ibex_pkg.sv into a separate core file

- doc/icache.rst
When a PMP error comes in, the cache doesn't quite behave as if the
request was granted (if it did: it would wait forever for a response).
Hopefully this version is a bit clearer.
Also, this makes explicit that the upper bits of a 16-bit instruction
fetch can be bogus.
> Clarify a couple of points in icache documentation

- doc/instruction_decode_execute.rst
- doc/integration.rst
- lint/verilator_waiver.vlt
- rtl/ibex_alu.sv
- rtl/ibex_core.sv
- rtl/ibex_decoder.sv
- rtl/ibex_ex_block.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_pkg.sv
- rtl/ibex_tracer.sv
- rtl/ibex_tracer_pkg.sv
* Bit counting instructions clz, ctz and pcnt can be implemented to
share much of the architecture:
clz: Count Leading Zeros. Counts the number of 0 bits at the
MSB end of the argument.
ctz: Count Trailing Zeros. Counts the number of 0 bits at the
LSB end of the argument.
pcnt: Counts the number of set bits of the argument.
I propose the following approach:
- 32 one bit adders, counting the set bits of a signal
bitcnt_bits
- For pcnt the argument is fed directly into bitcnt_bits.
- For ctz: generate a signal with the number of set
bits == number of trailing zeros:
`bitcnt_bits = bitcnt_data-1 & ~bitcnt_data;`
here we can share the ALU adder for computing
`bitcnt_bits`.
* Instructions sll[i], srl[i],slo[i], sro[i], rol, ror[i], rev, rev8
and orc.b are summarized as shifting instructions …
> [bitmanip] Add ZBB Instruction Group

- rtl/ibex_pmp.sv
- Region matches should be prioritized from 0 - N as stated in the RISCV
Privileged Spec v1.11
> [rtl/pmp] Fix PMP error prioritization

- doc/icache.rst
Add a few sentences to describe the behaviour/meaning of the err_plus2_o
signal, and how it is used by the core.
> [doc/icache] Document the err_plus2_o signal

- rtl/ibex_core_tracing.sv
- Make parameter declaration order and default values in
ibex_core_tracing.sv match the documentation
> [rtl] Unify top-level parameter declaration

- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_agent_pkg.sv
- dv/uvm/core_ibex/common/irq_agent/irq_agent_pkg.sv
- dv/uvm/core_ibex/env/core_ibex_env_pkg.sv
- dv/uvm/core_ibex/ibex_dv.f
This PR moves all SV interface includes from the relevant *_pkg.sv file into ibex_dv.f, as a follow up to #711.
In order to get the Icache testbench to compile with dvsim in #711, the ibex_mem_intf.sv file had to be removed from its `include` inside the `ibex_mem_intf_agent_pkg`, and thus had to be manually added in `ibex_dv.f` to get Ibex simulation (which don't use dvsim yet) to successfully pass.
> [dv] move all SV interface includes into ibex_dv.f

- dv/uvm/data/common_sim_cfg.hjson
- dv/uvm/data/vcs/vcs_fsdb.tcl
The previous code correctly dumped to "waves.fsdb" if you had Verdi
installed. Unfortunately, it dumped to the same file name if you
didn't, which was rather confusing.
This patch passes a "DUMP_BASE" environment variable, rather than
"DUMP_FILE", which doesn't include the extension. Then it appends the
correct extension at runtime in the TCL, when we tell VCS what sort of
dumping to do.
The code now also checks for all environment variables before reading
them, allowing defaults if they don't exist. The defaults might not be
what you want, but a syntax error at this point causes VCS to sit
waiting for terminal input (with no stdin!), which is kind of annoying.
I've also removed the copy-pasted Verdi documentation. Apart from
anything else, this is probably copyright, so we shouldn't have …
> Fix destination for dumped waves in dv/uvm

- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
In the `riscv_debug_single_step_test` currently, we wait for 2000 clocks after each round of single stepping has been completed, which was previously fine since this meant that debug requests would start being sent out immediately at the very end of the `<init>` code section (which is the very beginning of the `<main>` code section).
This no longer applies however, since due to a restructuring of the generated program to enable PMP, there is now a jump instruction at the very end of the `<init>` section.  As the single stepping test cannot handle single stepping over branch/jump instructions as of right now, we must ensure to wait until at least this instruction has retired to start sending debug requests.
Resultantly, the `clk_vif.wait_clks(2000)` function call has now been moved to the …
> [dv] fix timing issue in single_step test

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
Adds the necessary DSim options to the simulation command to allow RTL simulations to fully pass the end-to-end flow of Ibex DV.
> [dv] fix DSim simulation command options

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
Without `UVM defined assertion failures don't result in regression
failure as they do not produce UVM reports.
> [dv] Define `UVM for VCS sim

- dv/uvm/core_ibex/riscv_dv_extension/ibex_log_to_trace_csv.py
- dv/uvm/core_ibex/sim.py
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
Before I added the set_max_quit_count call I had a failure (xprop related that caused several assertions to fire each cycle) that caused a ~2GB log file and a failure to dump waves (the simulation timed out which seemed to mess up the wave dump).
I set the default to 10 rather than 1 as it can be useful to let the simulation run a little past the first error if only to get another cycle or two in the waves.
> Dv error changes

- dv/uvm/core_ibex/Makefile
- dv/uvm/core_ibex/sim.py
Minor fixes to fix running commands on LSF:
1) Adding the LSF_CMD makefile option to the compile and rtl_sim steps to actually pass in the 'bsub' command
2) Fixing a syntax error in one of the `sim.py` functions that ran whenever lsf is enabled
> [dv] Fix running on LSF

- dv/uvm/icache/data/ibex_icache_testplan.hjson
This doesn't list all that many entries, possibly because the icache
doesn't really have many modes of operation (enabled/disabled;
invalidating).
> Initial icache testplan

- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
The timeout period in `riscv_debug_ebreakmu_test`when waiting for the status handshake from the core signaling that the exception handler has been entered is slightly too short for some seeds, causing some arbitrary failures - this PR doubles that timeout limit to loosen timing requirements.
> [dv] fix timing issue in ebreakmu_test

- doc/cs_registers.rst
- doc/integration.rst
- dv/cs_registers/tb/tb_cs_registers.sv
- ibex_core.core
- ibex_core_tracing.core
- lint/verilator_waiver.vlt
- rtl/ibex_core.sv
- rtl/ibex_core_tracing.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_decoder.sv
- rtl/ibex_id_stage.sv
- A new parameter and a run-time control bit (SecureIbex and
secure_mode) enable different behaviour for running security critical
code sections.
- In the new mode, all branches act as if taken, with not-taken
branches executing as a branch to the next instruction.
- This should give similar execution time/power characteristics
regardless of the branch condition.
- Note that with the BranchTargetALU, branches stall an extra cycle in
secure mode to avoid factoring the branch-taken decision into the
branch target address mux.
> [rtl] Add fixed time execution of branches

- ci/ibex-rtl-ci-steps.yml
- dv/riscv_compliance/ibex_riscv_compliance.core
- ibex_core_tracing.core
- lint/verilator_waiver.vlt
This PR includes some testing bits and pieces so shouldn't be merged yet, will resubmit a version without them once I'm happy everything is working
Multi-config CI wasn't actually trying multiple configurations. This
fixes that issue and uses a less fragile method of producing fusesoc
options. They are generated once and stored in a variable so we cannot
accidentally break one or more steps by using an incorrect
ibex_config.py command in one step whilst using a correct
ibex_config.py in the display step (which is also intended to check the
ibex_config.py command is correct).
> [ci] Fix multi-config CI

- dv/cs_registers/tb_cs_registers.core
- dv/riscv_compliance/ibex_riscv_compliance.core
- examples/simple_system/ibex_simple_system.core
- ibex_configs.yaml
- ibex_core.core
- ibex_core_tracing.core
Fusesoc has an unfortunate bug[1] where a boolean parameter which has
default true can't be disabled. For now, just make all our boolean
parameters back into integers again. In the future, when that's fixed,
maybe we should switch things back.
[1] https://github.com/olofk/fusesoc/issues/392
> Switch from 'bool' to 'int' parameters in fusesoc core files

- dv/uvm/icache/dv/Makefile
- dv/uvm/icache/dv/env/ibex_icache_env.sv
- dv/uvm/icache/dv/env/ibex_icache_virtual_sequencer.sv
- dv/uvm/icache/dv/env/seq_lib/ibex_icache_base_vseq.sv
- dv/uvm/icache/dv/env/seq_lib/ibex_icache_sanity_vseq.sv
- dv/uvm/icache/dv/ibex_icache_agent/ibex_icache_agent.core
- dv/uvm/icache/dv/ibex_icache_agent/ibex_icache_agent_pkg.sv
- dv/uvm/icache/dv/ibex_icache_agent/ibex_icache_driver.sv
- dv/uvm/icache/dv/ibex_icache_agent/ibex_icache_if.sv
- dv/uvm/icache/dv/ibex_icache_agent/ibex_icache_item.sv
- dv/uvm/icache/dv/ibex_icache_agent/seq_lib/ibex_icache_sanity_seq.sv
- dv/uvm/icache/dv/ibex_icache_agent/seq_lib/ibex_icache_seq_list.sv
- dv/uvm/icache/dv/ibex_icache_sim_cfg.hjson
- dv/uvm/icache/dv/tb/tb.sv
This PR has the bones of the ICache "core" UVM agent (see DV plan at #754). It doesn't currently do any monitoring, but it can drive signals to the cache.
> ICache core agent

- tool_requirements.py
- util/check_tool_requirements.py
We need this specific edalize version because recent verilators have
got pickier about string parameter passing, breaking the
"MultiplierImplementation" parameter.
As well as teaching check_tool_requirements.py to get the edalize
version from pip3, this patch also does a bit of tidying up, coping
better if tool_requirements.py is missing or malformed.
> Teach check_tool_requirements to check for edalize versions

- doc/instruction_decode_execute.rst
- lint/verilator_waiver.vlt
- rtl/ibex_alu.sv
- rtl/ibex_core.sv
- rtl/ibex_core_tracing.sv
- rtl/ibex_decoder.sv
- rtl/ibex_ex_block.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_multdiv_fast.sv
- rtl/ibex_pkg.sv
- rtl/ibex_tracer.sv
- rtl/ibex_tracer_pkg.sv
This commits implements the Bit Manipulateion Extension ZBT instruction
group: cmix, cmov, fsr[i] and fsl. Those are instructions depend on
three ALU operands. Completeion of these instructions takes 2 clock
cycles.
Architectural additions:
* Multicycle Stage Register in ID stage.
multicycle_op_stage_reg
* Decoder generates alu_multicycle signal, to stall pipeline
* For all ternary instructions:
1. cycle: connect alu operands a and b to rs1 and rs2
respectively
2. cycle: connect operands a and be to rs3 and rs2
respectively
Instruction Details:
* cmov:
1. store operand a (rs1) in stage reg.
2. return stage reg output (rs2)  or rs3.
if rs2 != 0 the output (rs1) is already known in the
first cycle. -> variable latency implementation is
possible.
* cmix:
1. store rs1 & rs2 in stage_reg
2. …
> [bitmanip] Add ZBT Instruction Group

- dv/uvm/icache/dv/Makefile
- dv/uvm/icache/dv/env/ibex_icache_env.sv
- dv/uvm/icache/dv/env/ibex_icache_scoreboard.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_driver.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_if.sv
As discussed in issue #778.
The other two patches in the queue are embarrassing: it seems my "edit a long patch queue and push something near the bottom" flow missed a couple of typos which were fixed further down the list. I've checked, and you can actually run the code after this.
> Add clocking blocks to icache core agent interface

- rtl/ibex_decoder.sv
- rtl/ibex_tracer_pkg.sv
This commit fixes a flaw in the decoder, which results in wrongly
generating an illegal instruction upon an orc_b instruction.
* Fix decoding of orc_b in illegal_insn generation.
* Correct bit-slicing for bitmanip immediate instructions, according
to specification.
> [bitmanip] Bugfix: Erroneous Illegal Instructions for RV32B instructions and Decoder Bit-Slicing

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
Riviera supports riscv-dv please upadate its version to at least:
https://github.com/google/riscv-dv/commit/2e8e73bfdffc376568c71673448a4b1afdaa9bb4
and merge changes proposed in this pull request.
> riviera support for riscv-dv testbench

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/MANIFEST.in
- vendor/google_riscv-dv/README.md
- vendor/google_riscv-dv/docs/source/getting_started.rst
- vendor/google_riscv-dv/riviera_sim.tcl
- vendor/google_riscv-dv/scripts/lib.py
- vendor/google_riscv-dv/src/isa/riscv_b_instr.sv
- vendor/google_riscv-dv/src/isa/riscv_instr.sv
- vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
- vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
- vendor/google_riscv-dv/src/riscv_instr_pkg.sv
- vendor/google_riscv-dv/src/riscv_pmp_cfg.sv
- vendor/google_riscv-dv/target/ml/riscv_core_setting.sv
- vendor/google_riscv-dv/target/multi_harts/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv32i/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv32imc/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv32imcb/riscvOVPsim.ic
- vendor/google_riscv-dv/target/rv32imcb/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv32imcb/testlist.yaml
- vendor/google_riscv-dv/target/rv64gc/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv64gcv/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv64imc/riscv_core_setting.sv
- vendor/google_riscv-dv/yaml/simulator.yaml
Should help to address #776.
dv to revision 42264b7782a10848935e995063c212893820e561
* fix pmp generation in bare program mode (Udi Jonnalagadda)
* Use literal instead array concatenation (Daniel Mlynek)
* fix access rights (Daniel Mlynek)
* fix in WA fo Aldec Riviera rand cannot be defined in packed struct
(Daniel Mlynek)
* Fix ius compile error (Weicai Yang)
* fix pmp randomization to adhere to max offset (Udi Jonnalagadda)
* Add options to enable bitmanip by group (google/riscv-dv#532)
(weicaiyang)
* [pmp] Relative addressing scheme to configure pmpaddr (google/riscv-
dv#534) (udinator)
* redunant variable ALDEC_PATH removed (danielmlynek)
* riviera 2020.04 beta initial support (danielmlynek)
* Removed  system …
> Update google_riscv-dv to google/riscv-dv@42264b7

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
Update the basic PMP test to (hopefully) solve the hanging issue by adding the new set of plusargs dictated by the new riscv_pmp_cfg generator class and adds a <cmp_opts> argument to the vcs compile command to enable compile time command substitution from the Makefile/command-line.
The <cmp_opts> argument is to enable passing in PMP-related parameters to Ibex compilation (the number of regions and granularity) as the RTL treats these as top level parameters and cannot be modified at runtime.
The basic PMP yaml test entry has some updates as well:
1) +num_of_sub_program=2 has been deleted, which causes it to be set to the generator's default value of 5
2) +pmp_randomize=0 is explicitly specified here just to provide some clarification, as I have not gotten around to creating documentation …
> [dv] fix PMP compile option, update basic pmp test

- dv/verilator/memutil/cpp/verilator_memutil.cc
- dv/verilator/memutil/cpp/verilator_memutil.h
- shared/rtl/prim_generic_ram_1p.sv
Pack > 32bit memory loads into wider RAM instances. Fixes #790
> [memutils] Add support for > 32b memories

- azure-pipelines.yml
Reduce CI times by using a packaged version of Verilator. The packaging
is done by me on Open Build Service, which provides Verilator packages
for various distributions. The packages are versioned to help choose the
exact version in CI.
This is experimental for now, let's see if that's a suitable path
forward in the longer term.
> CI: Use packaged version of Verilator

- dv/uvm/core_ibex/Makefile
This PR is a minor change that simply updates source and destination directory arguments for riscv-dv functional coverage to the correct locations (in `out/seed-###` instead of just in `out/`).
> [dv] update directory paths for riscv-dv coverage

- rtl/ibex_ex_block.sv
- rtl/ibex_multdiv_slow.sv
This commit adds support for the shared immediate value register in the
id_stage for the slow implementation of the multdiv module.
Register accum_window_q is now stored in the intermediate value
register.
> Use Shared Intermediate Value Register with Multdiv Slow

- rtl/ibex_cs_registers.sv
This change prevents latches from being inferred by Vivado for unused counters for variable mhpmcounter_incr
> Reorder statements to prevent latch inference

- doc/debug.rst
- doc/verification.rst
Ibex only provides the necessary interfaces and core-internal functionality
for run-control debug. To get a fully working,
"debuggable" toplevel design, more components are needed. Describe where to
get them from, and include OpenTitan as an exemplary integration.
> [doc] Add note about debug system integration

- rtl/ibex_core.sv
- src_files.yml
This PR includes two commits with very minor fixes:
- Including `prim_assert.sv` at the top level (we also got some assertions there now)
- Re-aligning the `src_files.yml` used in PULP systems
> Minor fixes

- dv/uvm/core_ibex/Makefile
- dv/uvm/core_ibex/sim.py
This fixes a small but annoying bug - when `run_sim_commands()` is called, the `lsf_cmd` argument that it takes in is always set to `True` by default even when we don't want to run on LSF, as the default value of `lsf_cmd` passed in from the top level Makefile is always `''`, which when compared to `None` will return `True`, causing seemingly random regression timeouts.
This fixes this issue by defaulting `args.lsf_cmd` to an empty string and comparing the `lsf_cmd` argument value in the `run_sim_commands` call to an empty string instead of `None`.
> [dv] fix spurious LSF enabling

- doc/instruction_decode_execute.rst
- doc/integration.rst
- lint/verilator_waiver.vlt
- rtl/ibex_alu.sv
- rtl/ibex_core.sv
- rtl/ibex_decoder.sv
- rtl/ibex_pkg.sv
- rtl/ibex_tracer.sv
- rtl/ibex_tracer_pkg.sv
This commit implements the Bit Manipulation Extension SBS instruction group: sbset[i], sbclr[i], sbinv[i] and sbext[i]. These instructions set, clear, invert or extract bit rs1[rs2] or rs1[imm] for reg-reg and reg-imm instructions respectively.
Archtectural details:
- A multiplexer is added to the shifter structure in order to chose between 32'h1, used for the single-bit instructions as summarized below, and regular operand_b input.
- Dedicated bitwise-logic blocks are introduced for multicycle shifts and cmix instructions (fsr, fsl, ror, rol), single-bit instructions (sbset, sbclr, sbinv, sbext), and stanard-ALU and zbb instructions (or, and xor, orn, andn, xnor).
Instruction details: All of the zbs instructions rely on sharing the existing shifter structure. The instructions are carried …
> [bitmanip] Add ZBS Instruction Group

- rtl/ibex_load_store_unit.sv
- pmp_err_q needs to clear once the LSU state machine returns to idle,
otherwise it will remain set indefinely.
- Relates to #808
> [rtl/lsu] Fix bug in pmp error clearing

- rtl/ibex_tracer.sv
Failing to read rd in tracer for fsri caused bitmanip DV test to fail.
The bitmanip DV test is introduced in PR #809.
> [bitmanip] Fix bitmanip DV test failure

- rtl/ibex_icache.sv
- valid_o needs qualifying with output_error to mask X's in the output
data.
- err_plus2_o should not depend on the output data, only the alignment and
error status are relevant. Also needs skid_valid_q to mask
skid_error_q which is not reset.
> [rtl/icache] Fix some issues in icache

- dv/uvm/icache/dv/env/ibex_icache_env.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_agent.core
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_agent_pkg.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_sequencer.sv
- dv/uvm/icache/dv/ibex_icache_sim_cfg.hjson
This pretty much follows various UVM tutorials, except that we use the
sequencers (ibex_icache_core_sequencer, ibex_icache_mem_sequencer) to
poke the heartbeat objection object if there is one.
Doing this means that we can dispense with the explicit test timeout
in the hjson file: the test will fail if there is no activity on
either interface for 2000 cycles (this number is chosen because the
longest "wait a bit" time is 1200 cycles in the core driver).
> Add heartbeat tracking to ICache testbench

- dv/uvm/icache/dv/env/ibex_icache_scoreboard.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_agent.core
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_agent_pkg.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_bus_item.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_if.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_monitor.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_protocol_checker.sv
- dv/uvm/icache/dv/tb/tb.sv
Since the memory agent PR (#793) is slightly stalled, I've split out the follow-up work that adds monitors and SVA assertions. This is the code that applies to the core agent.
You should be able to build it, but it won't run to completion because there is no memory agent. I have (of course) checked that rebasing the patches from #793 on top of this patchset results in something that works.
> Monitor and SVA assertions for core agent in icache UVM testbench

- dv/uvm/icache/dv/env/ibex_icache_scoreboard.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_agent.core
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_agent_pkg.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_bus_item.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_if.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_monitor.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_protocol_checker.sv
- dv/uvm/icache/dv/tb/tb.sv
The equivalent PR for the core side is PR #807. (In fact, these patches have been split, so the commit messages look rather similar).
I don't believe there are any remaining review items open on that PR that apply here. These were relevant, but are now resolved:
1. ~~Naming of the interface that holds the assertions (see [here](https://github.com/lowRISC/ibex/pull/807#discussion_r413213740)).~~ (this naming seems ok)
1. ~~Naming of the object that reports bus transactions (see [here](https://github.com/lowRISC/ibex/pull/807#discussion_r413201343)).~~ (renamed as requested to `ibex_icache_mem_bus_item`)
> Add monitor and SVA checks to icache <-> memory interface in UVM testbench

- doc/verification.rst
- dv/uvm/core_ibex/Makefile
- dv/uvm/core_ibex/riscv_dv_extension/riscvOVPsim.ic
- dv/uvm/core_ibex/riscv_dv_extension/riscv_core_setting.sv
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
This PR enables verification of the Bitmanip Extension with OVPsim and Spike and adds a new test that can be updated in the future to also include newly added instruction groups. For Spike,
a different branch has to be used. This PR updates the documentation accordingly.
What is still missing is support for coverage. This will be later vendored in from upstream RISCV-DV.
This is related to lowRISC/ibex#703.
> [dv] Enable verification of the Bitmanip Extension with OVPsim and Spike

- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_monitor.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_driver.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_resp_item.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/seq_lib/ibex_icache_mem_resp_seq.sv
These fix various bugs that I ran into when trying to get the scoreboard working properly. The most interesting patch is probably the second: it turns out that my previous plan to spot fetch requests is fragile and doesn't take the non-determinacy of delta-cycle scheduling into account. Oops!
> Assorted bugfixes in the ICache UVM test code

- vendor/lowrisc_dv_lib.lock.hjson
- vendor/lowrisc_ip/dv_lib/dv_base_driver.sv
- vendor/lowrisc_ip/dv_lib/dv_base_mem.sv
- vendor/lowrisc_ip/dv_lib/dv_base_reg.sv
- vendor/lowrisc_ip/dv_lib/dv_base_sequencer.sv
- vendor/lowrisc_ip/dv_lib/dv_base_test.sv
Update code from subdir hw/dv/sv/dv_lib in upstream repository
https://github.com/lowRISC/opentitan to revision
1d17b1225d324c81da522c69317335a83edd5ddb
* [dv] Add excl for rstmgr, pwrmgr and fix top-level csr test (Weicai
Yang)
* [dv] Allow dv_lib-based sequences to have different RSP/REQ types
(Rupert Swarbrick)
* [dv] Support WO, RO type for mem (Weicai Yang)
* [dv,sw] SW -> DV tb self-checking mechanism - SV (Srikrishna Iyer)
* [dv/top] Fix csr rw test (Cindy Chen)
Signed-off-by: Rupert Swarbrick <rswarbrick@lowrisc.org>
> Update dv_lib to lowRISC/opentitan@1d17b122

- dv/uvm/icache/dv/env/seq_lib/ibex_icache_sanity_vseq.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_agent.core
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_agent_pkg.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_driver.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_req_item.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_rsp_item.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_sequencer.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/seq_lib/ibex_icache_core_base_seq.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/seq_lib/ibex_icache_core_sanity_seq.sv
This fixes a bug in the core agent where it could start trying to fetch data again without a branch after it had seen an error from the cache.
> Branch after error

- doc/instruction_decode_execute.rst
- doc/integration.rst
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- rtl/ibex_alu.sv
- rtl/ibex_decoder.sv
- rtl/ibex_pkg.sv
- rtl/ibex_tracer.sv
- rtl/ibex_tracer_pkg.sv
This commit implements the Bit Manipulation Extension ZBP instruction group: grev[i] (generalized reverse), gorc[i] (generalized or-combine) and [un]shfl[i] (generalized shuffle) and all of their pseudo-instructions.
Architectural details:
* grev / gorc: The shifter structure features only a right structure. In order to perform a left shift therefore the needs to be reversed, shifted and reversed again. The architecture 
of the back-reversal is implemented in stages are activated using the general reverse / orcombine operand or a signal marking left-shifts.
*  shfl / unshfl: Also known as zip / unzip or interlace / operation. These instructions are implemented in their own structure using a permutation networ of 6 stages. 4 stages thereof implement the shuffle permutations. The first and …
> [bitmanip] Add ZBP Instruction Group

- dv/uvm/core_ibex/Makefile
I'd overlooked changing the hardcoded LSF_CMD argument of the `cov` target to using `$(lsf-arg)` after adding a check in sim.py to return an error if the lsf command is an empty string - this PR simply updates this to prevent spurious error signaling.
> [dv] makefile:cov LSF arg fix

- dv/uvm/icache/dv/env/ibex_icache_scoreboard.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_bus_item.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_monitor.sv
This correctly tracks fetch addresses and fetched data. It understands
changing memory seeds, errors, invalidations and enable/disable.
Most of the complexity is in checking whether a fetch got the right
answer, given the set of memory seeds that it might have used. This
isn't conceptually hard (use a local memory model; check each seed and
see whether it matches), but is a bit fiddly in practice. In
particular, a misaligned 4-byte load might actually correspond to two
different seeds: note the nested loops in `check_compatible_2`.
The general flow of these checks is:
```
check_compatible
-> check_compatible_<i>    (loop over plausible seeds)
-> is_seed_compatible_<i>  (ask the memory what data to expect)
-> is_fetch_compatible_<i> (compare seen/expected data)
```
Note that the …
> Initial icache scoreboard

- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_driver.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_if.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_req_item.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/seq_lib/ibex_icache_core_sanity_seq.sv
- dv/uvm/icache/dv/ibex_icache_sim_cfg.hjson
The first commit makes them longer; the second makes sure we actually see the invalidate pin toggle occasionally.
> Minor tweaks to make icache test sequences more interesting

- rtl/ibex_core.sv
- rtl/ibex_decoder.sv
- rtl/ibex_ex_block.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_multdiv_fast.sv
- rtl/ibex_multdiv_slow.sv
This PR reworks the generation and usage of the `mult/div_en/sel` signals.
Previously, the `multdiv_sel` was generated in the ALU decoder and used inside the ALU primarily. The `mult/div_en` signals were generated in the regular decoder, qualified with `illegal_insn` and `instr_executing` and used for controlling the FSMs inside multdiv as well as a couple of data muxes. 
This means that, If the 3rd pipeline stage is enabled, also LSU exception and hazard signals are factored into the control signals of these data muxes (some of which are on the critical path).
With this PR, these signals are reworked as follows:
- The unqualified `multdiv_sel` signal is split into `mult_sel` and `div_sel` both generated inside the ALU decoder. Only these unqualified signals are used to control data muxes …
> [rtl] Rework multdiv_en/sel

- rtl/ibex_icache.sv
- Data valid should only be signalled when the current beat is
signalling an error
- PMP errors for future beats can sneak in while waiting for the
current beat
> [rtl] icache error signalling fix

- dv/uvm/icache/dv/env/ibex_icache_scoreboard.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_agent_pkg.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_bus_item.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_model.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_monitor.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_req_item.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/seq_lib/ibex_icache_mem_resp_seq.sv
The flow for a memory fetch is:
1. Cache requests data for a memory address
2. Agent spots the request, maybe signalling a PMP error
3. Grant line goes high, at which point the request is granted.
4. Sometime later (in-order pipeline), agent sends a response
Occasionally, we need to pick a new seed for the backing memory.
Before this patch, we picked these seeds at point (3).
Unfortunately this was wrong in the following case:
1. We're switching from seed S0 to seed S1.
2. The request is spotted with seed S0 and doesn't signal a PMP error
3. The request is granted and we switch to seed S1.
4. We respond with data from memory based on S1, with no memory
error either
If S1 would have caused a PMP error, the resulting fetch (no error,
but data from S1) doesn't match any possible seed and the …
> Rework choosing new seeds in icache UVM memory model

- shared/prim_generic_ram_1p.core
- shared/prim_ram_1p.core
- shared/prim_secded.core
- shared/sim_shared.core
- All primitives the icache uses are specified in distinct core files
with names that match those existing (or about to exist) in OpenTitan
- When vendoring-in Ibex, none of those primitives need to be copied
across, since OpenTitan will use its own versions
- Relates to lowRISC/opentitan/#1231
> [prim] Split out primitives used by icache

- rtl/ibex_load_store_unit.sv
- A data or PMP error should stop the register file from being updated
- Fixes #832
> [rtl] Stop regfile writeback for load errors

- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
Pretty straightforward PR, all this does is to enable the writeback stage and the branch ALU in the Ibex testbench.
> [dv] enable writeback stage and branch ALU

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/docs/source/extension_support.rst
- vendor/google_riscv-dv/docs/source/index.rst
- vendor/google_riscv-dv/run.py
- vendor/google_riscv-dv/src/isa/riscv_b_instr.sv
- vendor/google_riscv-dv/src/isa/riscv_instr.sv
- vendor/google_riscv-dv/src/isa/riscv_vector_instr.sv
- vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
- vendor/google_riscv-dv/src/riscv_instr_cov_item.sv
- vendor/google_riscv-dv/src/riscv_instr_cover_group.sv
- vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
- vendor/google_riscv-dv/src/riscv_instr_pkg.sv
- vendor/google_riscv-dv/src/riscv_instr_sequence.sv
- vendor/google_riscv-dv/src/riscv_pmp_cfg.sv
- vendor/google_riscv-dv/target/rv64imcb/riscvOVPsim.ic
- vendor/google_riscv-dv/target/rv64imcb/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv64imcb/testlist.yaml
- vendor/google_riscv-dv/test/riscv_instr_cov_test.sv
- vendor/google_riscv-dv/test/riscv_instr_test_lib.sv
dv to revision ace2805b63100f46c3dcd02b4fcf6a7184582110
* Fix vector instruction randomization (google/riscv-dv#560) (taoliug)
* Change generate_instr_stream to a virtual function (google/riscv-
dv#559) (taoliug)
* fix bug with compressed ebreak generation (google/riscv-dv#557)
(udinator)
* update PMP exception handlers to 'fix' config CSRs (google/riscv-
dv#546) (udinator)
* Add bitmanip doc (google/riscv-dv#555) (weicaiyang)
* specify physical pmp addresses from cmdline (Udi Jonnalagadda)
* Fix branch hit coverage issue (google/riscv-dv#551) (taoliug)
* B extension coverage part2 (google/riscv-dv#548) (weicaiyang)
* B extension coverage part1 (google/riscv-dv#542) (weicaiyang)
* Fix typo in riscv_instr_test_lib …
> Update google_riscv-dv to google/riscv-dv@ace2805

- dv/cs_registers/tb_cs_registers.core
- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
- examples/simple_system/ibex_simple_system.core
As discussed in issue #845, this tells VCS to wait for signals to
settle in combinatorial blocks before checking uniqueness in
constructs like unique case.
Otherwise things like this can cause spurious warnings:
```systemverilog
always_comb b = ~in;
always_comb c = in;
always_comb begin
unique case (1'b1)
b: x = 1;
c: x = 0;
default: x = 0;  // not that it matters, but this won't happen
endcase
end
```
For example, on a falling edge of the `in` signal, if the processes are
executed in the order 1, 3, 2 then the unique case block will appear
to see both `b` and `c` true at the same time.
> Specify "-xlrm uniq_prior_final" for VCS

- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_driver.sv
This works around a bug tracked in issue #850.
> Always assert ready in core driver for ICache UVM testbench

- doc/instruction_decode_execute.rst
- doc/integration.rst
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- rtl/ibex_alu.sv
- rtl/ibex_decoder.sv
- rtl/ibex_pkg.sv
- rtl/ibex_tracer.sv
- rtl/ibex_tracer_pkg.sv
This commit implements the Bit Manipulation Extension ZBE instruction
group: bext (bit extract) and bdep (bit deposit).
Architectural details:
* bext/bdep: A new butterfly and inverse butterfly network is
implemented. The generation of its controlbits depend on a
parallel prefix bitcount of the deposit / extract mask.
* bitcounter: The path for bext / bdep instructions traverses
the bit counter and the butterfly network, resulting in both a
larger delay and area. To mitigate the bitcounter has been
changed from a serial bit counter to a radix-2 tree structure.
* grev/gorc: Zbp instructions general reverse and general
or-combine have as of yet shared the shifters reversal
structure. It has proven benefitial to area and timing to reuse
the novel butterfly network instead
The butterfly …
> [bitmanip] Add ZBE Instruction Group

- doc/instruction_decode_execute.rst
- doc/integration.rst
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- rtl/ibex_alu.sv
- rtl/ibex_decoder.sv
- rtl/ibex_pkg.sv
- rtl/ibex_tracer.sv
- rtl/ibex_tracer_pkg.sv
This commit implements the Bit Manipulation Extension ZBF instruction
group, which consists only of the one instruction bfp (bit-field
place).
This instruction places a field of length len < 16 from rs2 in rs1 at
offset off.
Architectureal details:
The implementation works exactly the same as proposed by Claire
Wolf in her reference implementation.
1. bfp_mask = slo(o, len)
2. bfp_result =
(rs1 & ~(bfp_mask << off)) | (rs2 & bfp_mask) << off
^------ shifter-^
The existing shifter structure is shared for the indicated
operation.
Impact on area:
* When synthesizing without the B-extension, the 2 stage 
design seems to move the timing bottleneck, leading to 
optimizations which result in an area increase by 1 kGE, 
when synthesized with tight timing constraints. For the 
3 stage …
> [bitmanip] Add ZBF instruction group

- rtl/ibex_alu.sv
- rtl/ibex_decoder.sv
- rtl/ibex_pkg.sv
- rtl/ibex_tracer.sv
- rtl/ibex_tracer_pkg.sv
This commit implements the Bit Manipulation Extension sign-extend
instructions: sext.b (sign-extend byte) and sext.h (sign-extend half
word).
The implementation is basically a one-liner, duplicating the msb of the
byte / half-word into the msb of the output register.
> [bitmanip] Add sext.b/h instructions

- dv/riscv_compliance/ibex_riscv_compliance.core
- examples/simple_system/ibex_simple_system.core
- ibex_core.core
- ibex_core_tracing.core
Change default to 4 rather than 0. Makes no difference when PMPEnable==0
and gets rid of lint failures due to 0 array referencing (0 is an
unsupported value for this parameter).
> [config] Change default PMPNumRegions

- dv/uvm/icache/dv/env/ibex_icache_env.sv
- dv/uvm/icache/dv/env/ibex_icache_scoreboard.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_agent_pkg.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_bus_item.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_driver.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_monitor.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_req_item.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_resp_item.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/seq_lib/ibex_icache_mem_resp_seq.sv
The previous code kind of worked, but we were making the "should I
make a new seed" decision in the monitor, rather than the sequence.
The problem is that this is difficult to customize with other test
sequences (they sit adjacent to the monitor in the class hierarchy,
not above it).
The new code seems a little cleaner. We generate new seeds in the
sequence (which is in charge of keeping track of the current seed
anyway). These new seeds get passed to the driver, which has an
analysis port by which it can tell the scoreboard about them. Note
that we have to pass them from the driver, rather than the monitor,
because the new seed doesn't directly appear on the interface.
The rest of the changes are simplifying the ibex_icache_mem_bus_item
class, which now only has two modes and removing …
> Move seed updates into sequence in ICache memory agent

- dv/uvm/icache/data/ibex_icache_testplan.hjson
I think these represent the test cases we discussed. I've also removed
non-existent entries from the "tests" keys: I didn't really understand
how dvsim.py worked when I wrote the original version and they just
cause irritating warnings.
> Update ICache testplan after review meeting

- doc/instruction_decode_execute.rst
- doc/integration.rst
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- rtl/ibex_alu.sv
- rtl/ibex_decoder.sv
- rtl/ibex_pkg.sv
- rtl/ibex_tracer.sv
- rtl/ibex_tracer_pkg.sv
This commit implements the Bit Manipulation Extension ZBC instruction
group: clmul[rh] (carry-less multiply [reverse][high])
Carry-less multiplication can be understood as multiplication based on
the addition interpreted as the bit-wise xor operation.
Example: 1101 X 1011 = 1111111:
1011 X 1101
-----------
1101
xor 1101
---------
10111
xor 0000
----------
010111
xor 1101
-----------
1111111
Architectural details:
A 32 x 32-bit array
`[ operand_b[i] ? (operand_a << i) : '0 for i in 0 ... 31 ]`
is generated. The entries of the array are pairwise 'xor-ed'
together in a 5-stage binary tree.
The area increase when synthesized with relaxed timing constraints is
1.6-1.7kGE.
Timing figures are improve by 0.1 ns for the 3-stage configuration and
worsen by 0.04ns for the 2-stage implementation. …
> [bitmanip] Add ZBC instruction group

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
Hey!
In this pull request I added missing `cmp_opts` to Riviera compilation options
> added missing cmp_opts to Riviera compilation options

- doc/cs_registers.rst
- doc/index.rst
- doc/security.rst
- dv/uvm/core_ibex/ibex_dv.f
- ibex_core.core
- rtl/ibex_core.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_dummy_instr.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_pkg.sv
- rtl/ibex_register_file_ff.sv
- rtl/ibex_register_file_fpga.sv
- rtl/ibex_register_file_latch.sv
- shared/prim_lfsr.core
- shared/rtl/prim_lfsr.sv
- Adds a new module in the IF stage to inject dummy instructions into
the pipeline
- Control / frequency of insertion is governed by configuration CSRs
- Extra CSR added to allow reseed of the internal LFSR useed for
randomizing insertion
- Extra logic added to the register file to make dummy instruction
writebacks look like real intructions (via the zero register)
> [rtl] Add dummy instruction insertion

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
- vendor/google_riscv-dv/yaml/simulator.yaml
dv to revision 7b38e54c5e833f147edc03717b3fd711be923026
* add cmdline configuration of mstatus.mprv (Udi Jonnalagadda)
* Add Xcelium support (google/riscv-dv#579) (Tudor Timi)
> Update google_riscv-dv to google/riscv-dv@7b38e54

- examples/simple_system/ibex_simple_system.core
To allow other modules to reference the simple system, it must provide
default files. In particular this is useful in DV settings where bind
is used.
Signed-off-by: Stefan Wallentowitz <stefan.wallentowitz@hm.edu>
> Change simple system core file to provide default files

- dv/verilator/pcount/cpp/ibex_pcounts.cc
- dv/verilator/pcount/cpp/ibex_pcounts.h
- examples/simple_system/ibex_simple_system.cc
- examples/simple_system/rtl/ibex_simple_system.sv
DPI access is suggested and more generic than Verilator direct signal
access. This changes the access to the performance counters from the
Verilator testbench to use DPI instead of directly accessing the
array.
> [dv] Change performance counter access to DPI

- dv/riscv_compliance/ibex_riscv_compliance.cc
- dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
- shared/rtl/ram_1p.sv
- shared/sim_shared.core
ram_1p is almost a copy of the single-port RAM primitive we have in
OpenTitan, called prim_ram_1p, with its generic implementation
prim_generic_ram_1p. Instead of having a copy of that file in Ibex,
consistently use the OpenTitan one.
Unfortunately, ram_1p has slightly different semantics around some
signals, especially rvalid. This commit adjusts the meanings of the
signals for now, since I don't have a way to test the Arty board
which also uses this primitive (together with the compliance test
suite). With the testing in the compliance suite I'm reasonably certain
that the Arty board will work as well.
> Use prim_generic_ram_1p in ram_1p

- doc/instruction_decode_execute.rst
- doc/integration.rst
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- rtl/ibex_alu.sv
- rtl/ibex_decoder.sv
- rtl/ibex_pkg.sv
- rtl/ibex_tracer.sv
- rtl/ibex_tracer_pkg.sv
This commit implements the Bit Manipulation Extension ZBR instruction
group: crc32[c].[bhw].
CRC-32 (CRC-32/ISO-HDLC) and CRC-32C (CRC-32/ISCSI) are directly
implemented. The CRC operation solves the following equation using
binary polynomial arithmetic:
```
rev(rd)(x) = rev(rs1)(x) * x**n mod {1, P}(x)
```
where {1,P}(x) denotes the crc polynomial. Using barret reduction one
can write this as
```
rd = (rs1 >> n) ^ rev(rev( (rs1 << (32-1)) cx rev(mu)) cx P)
^-- cycle 0--------------------^
^-- cycle 1 ------------------------------------------^
```
Where `cx` denotes carry-less multiplication and `mu = polydiv(x**64,
{1,P})`, omitting the MSB (bit 32).
The implementation increases area consumption by ~0.6kGE for synthesis
with relaxed timing constraints. With tight timing constraints that …
> [bitmanip] Add ZBR instruction group

- dv/uvm/core_ibex/env/core_ibex_rvfi_if.sv
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- formal/.gitignore
- formal/Makefile
- formal/README.md
- rtl/ibex_core.sv
- rtl/ibex_core_tracing.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_pkg.sv
- rtl/ibex_tracer.sv
Provide a conversion of SystemVerilog to Verilog for riscv-formal.
Update RVFI to include IXL (following upstream update). For this I made the local parameter MXL a global parameter CSR_MISA_MXL so it can be used in `ibex_core.sv`.
A new top level folder `formal` is used. This reflects the usage of `formal` in OpenTitan `hw`, instead of putting it into `dv/formal`.
The conversion is done with a Makefile and does not use FuseSoC, which is somewhat not good as the list for the source files is replicated, but this makes it easier to be used by riscv-formal.
It also stores output artifacts in `formal/build`. The intention here is to decouple it from the FuseSoC system, but I can see that it can also at some confusion.
> Riscv-formal Verilog source

- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_driver.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_protocol_checker.sv
- rtl/ibex_icache.sv
- Remove any ready -> valid dependency by allowing the skid buffer to
accept data when the core is not ready
- Tighten-up behaviour around invalidations and cache enable/disable
- Remove xprop through output_compressed from invalid data when driving errors
- Make behaviour more consistent where speculative requests return
different data/error conditions to existing cache hit
> [rtl] Various small icache bugfixes

- doc/icache.rst
- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_icache.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_prefetch_buffer.sv
- Drive a speculative version of the branch signal into the IF stage to
drive address muxing
- The speculative signal is the same as the regular branch signal but
assumes all conditional branches are taken
- This breaks the timing path from branch condition calculation into
address muxing (and therefore PMP error calculation)
- When the branch is not taken, any external request we might otherwise
have made is suppressed
- This has a minor performance cost (0.8% without I$, ~0% with I$)
> [rtl] Add speculative branch signal

- util/ibex_config.py
Fix a deprecation, to be removed in Python 3.10.
See https://docs.python.org/3/library/collections.html:
"Deprecated since version 3.3, will be removed in version 3.10: Moved
Collections Abstract Base Classes to the collections.abc module. For
backwards compatibility, they continue to be visible in this module
through Python 3.9."
> Fix deprecation warning in ibex_config.py

- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- test_en_i is a DFT feature that shouldn't be enabled for normal
runtime testing
- Only really affects the clock gate in the design, but is needed for
running tests with the latch-based register file
> [DV] Tie test_en_i to zero

- rtl/ibex_icache.sv
The RAM primitive provides a way to specify the granularity of the write
mask (wmask) signal, which can be used to select an appropriate
implementation (e.g. a SRAM with only byte selects, or no subselects at
all).
---
Even though this change should be safe, I've seen X asserts fire on this one previously in icache UVM DV. I cannot test right now until #904 is fixed.
> Optimize use of RAM primitive in icache

- python-requirements.txt
This dependency gets pulled in with dvsim.py since OpenTitan [commit
1aff665d2](https://github.com/lowRISC/opentitan/commit/1aff665d27d93ce0108cc80c200b52f0936d6878), vendored in with Ibex commit 1bbcce0.
> Add missing Python dependency on premailer library

- rtl/ibex_fetch_fifo.sv
- rtl/ibex_prefetch_buffer.sv
- The prefetch buffer needs to know when space is available in the fetch
FIFO to accept a new external request.
- This change updates that logic to look at what is in the FIFO and what
is outstanding on the bus to decide when space is available rather
than always assuming the maximum number of requests are outstanding.
- This improves the usage efficiency of the FIFO and fixes #574
> [rtl] prefetch buffer performance fix

- rtl/ibex_pmp.sv
- Apply address masking to the bottom address bit for NA4 as well as
NAPOT
- Relates to #902
> [rtl] Fix PMP NA4 address matching

- rtl/ibex_core.sv
- rtl/ibex_id_stage.sv
- The speculative branch behaviour causes a performance degradation of
around 3% in the max config. This change enables that behaviour only
the maximum PMP config, which is where it is most needed for timing
closure.
> [rtl] Make speculative branch optional

- dv/uvm/icache/data/ibex_icache_testplan.hjson
- dv/uvm/icache/dv/env/ibex_icache_env.core
- dv/uvm/icache/dv/env/seq_lib/ibex_icache_back_line_vseq.sv
- dv/uvm/icache/dv/env/seq_lib/ibex_icache_vseq_list.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_agent.core
- dv/uvm/icache/dv/ibex_icache_core_agent/seq_lib/ibex_icache_core_back_line_seq.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/seq_lib/ibex_icache_core_base_seq.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/seq_lib/ibex_icache_core_seq_list.sv
- dv/uvm/icache/dv/ibex_icache_sim_cfg.hjson
This turns out to be reasonably easy to plumb in: derive from the core
sequence base class, overriding its run_req method (once I've
remembered to make it virtual). Then pick the right core sequence by
adding a factory override in the vseq.
> Add backward_line icache test sequence

- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_if.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_protocol_checker.sv
- dv/uvm/icache/dv/tb/tb.sv
This should have no functional change - it's still set iff branch is
set - but the logic now lies in the UVM code, rather than the
structural code in tb.sv.
> Wire in the branch_spec signal properly in ICache testbench

- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_agent_cov.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_if.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_monitor.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_protocol_checker.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_agent_cov.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_monitor.sv
- dv/uvm/icache/dv/tb/tb.sv
This doesn't define points for interesting behaviours that we're trying to hit with special tests in the testplan (I'll do that in a follow-up). It also doesn't define points for uarch coverage, which will use slightly different machinery.
This PR depends on PR #935 for the first patch: let's review that commit there, rather than here, if necessary.
@tomroberts-lowrisc: Can you think of any other sensible interface-level coverage points that we should define? I'd have thought that most "weird timing" coverage points should be uarch-level, because it will be easier to describe them there, but maybe I've missed something?
> Add interface-level functional coverage to icache tests

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
This PR adds 3 new PMP tests, and updates the existing PMP test in the Ibex testlist.
1) `riscv_pmp_basic_test` - this updates the existing Ibex-specific PMP sanity test, where every PMP region is given full x/w/r permissions and operates in TOR address matching mode, as a result the core should be able to successfully execute every instruction fetch and memory load/store without any faults being raised.
2) `riscv_pmp_disable_all_regions_test` - In this test, all x/w/r permissions are stripped from every PMP region and TOR address matching is enabled by default for every region. We should see every fetch from IMEM and every load/store from DMEM raise an exception to trap into the custom exception handler.
3) `riscv_pmp_out_of_bounds_test` - In this test, default PMP settings are used …
> [ibex/dv] Add several PMP tests

- rtl/ibex_register_file_ff.sv
By giving each register its own always_ff block clock gating is more
obvious to synthesis tools.
This also includes some minor naming tweaks to make use of the _q
convention for flops.
> [rtl] Use generate loop in FF register file

- rtl/ibex_core.sv
Corrects a typo, ibex_wb_stage and ibex_register_file were being
supplied with the ungated clk.
> [rtl] Use gated clock for wb_stage and rf

- rtl/ibex_register_file_latch.sv
This matches the style used in the FF based register file. It gives each
register its own always block with a single enable rather than having
multiple registers with enables in a single always block.
Signed-off-by: Greg Chadwick <gac@lowrisc.org>
> [rtl] Use outer generate loop for latch RF

- rtl/ibex_icache.sv
- Remove the timing optimisations that delay the factoring-in of ecc
errors into valid_o.
- Optimisations are probably unnecessary here due to the minimal logic
hanging off valid_o, and the optimisations cause protocol checker
violations.
> [rtl] Simplify I$ ECC error handling

- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- The testbench probes signals that are unqualified by instr_valid
- This causes events to trigger due to instructions that are not
actually executed, leading to false timeout failures
- Note this fix alone doesn't eliminate such failures due to another
issue which will be addressed separately
> [dv] Fix DUT probe IF paths

- dv/uvm/icache/dv/env/ibex_icache_scoreboard.sv
- dv/uvm/icache/dv/ibex_icache_ecc_agent/ibex_icache_ecc_driver.sv
One change is a bug-fix (I'd left something with verbosity UVM_LOW, when it should have been UVM_HIGH). The other is to improve debuggability.
> Changes to verbosity in ICache UVM tests

- dv/uvm/icache/dv/env/ibex_icache_scoreboard.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_driver.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_if.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_monitor.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/seq_lib/ibex_icache_core_back_line_seq.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/seq_lib/ibex_icache_core_base_seq.sv
There are 4 patches in the series.
1. Make it more likely that a branch will land at the edge of the address space (to check wrapping)
1. Allow the ready signal to be high when a branch hits (this has no effect, but is allowed by the spec, so we may as well do it sometimes).
1. Make the "cancelled_valid" sequence spot what it was supposed to spot
1. Fix the wiring downstream of the "cancelled_valid" sequence (I was turning on the monitor after the run phase had completed, which meant it didn't see very much!).
> Tweak ICache tests to fill functional coverage defined so far

- dv/uvm/core_ibex/riscv_dv_extension/riscv_core_setting.sv
This PR just adds some required (but mostly unused) parameters to `riscv_core_setting.sv` to match the updated version of the instruction generator - required to allow the Ibex DV environment to compile successfully.
The vector parameters are not used, since Ibex does not support the vector instruction set; same with `num_float_gpr` and `num_vec_gpr`, as Ibex also does not support the floating point instruction set.
> [dv/ibex] Update riscv_core_setting to match latest version of riscv-dv

- dv/uvm/icache/dv/ibex_icache_sim.core
- dv/uvm/icache/dv/ibex_icache_sim_cfg.hjson
- dv/uvm/icache/dv/late_cfg.hjson
It seems that dvsim.py doesn't actually use fusesoc to do things like
pass parameters. Instead, we have to set the tool-specific options in
the hjson file by hand.
Fixes issue #964.
> Enable ICache ECC in the way dvsim.py requires

- dv/uvm/icache/dv/ibex_icache_ecc_agent/ibex_icache_ecc_agent.core
- dv/uvm/icache/dv/ibex_icache_ecc_agent/ibex_icache_ecc_if.sv
- dv/uvm/icache/dv/ibex_icache_ecc_agent/ibex_icache_ecc_protocol_checker.sv
- dv/uvm/icache/dv/prim_badbit/prim_badbit_ram_1p.sv
- rtl/ibex_icache.sv
Since we are binding in an interface anyway, we can add some SV
assertions to make sure nothing too strange is happening.
Note that they aren't as strong as you might expect: we don't check
that rdata isn't X, for example. This is because the cache makes
speculative reads, which it (hopefully) ignores if the data is
invalid.
> Add some basic protocol checking to the icache's RAM interface

- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_master_driver.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_monitor.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_slave_driver.sv
- dv/uvm/core_ibex/common/irq_agent/irq_if.sv
- dv/uvm/core_ibex/common/irq_agent/irq_master_driver.sv
- dv/uvm/core_ibex/common/irq_agent/irq_monitor.sv
- dv/uvm/core_ibex/env/core_ibex_csr_if.sv
- dv/uvm/core_ibex/env/core_ibex_dut_probe_if.sv
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/tests/core_ibex_seq_lib.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
This PR simply adds clocking blocks to all major Ibex interface agents and updates all interface accesses to use these clocking blocks to enforce clock synchronization.
@tomroberts-lowrisc this should address #954. I tested the `riscv_dret_test` and other similar tests that you noticed some arbitrary errors in, and they all seem to pass successfully with these changes
A few notes about some parts of this PR:
- `ibex_mem_intf` has two driver clocking blocks added, one for host side and one for device side. This is because our Ibex testbench currently provides both host and device agents for the Ibex I/D-side interfaces (of course we only use the reactive device agents in the main testbench). If you feel the host agents should be removed, I can do this in a later PR.
- `csr_if` has only one …
> [ibex/dv] Add clocking blocks to Ibex interfaces

- dv/uvm/icache/dv/top_pkg.sv
- rtl/ibex_alu.sv
- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_counter.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_id_stage.sv
This fixes several style lint warnings in Ibex. Note that the `top_pkg` from Ibex seems to override the `top_pkg` from OpenTitan (hence we get all these duplicate warnings about missing parameter types in https://reports.opentitan.org/hw/ip/rv_core_ibex/lint/veriblelint/latest/results.html). This is another instance of https://github.com/lowRISC/opentitan/issues/1231 and we should resolve this.
> [top_pkg] Fix style lint warnings

- rtl/ibex_dummy_instr.sv
Although CSR_SECURESEED is unreadable, an attacker can write a new seed, which
brings convenience to the attack. This patch is used to XOR the historical seed,
so that even if the attacker writes a new value to CSR_SECURESEED , he cannot
know the value of the seed.
Signed-off-by: Xiang Wang \<merle@hardenedlinux.org\>
> Prevent writing CSR_SECURESEED to get the seed of dummy instruction

- examples/sw/simple_system/pa_test/pa_test.c
- rtl/ibex_cipher.sv
- rtl/ibex_pointer_authentication.sv
We have some lint errors below in Pointer Authentication. I fixed it.
- Bits of signal are not used
- Case values incompletely covered
- Signal unoptimizable: Feedback to clock or circular logic
- Run clang-format on pa_test.c
> Fix Pointer Authentication lint errors

- rtl/ibex_core.sv
- rtl/ibex_decoder.sv
- rtl/ibex_id_stage.sv
With the writeback stage enabled we execute the PAC/AUT instruction before the required data is written to the register file. For example, when the load instruction precedes AUT instruction, AUT instruction is started before the loaded data is written to the register file. It is a problem that the hazard detection (`stall_ld_hz`) using `rf_ren_a/b_o` was not active for PAC/AUT instruction. So, I change codes to set `rf_ren_a/b_o` in the decoder.  Also, I change codes not to activate `pa_pac_en` or `pa_aut_en` when load hazard occurs. 
I show how the waveform changes before and after. I build with this command (`fusesoc --cores-root=.run --target=sim --setup --build lowrisc:ibex:ibex_simple_system --RV32M=1 --RV32E=0 --PMPEnable=1 --PointerAuthentication= 1 --WritebackStage=1`) and run …
> Fix hazard detection issues for Pointer Authentication 

- rtl/ibex_id_stage.sv
I am implementing a counter and tracer for PAC and AUT instructions. However, I have a problem.
PAC instruction writes to the register file twice, so when not taking `stall_pa` into consideration, `instr_id_done_o` is activated twice during the execution of an PAC instruction. Unfortunately it interferes with the implementation of counters and tracers for PAC. Furthermore, it may not be good for the done signal to be activated twice during the execution of one instruction. So I want to fix it a little.
> Fix instr_id_done_o for PAC instruction

- rtl/ibex_icache.sv
- invalidate all ways on a tag error to prevent xprop from the data
error signal and reduce the likelyhood of multi-way allocations
> [rtl] Fix icache xprop issue

- README.md
- azure-pipelines.yml
- doc/instruction_decode_execute.rst
- doc/integration.rst
- doc/introduction.rst
- dv/riscv_compliance/ibex_riscv_compliance.core
- dv/uvm/core_ibex/Makefile
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- examples/simple_system/ibex_simple_system.core
- examples/simple_system/rtl/ibex_simple_system.sv
- ibex_configs.yaml
- ibex_core.core
- ibex_core_tracing.core
- lint/verilator_waiver.vlt
- rtl/ibex_alu.sv
- rtl/ibex_core.sv
- rtl/ibex_core_tracing.sv
- rtl/ibex_decoder.sv
- rtl/ibex_ex_block.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_multdiv_fast.sv
- rtl/ibex_multdiv_slow.sv
- rtl/ibex_pkg.sv
This commit contains some final optimizations regarding the bit
manipulation extension as well as the parametrization into a balanced
version and a full performance version.
Balanced Version:
* Supports ZBB, ZBS, ZBF and ZBT extensions
* Dual cycle instructions:
ror[i], rol, cmov, cmix fsl, fsr[i]
* Everything else completes in a single cycle.
Full Version:
* Supports all 32b sub extensions.
* Dual cycle instructions:
ror[i], rol, cmov, cmix fsl, fsr[i], crc32[c], bext, bdep
* Everything else completes in a single cycle.
Notable Changes:
* bext/bdep are now multi-cycle: Sharing additional register
with multiplier module
* grev/gorc instructions are implemented in separate structures
rather than sharing the shifter or butterfly network.
* Speed up decision on using rs1 or rs3 for …
> [bitmanip] Optimizations and Parametrization

- doc/introduction.rst
We list all specifications we implement, even optional ones. Add
Bitmanip there as well.
Fixes #966
> [doc] Add bitmanip spec to introduction page

- rtl/ibex_alu.sv
- rtl/ibex_tracer.sv
- rtl/ibex_tracer_pkg.sv
- shared/rtl/bus.sv
- shared/rtl/sim/simulator_ctrl.sv
- shared/rtl/timer.sv
Fix all remaining issues reported by Verible lint.
It turns out that #965 undid some of the fixes in `ibex_alu.sv`
that were done in #980 around the `SHUFFLE_*`/`FLIP_*` signals.
> Fix Verible lint issues

- azure-pipelines.yml
- ci/ibex-rtl-ci-steps.yml
- ibex_core.core
- lint/verible_waiver.vbw
Add the last remaining things to enforce Verible lint in CI:
- Add a waiver file. The waiver files currently don't support comments, and require the "empty" regex; bugs have been filed to get that resolved upstream.
- Enable it per config
- Add lint for the simple system
- Some core file cleanups.
Fixes #579
> Enforce Verible Lint in CI

- doc/getting_started.rst
By now, ibex depends not only on the a clock gating cell, but also on
assert macros and a LFSR; there will be more to come. This removed piece
of documentation was from the early days, when only a clock gating cell
was to be provided (and we didn't ship one).
Today, users need to either use FuseSoC, or run fusesoc on the simple
system and "harvest" the resulting files if they want to copy-paste Ibex
into their build system. That's not ideal, but not something we can very
easily fix -- so let's remove the outdated documentation first to at
least reduce the confusion.
> Remove outdated documentation

- vendor/lowrisc_ip.lock.hjson
- vendor/lowrisc_ip/dvsim/Modes.py
- vendor/lowrisc_ip/lint/tools/verilator/common.vlt
- vendor/lowrisc_ip/prim/prim.core
- vendor/lowrisc_ip/prim/prim_ram_1p_scr.core
- vendor/lowrisc_ip/prim/rtl/prim_ram_1p_scr.sv
- vendor/lowrisc_ip/prim/rtl/prim_subst_perm.sv
Update code from upstream repository
https://github.com/lowRISC/opentitan to revision
976d9b9c1f563173d9e4571c775b38e70cb1c5d4
* [lint] Add blanket waiver for DECLFILENAME with blackboxes (Philipp
Wagner)
* [prim_ram_1p_scr] Add a memory scrambling draft implementation
(Michael Schaffner)
* [prim_subst_perm] Add simple substitution/permutation network
(Michael Schaffner)
* [dvsim] Fix for lowRISC/opentitan#2686 - missing else (Srikrishna
Iyer)
> Update lowrisc_ip to lowRISC/opentitan@976d9b9c

- examples/simple_system/README.md
- examples/simple_system/ibex_simple_system.core
- examples/simple_system/rtl/ibex_simple_system.sv
- shared/rtl/ram_1p.sv
- shared/rtl/ram_2p.sv
This has two components:
1. Plumbing MemInitFile through properly
1. Rejigging the simple_system core file to allow non-verilator builds
I've checked, and the "hello world" example generates the same trace with VCS (modulo some Xs).
> Get the simple_system example working with VCS

- azure-pipelines.yml
- examples/simple_system/ibex_simple_system.core
- ibex_core.core
- ibex_core_tracing.core
- ibex_icache.core
This PR contains a rather odd collection of papercut commits, none of them are really spectacular.
The most significant change, besides the end result of enabling lint for simple system, is the addition of the prim_clock_gating dependency. I'll most likely put this one into a separate PR, but I want to see CI for the whole thing first.
> Enable ibex_simple_system lint in CI

- shared/fpga_xilinx.core
- shared/sim_shared.core
The clock gating primitive is now a dependency of the
lowrisc:ibex:ibex_core file directly and only used in there, we can
remove it from the simulation or FPGA dependency collections.
> Remove lowrisc:prim:clock_gating from shared core collections

- dv/cs_registers/lint/verilator_waiver.vlt
- dv/cs_registers/tb/tb_cs_registers.sv
- dv/cs_registers/tb_cs_registers.core
- dv/riscv_compliance/ibex_riscv_compliance.core
- examples/simple_system/ibex_simple_system.core
- The "PINCONNECTEMPTY" waiver is part of our normal waiver file, no need
to add it to the tool invocation.
- Recent versions of Verilator choose good defaults for MAKE_OPTS,
passing it explicitly overrides the settings.
- All Verilator code is now lint clean, we can remove `-Wno-fatal`.
- FST traces are not much slower then VCD traces any more in recent
Verilator versions, remove the respective comment.
- Align comment about the compile/sim time for tracing with other files
and OpenTitan.
> Clean up Verilator sections in core files

- doc/instruction_decode_execute.rst
- doc/introduction.rst
Support for this extension is not experimental in Ibex. The bitmanip implementation is fully verified using RISCV-DV. Instead the extension might change before being ratified. We will want to align Ibex with the final ratified version of the extension, but implementations based on the current RTL might not get toolchain support in the future. This PR clarifies this.
> [doc] Clarify bitmanip status

- examples/fpga/artya7/top_artya7.core
Use Xilinx-specific implementations for primitives, such as RAM and the
clock gate (which will now be implemented using a BUFGCE macro, and no
longer with a latch).
Verified in Vivado synthesis to pick up the Xilinx primitive now.
> Use the Xilinx primitives for the Arty board

- dv/uvm/core_ibex/common/irq_agent/irq_if.sv
- dv/uvm/core_ibex/common/irq_agent/irq_master_driver.sv
- dv/uvm/core_ibex/env/core_ibex_instr_monitor_if.sv
- dv/uvm/core_ibex/ibex_dv.f
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/tests/core_ibex_seq_lib.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
- dv/uvm/core_ibex/tests/core_ibex_test_pkg.sv
- dv/uvm/core_ibex/tests/core_ibex_vseq.sv
As a result of lowRISC/opentitan#2405 and lowRISC/ibex#928, this PR adds some new
directed interrupt and debug tests to check that the core behaves
properly during execution of each supported instruction when some
external irq/debug stimulus comes in.
To do this, we use the two new functions `decode_instr(...)` and
`decode_compressed_instr(...)` in `core_ibex_test_list.sv` to "decode"
every instruction that the `core_ibex_instr_monitor_if` sees in the ID
stage of the pipeline. Once the testbench decodes an instruction that
we have not seen before, it can then drive interrupt or debug stimulus
into the core.
Once any given instruction has been detected by the testbench (and
stimulus driven), it will no longer drive stimulus if this instruction
is seen in the decode pipeline (e.g. if we …
> [dv/ibex] Add two new interrupt/debug tests

- ibex_core.core
- vendor/lowrisc_ip.lock.hjson
- vendor/lowrisc_ip/prim/fpv/prim_lfsr_fpv.core
- vendor/lowrisc_ip/prim/prim.core
- vendor/lowrisc_ip/prim/prim_lfsr.core
We previously had a dependency on all primitives in Ibex, even though we 
only depend on the LFSR primitive. Now that there's a more fine-grained 
dependency available, we can use that.
This has the great benefit of restricting all lint tools to only the code
we're interested in, and not linting all primitives in OpenTitan together
with Ibex. This also helps tools like yosys, which aren't able to parse all
of OpenTitan's code yet.
> Only include necessary LFSR primitive

- examples/simple_system/README.md
* Mention the need to install `libelf-dev`. Thanks to Bert Pieters for
reporting this.
* Guide users to install our Python dependencies, including fusesoc and
edalize, from `python-requirements.txt`, to ensure they have the
right version.
* Prefer ELF files for Verilator simulations. This makes it easier to
use existing ELF files from another software build system.
Fixes #1019
> Clarifications to the README of the simple system

- rtl/ibex_core.sv
- rtl/ibex_counter.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_id_stage.sv
Fix some of the warnings seen in the nighly lint report at https://reports.opentitan.org/hw/ip/rv_core_ibex/lint/ascentlint/latest/results.html. 
I didn't even attempt to do this systematically, just a couple drive-by ones.
> Fix some AscentLint warnings

- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
Hey!
Enum should be assignment only by enum type. LRM1800-2017 6.19.4: `A cast shall be required for an expression that is assigned to an enum variable where the type of the expression is not equivalent to the enumeration type of the variable.`
> correct wrong assignment to enum

- README.md
- examples/sw/benchmarks/README.md
- examples/sw/benchmarks/coremark/ibex/core_portme.mak
Felt the README should reflect the numbers actually achieved (as `SpecBranch` reduces performance for the PMP enabled config). Also felt we should show the best results achievable so added ISA configurability to the coremark build as different configs get better results with different ISA strings.
> Coremark updates

- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_agent.core
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_agent_pkg.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_request_agent.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_request_driver.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_agent.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_driver.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_seq_lib.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_sequencer.sv
- dv/uvm/core_ibex/common/irq_agent/irq_agent_pkg.sv
- dv/uvm/core_ibex/common/irq_agent/irq_request_agent.sv
- dv/uvm/core_ibex/common/irq_agent/irq_request_driver.sv
- dv/uvm/core_ibex/env/core_ibex_env.sv
- dv/uvm/core_ibex/env/core_ibex_vseqr.sv
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/tests/core_ibex_vseq.sv
This PR modifies the Ibex DV environment to match OpenTitan terminology
standards of using host/device. These changes are purely aesthetic.
> [dv/ibex] Switch to request/response terminology

- rtl/ibex_decoder.sv
Previously, these bits were not checked when decoding `slli`, `srli` and `srai`, causing some illegal instruction encodings not to trigger an illegal instructions exception.
This resolves lowRISC/Ibex#1018.
> [rtl] Make sure decoder also checks bits 26 and 25 for slli, srli, srai

- dv/uvm/core_ibex/env/core_ibex_instr_monitor_if.sv
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
As pointed out by @tomroberts-lowrisc in #983, the current
implementation of riscv_debug_single_step_test cannot handle
single-stepping over instructions that change the PC.
This PR aims to introduce this functionality, utilizing the
new instr_monitor_if.
Now, if the core single-steps onto a branch/jump instruction, the
testbench will log the new target PC and compare it against the actual
target address stored in `dpc`.
"Normal" instructions are checked as usual by incrementing the
instruction's PC by either 2 or 4 (depending whether it is compressed)
and comparing that against `dpc`.
This test passes successfully when combined with the RTL patch in #1034.
> [dv/ibex] Enhance riscv_debug_single_step test

- dv/uvm/data/vcs/vcs.hjson
- dv/uvm/data/xcelium/xcelium.hjson
cov_report_page is used by dvsim's SimCfg.py to print a message to the
console with the path to the dashboard HTML page. Most of these
messages have the full path (useful for copy-pasting), but this one
didn't.
This is essentially a duplicate of OpenTitan PR 2934[1] (because we're
not able to vendor these files properly yet).
[1] https://github.com/lowRISC/opentitan/pull/2934
> [dvsim] Print a more helpful path to coverage dashboard

- dv/uvm/icache/doc/ibex_icache_dv_plan.md
- dv/uvm/icache/dv/Makefile
- dv/uvm/icache/dv/env/ibex_icache_scoreboard.sv
There's a long description in the second commit message, but it boils down to the fact that memory requests slightly "smear" across sequence boundaries, and the scoreboard needs to be a bit cleverer about tracking `mem_err_shift` (a parameter that controls the proportion of the address space that generates errors).
> Fix bug in ICache testbench with chained sequences

- dv/uvm/core_ibex/riscv_dv_extension/riscv_core_setting.sv
This PR updates the `implemented_csr` list in `riscv_core_setting.sv`
and adds the two custom CSRs `cpuctrl` and `secureseed` to the
`custom_csr` list. Both are for use by the riscv-dv generator.
This PR can only be merged after #1049 , which vendors in some updates to riscv-dv,
including basic support for custom CSRs.
> [dv/ibex] Update CSR listings

- rtl/ibex_cs_registers.sv
This is a modification of the additional "CLINTx" Interrupt Interface for the Pulpissimo µC.
The Interface is intended to work with the platform-level Interrupt Controller. This controller is managed via an APB-Interface and brings its own Interrupt Enable Mask. Therefore the miex register is redundant. Because the mask register is also never written by the PULP SDK the core does not react to an interrupt.
This modification goes hand in hand with some other modifications in the [pulp-rt](https://github.com/pulp-platform/pulp-rt/pull/36) and [pulp-configs](https://github.com/pulp-platform/pulp-configs/pull/12) Repositories.
> Pulpissimo interrupt fix

- examples/sw/simple_system/pa_test/README.md
I added README.md in `examples/sw/simple_system/pa_test`.I described how to build the simulator and software, how to run the simulator.  Please tell me if my English is wrong.
> Add README.md for pointer authentication test

- examples/fpga/artya7/top_artya7.core
- ibex_core.core
This PR makes sure that whenever Vivado is used, the Verilog define `FPGA_XILINX` is set. This define can be used to enable Xilinx specific pragmas in the RTL code. It is currently used to implement the performance counters with DSP slices (incl. integrated output registers for counter widths <= 32) which helps to save logic resources and FFs (e.g. -7% and -15% when using 10 32-bit counters).
Previously, we had to set this parameter in every single top-level .core file using Ibex.
> Set `FPGA_XILINX` define whenever Vivado is used

- rtl/ibex_cs_registers.sv
Updates the write enable for `pmpaddr[i]` CSRs to deny writes if
`pmpcfg[i+1].lock == 1` and `pmpcfg[i+1].mode == TOR`, as per the
spec.
Relates to #1044.
> [ibex/rtl] Fix pmpaddr write enable signal

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/pygen/pygen_src/isa/riscv_instr.py
- vendor/google_riscv-dv/pygen/pygen_src/isa/riscv_instr_cov.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_asm_program_gen.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_gen_config.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_pkg.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_stream.py
- vendor/google_riscv-dv/pygen/pygen_src/target/rv32i/riscv_core_setting.py
- vendor/google_riscv-dv/pygen/pygen_src/test/riscv_instr_cov_test.py
- vendor/google_riscv-dv/src/isa/riscv_vector_instr.sv
- vendor/google_riscv-dv/src/isa/rv32v_instr.sv
- vendor/google_riscv-dv/src/riscv_amo_instr_lib.sv
- vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
- vendor/google_riscv-dv/src/riscv_illegal_instr.sv
- vendor/google_riscv-dv/src/riscv_instr_pkg.sv
- vendor/google_riscv-dv/src/riscv_load_store_instr_lib.sv
- vendor/google_riscv-dv/src/riscv_pmp_cfg.sv
- vendor/google_riscv-dv/src/riscv_privil_reg.sv
- vendor/google_riscv-dv/target/rv64gcv/testlist.yaml
dv to revision 61755c001bec0433fb69458f74d95476d2101cf3
* Adds new PMP directed sequence. (Udi Jonnalagadda)
* Fix typo (aneels3)
* Add gpr_c constraint (aneels3)
* Corrections of a code formatting. (Dariusz Stachanczyk)
* Modify asm, config and pkg files. (aneels3)
* fix riscv_privil_reg compile error (google/riscv-dv#666) (udinator)
* Added methods to the coverage test file (Hodjat Asghari Esfeden)
* Constraints should contain only intergral types - fix added for a
string variable used in nfields_c constraint. (Dariusz Stachanczyk)
* Minor fixes on coverage test (Hodjat Asghari Esfeden)
* fix pmpcfg csr definitions (Udi Jonnalagadda)
* Pygen: minor fix (danghai)
* Pre_sampling extension (Hodjat Asghari Esfeden)
* Fix …
> Update google_riscv-dv to google/riscv-dv@61755c0

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
This PR adds a new riscv-dv option `enable_write_pmp_csr=1` to each of the
tests in the existing PMP test suite.
This will enable the core to execute a directed test sequence to write
random values to each `pmpaddr` and `pmpcfg` CSR in order to explicitly test write
accessibility and spec compliance.
The original values stored in these CSRs are restored afterwards.
Note: This patch has exposed what looks like a bug in OVPsim,
for the time being please run all PMP tests with Spike.
> [ibex/dv] Update Ibex PMP tests

- README.md
- doc/introduction.rst
- syn/README.md
- syn/rtl/latch_map.v
- syn/rtl/prim_clock_gating.v
- syn/syn_yosys.sh
- syn/tcl/lr_synth_flow_var_setup.tcl
- syn/tcl/sta_utils.tcl
- syn/tcl/yosys_run_synth.tcl
- Add a technology map for latches (only works with nandgate45 library
at the moment)
- Add a real latch-based clock gating cell
- Update timing path reporting to differentiate between register and
latch paths
- Update summary results in README to reflect the latch-based numbers,
plus add numbers for a micro-riscy-style (RV32EC) config
> [syn] Use latch-based register file in yosys

- dv/uvm/core_ibex/riscv_dv_extension/csr_description.yaml
This patch does a few things:
- Fixes some yaml syntax errors by deleting the appropriate `-` characters to align with format of all other entries
- Temporarily changes type of all `cpuctrl` fields to read-only, as we do not enable the SecureIbex parameter in Ibex regressions yet to turn on all security features (and add a TODO item to do so)
- Changes type of `secureseed` to read-only, as according to the [Ibex CSR spec](https://ibex-core.readthedocs.io/en/latest/cs_registers.html#security-feature-seed-register-secureseed), "Seed values are not actually stored in a register and so reads to this register will always return zero"
> [ibex] Update CSR description of cpuctrl/secureseed

- rtl/ibex_controller.sv
- rtl/ibex_id_stage.sv
This signal aimed to ensure loads/stores completed succesfully when an
interrupt or debug request appeared at the same time they were being
executed when the writeback stage is present. However other stall logic
suffices for this purpose (debug/interrupt will wait for instruction to
unstall in ID/EX which only happens once request has been sent out, then
first instruction of debug/interrupt handler will stall until load/store
response has been seen based on the generic stall logic for lsu requests
in the writeback stage).
With this signal in place debug single stepping was broken around loads
and stores.
Fixes #1029
This half undoes the fix from this PR: https://github.com/lowRISC/ibex/pull/928 which was in response to this OT issue: https://github.com/lowRISC/opentitan/issues/2405
I'm …
> [rtl] remove lsu_req_in_id signal

- dv/uvm/core_ibex/riscv_dv_extension/riscvOVPsim.ic
This patch updates the OVPsim config file to use a 34-bit address space, as per discussion in https://github.com/riscv/riscv-ovpsim/issues/15.
Needed to resolve bugs in PMP tests that are popping up due to OVPsim currently only being configured for a 32-bit address space (PMP uses a 34-bit space).
> [ibex/dv] Update OVPsim to use 34-bit address range

- dv/uvm/core_ibex/ibex_dv.f
This patch updates the Ibex environment's dependency on the old top_pkg
to now depend on bus_params_pkg.
> [ibex/dv] Add dependency on bus_params_pkg

- azure-pipelines.yml
This update also switches from GCC 9.2 to GCC 10 experimental, see
https://github.com/lowRISC/lowrisc-toolchains/releases/tag/20200626-1
for more information about the toolchain builds.
> Use a RV32IMCB toolchain in CI

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/pygen/pygen_src/isa/riscv_cov_instr.py
- vendor/google_riscv-dv/pygen/pygen_src/isa/riscv_instr.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_asm_program_gen.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_defines.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_directed_instr_lib.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_cover_group.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_gen_config.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_pkg.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_sequence.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_stream.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_pseudo_instr.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_utils.py
- vendor/google_riscv-dv/pygen/pygen_src/test/riscv_instr_base_test.py
- vendor/google_riscv-dv/pygen/pygen_src/test/riscv_instr_cov_test.py
- vendor/google_riscv-dv/scripts/gen_csr_test.py
- vendor/google_riscv-dv/src/isa/riscv_amo_instr.sv
dv to revision 2e5251846efb5fa42882a2b6b571ef8693e8cd60
* Remove f strings for Python 3.5-compatibility (Philipp Wagner)
* Fix start-end pair mismatch in asm file (aneels3)
* Fix AMO instruction constraint issue (google/riscv-dv#682) (taoliug)
* - Adds support for the coverage report visualization (pyucis-viewer)
- Adds CSR, opcode, rv32i_misc, and mepc_alignment covergroups
(Hodjat Asghari Esfeden)
* fix Todo of directed_lib (aneels3)
* Added avail_regs_c constraint (ShraddhaDevaiya)
* Fix factory method implementation (aneels3)
* Add directed instr (aneels3)
* fix label issue (aneels3)
* fix randomization issue (aneels3)
* Fix typo (aneels3)
* add riscv_pseudo_instr (aneels3)
* add value_plusargs functionality …
> Update google_riscv-dv to google/riscv-dv@2e52518

- azure-pipelines.yml
- ci/azp-private.yml
- ci/install-build-deps.sh
- ci/vars.yml
- ci/vars_to_logging_cmd.py
Add necessary configuration to be able to run RISC-V DV-based UVM regressions in CI. Due to licensing concerns these runs won't be publicly available. We therefore use the same setup as we do in OpenTitan, and add these runs as a second pipeline. The pipeline configuration and detailed results will only be visible to the core team, success/failure status will be available to everybody in the GitHub pull request view.
This PR is therefore mostly refactoring, the job configuration itself is in a separate repository.
> Add UVM regression runs in private CI

- rtl/ibex_if_stage.sv
- The core does not rely on instr_err_i being always valid, and most bus
protocols don't support that
> [rtl] Remove outdated assertion

- ci/install-build-deps.sh
There's a long and painful discussion on the setuptools issues
list (I count 9 issues raised the day after the release). This is all
to do with how Debian/Ubuntu installs stuff with pip.
There's an "official" workaround that involves setting things in your
environment, but that looks a bit fiddly with the Azure pipelines
stuff and this has been such a disaster that I'm pretty certain the
setuptools maintainers will release something more sensible soon.
See e.g.
https://github.com/pypa/setuptools/issues/2350#issuecomment-683512526
for a careful description of what's going on.
> [ci] Force setuptools not to use version 50.0.0 for now

- formal/icache/ibex_icache_fpv.core
- formal/icache/run.sby.j2
The PR that I pushed up to add sby support to
Edalize (https://github.com/olofk/edalize/pull/173) ended up with a
different input format from the one it started with.
That's now merged into master, so this patch updates the Ibex code to
match the final syntax.
> Port ICache formal core file to final Edalize design

- dv/uvm/icache/dv/env/seq_lib/ibex_icache_caching_vseq.sv
- dv/uvm/icache/dv/env/seq_lib/ibex_icache_oldval_vseq.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/seq_lib/ibex_icache_core_base_seq.sv
Some sequences run in "no invalidate" mode. Unfortunately, sometimes
we *have* to invalidate, either because we have a stale seed, or
because we're at the start of a sequence.
It turns out that "no invalidate" is a soft requirement, so we can
weaken it here. This patch also renames the flag to
"avoid_invalidation" to make it clear that this is allowed to be
violated occasionally.
Closes #1101.
> Fix "no invalidate" logic in ICache sequence

- rtl/ibex_controller.sv
- If there is a request to enter debug mode (either due to a halt
request or single stepping mode) on the same cycle as an EBREAK
instruction, continue with the EBREAK and capture the ID PC rather
than the IF PC.
- relates to #1106
> [rtl] Fix debug step over EBREAK issue

- Makefile
- util/Makefile
The other scripts in the directory don't have typing annotations.
> In util, restrict mypy linting to sv2v_in_place.py

- examples/sw/simple_system/common/simple_system_common.c
- rtl/ibex_tracer.sv
At some point in the future, the version of binutils we're using, and
the released version of LLVM, will coincide to use the correct name. In
the meantime, this change just uses the number which is supported by
both compilers.
This is, as I understand it, the only stumbling block to compiling the
in-repo C benchmark code with both GCC and LLVM. Being able to do so
would make it much easier for us to do comparisons on the benchmarks for
both compilers.
---
I'm not sure if the changes to `ibex_tracer.sv` are correct, it seems `0x321` and `0x322` are not defined in the privileged spec v1.11, and nor are they defined in https://ibex-core.readthedocs.io/en/latest/cs_registers.html
@luismarques are there other stumbling blocks to running ibex simple system with LLVM? I think this is the only …
> [simple_system] Update CSR Access for LLVM and GCC

- examples/sw/simple_system/common/link.ld
Adding the "small" sections to the example linker script. This ensures
that all sections of memory needing to be zeroed are captured.
Fixes #1092
> [simple-system] Add missing linker sections

- examples/fpga/artya7/README.md
The documentation restructure in #1119 resulted in a new URL for the
documentation on Ibex system examples. This commit updates the in-tree
link to reference that new URL.
> [doc] Fix broken link to examples description

- rtl/ibex_decoder.sv
- Without the B extension, a gorci instruction should decode as an
illegal instruction.
- Relates to #1129
> [rtl] Fix missing else branch in decoder

- doc/02_user/integration.rst
- doc/03_reference/security.rst
- rtl/ibex_core.sv
- rtl/ibex_fetch_fifo.sv
- rtl/ibex_if_stage.sv
- Document that SecureIbex cannot be used without a multiplier and add
an assertion in the rtl. This fixes #1080.
- Move the PC checking hardware onto its own parameter to match all the
other individual security features.
- Make the PC increment behavior more sensible on fetch errors (and make
it match the icache behavior). Factor this into the PC increment check
to prevent false triggering, fixes #1094.
- Stop the PC mismatch checker firing on dummy instructions, fixes
#1095.
> [rtl] Various security feature bugfixes

- dv/uvm/core_ibex/ibex_dv.f
- ibex_core.core
- lint/verilator_waiver.vlt
- rtl/ibex_cs_registers.sv
- rtl/ibex_csr.sv
This PR is an example to discuss how we might move the CSRs to separate modules. The objective is mostly to allow parameterized addition of shadow copies, but there should be some other side benefits (clock gating, tidy-up etc.).
* I have only converted two CSRs here as an example to gather feedback.
* There is more scope for tidy-up and rationalization of the write muxing etc. once all CSRs are converted.
* There is also the option of making the CSR module type-parametrizable, rather than casting at the module boundaries. It's not currently supported by sv2v but I'll file that as an issue separately.
> Instantiate CSR module

- rtl/ibex_cs_registers.sv
- This field is read-only to software, and so should retain its previous
value on a write. This fixes #1134.
> [rtl] Fix illegal write to DCSR cause field

- doc/03_reference/verification.rst
The icache verification is complete until new bugs are found, let's mark
it as such in the docs.
> [doc] Mark icache verification as "done for now"

- dv/uvm/core_ibex/sim.py
Currently the Ibex run scripts return 0 no matter what the test result
is.
To get Ibex sims correctly integrated into CI, the Makefile needs to
return 1 upon seeing a log comparison failure to indicate an error.
> [ibex/dv] return non-zero exit code upon failure

- dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
The RISC-V compliance toplevel needs to pass through the instruction
cache-related parameters, which are set by the ibex configuration
script.
> Pass through ICache-related parameters in compliance test

- ci/ibex-rtl-ci-steps.yml
Turns out, just having a nice error message with the correct tool
invocation isn't enough: you actually need to call the tool with the
arguments you document.
Let's do that and actually run Verilator lint and Verible lint, and not
just Verilator lint twice.
> Enable Verible lint

- lint/verilator_waiver.vlt
- rtl/ibex_alu.sv
- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_decoder.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_multdiv_fast.sv
- rtl/ibex_register_file_ff.sv
- rtl/ibex_register_file_fpga.sv
- Move various unused signal fixes from the waiver file to the rtl, so
that all tools can pick them up.
- Fix some oversize line issues.
- Fix some signed / unsigned casting issues.
- Remove some extraneous semicolons.
> [rtl] Various small lint fixes

- azure-pipelines.yml
- rtl/ibex_if_stage.sv
We now have an Ibex configuration
experimental-maxperf-pmp-bmfull-icache, which also enables the
instruction cache. Enable this configuration in public CI, which makes
it run the lint and RISC-V compliance jobs.
> Enable configuration with Icache in public CI

- azure-pipelines.yml
Private CI has a separate list of ibex configurations it runs (there's
no sane way around that). Add a note to the pipeline configuration to
hopefully remember to keep them in sync, if that's desired (they don't
*have to* be in sync).
> [ci] Add a comment on private CI

- dv/uvm/core_ibex/sim.py
Increase the RTL simulation timeout when not in LSF-mode from 5 to 10
minutes.
Could potentially solve #1154.
> [dv] Increase simulation timeout

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
For some bizarre reason VCS includes DPI code that has smart
quotes (yes, smart quotes) around some #error macros. Recent GCC
versions (g++ >= 10.2) have got proper support for UTF-8, which is
nice but makes them choke on these input files.
Passing -fno-extended-identifiers tells GCC to go back to the days of
yore and pretend that everything is ASCII, and all is well again!
Obviously the right fix is not to embed smart quotes in C++ code, but
that's not something in our control :-(
> Pass -fno-extended-identifiers to VCS

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/docs/source/appendix.rst
- vendor/google_riscv-dv/docs/source/end_to_end_simulation.rst
- vendor/google_riscv-dv/pygen/pygen_src/isa/riscv_floating_point_instr.py
- vendor/google_riscv-dv/pygen/pygen_src/isa/riscv_instr.py
- vendor/google_riscv-dv/pygen/pygen_src/isa/rv32d_instr.py
- vendor/google_riscv-dv/pygen/pygen_src/isa/rv32dc_instr.py
- vendor/google_riscv-dv/pygen/pygen_src/isa/rv32f_instr.py
- vendor/google_riscv-dv/pygen/pygen_src/isa/rv32fc_instr.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_asm_program_gen.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_defines.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_gen_config.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_privil_reg.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_privileged_common_seq.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_reg.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_utils.py
- vendor/google_riscv-dv/pygen/pygen_src/target/rv32imfdc/riscvOVPsim.ic
- vendor/google_riscv-dv/pygen/pygen_src/target/rv32imfdc/riscv_core_setting.py
- vendor/google_riscv-dv/pygen/pygen_src/test/riscv_instr_base_test.py
- vendor/google_riscv-dv/run.py
- vendor/google_riscv-dv/src/isa/riscv_compressed_instr.sv
- vendor/google_riscv-dv/src/riscv_pseudo_instr.sv
- vendor/google_riscv-dv/target/rv32imfdc/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv32imfdc/testlist.yaml
- vendor/google_riscv-dv/yaml/simulator.yaml
dv to revision 3467c3777cb428b2e30b30b7f895a8fd73873d4f
* add VCS compile option for unicode (Udi Jonnalagadda)
* Add missing license header (aneels3)
* [Docs] Fix broken links and typos (db434)
* Add support for RV32D (ishita71)
* Fix google/riscv-dv#733 (aneels3)
* Fix Spike Issue (aneels3)
* add riscv_reg and riscv_privil_reg (pvipsyash)
* fix target issue for foating point (pvipsyash)
* add rv32fc target (pvipsyash)
* add riscv_floating_point_instr (pvipsyash)
* Add defines for floating point instructions (ShraddhaDevaiya)
> Update google_riscv-dv to google/riscv-dv@3467c37

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
Similar to simulator.yaml, this changes has to be applied to rtl_simulation as well to avoid weird compilation errors.
> Add VCS compile option for unicode

- dv/uvm/core_ibex/env/core_ibex_instr_monitor_if.sv
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
Testbench computation of next PC when single stepping was broken. A
branch may stall before branch_set is asserted and this wasn't being
taken into account. Where the branch target ALU is present branch_set
can be set on the first cycle of the branch so this bug wasn't apparent.
Even with the branch target ALU the branch may stall awaiting the result
of a load when the writeback stage is present.
To make matters more complicated for a jump the PC being jumped to is
only available when jump_set is asserted which happens whilst the jump
instruction is stalling.
This alters the riscv_debug_single_step_test so when waiting for a
single step it looks for either a branch_set or jump_set signal being
asserted. Otherwise it waits until the instruction has unstalled. This
should give correct …
> [dv] Fix riscv_debug_single_step_test

- rtl/ibex_pmp.sv
Generate correct masks for NAPOT range addresses covering the entire granule. When PMPGranularity > 0, then a NAPOT range can span the whole granule, which requires the next-lowest bit (i.e. highest bit that is not part of the granule) to be 0. Fixes #1178
> [rtl] Fix NAPOT address matching (#1178)

- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
This PR slightly modifies how we wait for the end of an Ibex sim.
Currently we wait on dut_vif.dut_cb.ecall, which will be delayed by a
cycle as it is in a clocking block.
However we should end the test immediately when an ecall is seen, so we
should rather wait on dut_vif.ecall instead to be more accurate and
prevent potential race conditions caused by irq/debug stimulus being
sent on the same cycle as an ecall instruction is executed by the core.
Addresses #1177 and #1159.
> [ibex/dv] Modify EOT ecall check

- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_monitor.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_driver.sv
- dv/uvm/core_ibex/common/irq_agent/irq_monitor.sv
- dv/uvm/core_ibex/common/irq_agent/irq_request_driver.sv
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
This makes changes to support Cadence Xcelium 20.09.001.
Cadence recommends that disabling forks should be done using a *"disable fork;"* statement, not the *"disable fork_process_label;"* construct.
The *"disable fork_process_label"* construct for forks is not defined in the IEEE Std 1800-2017 LRM. See section 9.6.2 of the LRM (2017).
For a more detailed explanation, please see the description from my colleague in Issue #1174.
In many cases, Xcelium will ignore a disable statement if it is not in the *"disable fork;"* form.
This causes problems in many tests, most notably in the riscv_reset_test.
Processes not being disabled when reset is asserted cause not just test failures, but the entire regression to crash.
Most changes here are simple substitutes of *"disable fork;"* where …
> [dv] Fixes for disabling forks, for Cadence Xcelium

- rtl/ibex_core.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_wb_stage.sv
- Make sure performance counters only count retired, non-trapping
instructions excluding ebrk/ecall
- Rewire some signalling through the writeback stage to allow
instruction retire to be signalled from one place
- Relates to #1132
> [rtl] Fix performance counter bug

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
dv to revision 3da32bbf6080d3bf252a7f71c5e3a32ea4924e49
* fix location of custom CSR setup (google/riscv-dv#747) (udinator)
> Update google_riscv-dv to google/riscv-dv@3da32bb

- util/ibex_config.py
We need to check that the output type is actually supplied, otherwise
we spit out a rather mysterious error a few lines later.
> Improve ibex_config command line handling with missing output_fn

- rtl/ibex_core_tracing.sv
Hi @vogelpi,
When using ibex_core_tracing in PULP, the irq_x_i lines were in an X state due to this bug.
> bugfix tracer irq_x_i

- azure-pipelines.yml
- ci/install-build-deps.sh
Follow OpenTitan's lead and move to Ubuntu 18.04 for the CI runner. Ubuntu 16.04 comes with Python 3.5, which is EOL and causes more and more issues.
Specificially, this update is triggered by rst2pdf not being installable with pip's new dependency resolver (see also https://github.com/rst2pdf/rst2pdf/issues/489#issuecomment-736652808 for a detailed analysis).
> Update CI to use Ubuntu 18.04

- doc/03_reference/icache.rst
- dv/uvm/icache/dv/env/seq_lib/ibex_icache_base_vseq.sv
- dv/uvm/icache/dv/env/seq_lib/ibex_icache_combo_vseq.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_driver.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_protocol_checker.sv
- dv/uvm/icache/dv/ibex_icache_core_agent/seq_lib/ibex_icache_core_base_seq.sv
- dv/uvm/icache/dv/tb/tb.sv
- formal/icache/formal_tb.sv
- formal/icache/formal_tb_frag.svh
- rtl/ibex_icache.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_prefetch_buffer.sv
Two commits in this PR -
The first is some minor performance updates to the icache when running in cache disabled mode, the second adds the branch prediction signals and deals with them in the same way as the prefetch buffer.
> Add branch prediction feature to icache

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/question.md
Add two issue templates to the GitHub project: one for questions, and
one for reporting bugs. These templates are not mandatory, users can
freely change them, or get a blank issue template instead.
To avoid having too much description/example text in the final issue the
instructions are written in HTML comments (which is not beautiful, but
should do the trick and seen commonly in projects).
> Add issue templates to GitHub project

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/question.md
The GitHub UI shows apparently the name of the template at
https://github.com/lowRISC/ibex/issues/new/choose, which I thought was
just an internal identifier. Use the longer-form version there as well.
> Use more descriptive issue template names

- rtl/ibex_controller.sv
Assert not correctly understood by some versions of xcelium.
A single character added line in rtl/ibex_controller.sv .
> This is modification request for xcelium

- dv/uvm/icache/dv/Makefile
This reverts commit 31a18ad: the problem that it was working around
was fixed in OpenTitan with commit 249a544, vendored into Ibex as
b1daf9e.
> Revert "Clear MAKEFLAGS when running dvsim.py"

- ci/install-build-deps.sh
In the past, we did explicitly install pyyaml through PIP to get a
version newer than the one provided in Ubuntu 18.04. Since then we
changed the calling code to not rely on newer pyyaml features and
are thus able to rely on an older version of pyyaml.
The distro-provided version of pyyaml is built with C bindings, which
are significantly faster than the pip-installed version, which uses a
pure Python-implementation of the parser/dumper.
> CI: The distro-provided pyyaml package is enough

- dv/cs_registers/tb/tb_cs_registers.sv
- dv/cs_registers/tb_cs_registers.core
- rtl/ibex_core.sv
- rtl/ibex_cs_registers.sv
I am not 100% sure if this should be done as the B extension bit is still "Tentatively reserved for Bit-Manipulation extension".
As I made changes to the testbench I checked it with Verilator and added some minor changes to it as well into this PR.
> Add misa b extension

- rtl/ibex_pmp.sv
This bug was noted in https://github.com/lowRISC/ibex/pull/1179 and a fix proposed by @byllgrim which I have used in this PR.
> [rtl] Fix PMP NAPOT matching for 0 PMPGranularity

- syn/README.md
- syn/tcl/sta_utils.tcl
This fixes a bug where .csv.rpt files weren't being generated properly.
OpenSTA was outputting a simple 'Q' or 'D' for start and end path points
where the full instance name was required (which is then fed to yosys to
translate to a human readable name). The issue was in the `timing_report`
proc in syn/tcl/sta_utils.tcl which needed to request the full name of
the start and end points.
The syn README is updated to note which tool versions have been used to
test the flow.
Fixes #1193
> [syn] Fix timing reports in synthesis flow

- rtl/ibex_tracer_pkg.sv
This bug was originally found by @micprog.
> [rtl] Fix encoding for ORC16/REV16 instructions in tracer package

- rtl/ibex_tracer_pkg.sv
This PR contains fixes overlapping instruction encodings for the bitmanip extension in the tracer package.
@micprog could you please check that this PR resolves the remaining warning around FSRI?
> [rtl] Fix instruction encodings in tracer package

- src_files.yml
@vogelpi There is a small error left from my previous commits, this minor bugfix ensures compatibility with IPApproX.
> bugfix src_files naming

- rtl/ibex_cs_registers.sv
`DbgHwBreakNum - 1` is an int, so generates a warning if it's assigned
to `tselect_d` (of type `logic [DbgHwNumLen-1:0]`). Explicitly generate
the value we need as a localparam.
This lint warning doesn't appear by default in the Ibex repository,
because `DbgTriggerEn` is disabled. It does, however, appear in
OpenTitan because we enable it there.
> [rtl] Fix lint warning when DbgTriggerEn parameter is set

- rtl/ibex_cs_registers.sv
The previous change was wrong: it was trying to define a signal with
`DbgHwNumLen` bits that contained `DbgHwBreakNum - 1`. Unfortunately, `'1`
is *not* the same as a zero-extended version of `1'b1`.
> [rtl] Fix lint "fix" with DbgTriggerEn

- examples/simple_system/ibex_simple_system.core
- lint/verilator_waiver.vlt
The `-Wwarn-IMPERFECTSCH` flag is suggested in the Verilator docs (to
help spot if we get a clock gating hint wrong). The waiver is no
longer needed because we now add the relevant hint in the
RTL (vendored in `prim_generic_clock_gating.sv` from OpenTitan).
Closes #212.
> [verilator] Remove clock gating waiver and add extra warning

- syn/syn_yosys.sh
With the introduction of dv_fcov_macros.svh we need to add it as an
included path for sv2v.
> [syn] Add missing include path

- doc/03_reference/verification.rst
This should match what's going on a bit more accurately. The link to
OVPsim now points at the (free of cost) commercial tool: riscv-ovpsim
doesn't support the bitmanip specification that we're using at the
moment.
Fixes #1248.
> [doc] Update dependency descriptions for Spike/OVPsim

- dv/uvm/core_ibex/ibex_dv.f
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
I wonder whether we could use some form of quoting to allow
"32'h8000_0000" to get through Riviera's TCL, but we don't have any
way to test, so let's go with the easy option.
Fixes #1224.
> Specify boot address in hex to avoid 32-bit signed overflow

- dv/uvm/core_ibex/env/core_ibex_dut_probe_if.sv
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
This silences VCS warnings about the DUT having missing port
connections. It doesn't add any actual testing for these signals.
The patch also re-orders the signals to match the order in
`ibex_core_tracing.sv`, to make it easier to spot what's going on by
eye.
> [dv] Wire up alerts to dut probe interface

- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
The previous code contained
wait (dut_vif.dut_cb.priv_mode === select_mode())
and VCS warns that this `wait` block will only trigger on changes to
explicit arguments. That is, if the `in_nested_trap` field changes, so
the return value of the `select_mode()` method would change to match
priv_mode, the `wait` statement won't finish.
This patch explicitly stores a snapshot of the value of `select_mode()`
just before the wait line. I think this is the intended behaviour, and
will no longer trigger warnings from VCS.
@udinator: Have I understood this code correctly? This change isn't right if we expect `in_nested_trap` to change "behind our backs".
> [dv] Be explicit about the target priv_mode in wait_ret test

- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
In UVM 1.2, at least, `uvm_component` (a base class of
`core_ibex_base_test`) still has a method called run(). Ironically, this
has been renamed to `run_phase` to avoid conflicting with user names,
but the old-style phase names still exist at the moment.
Rename our copy of the phase object to `cur_run_phase`, which doesn't
conflict. Also, set it back to null at the end of the `run_phase()`
task. We shouldn't ever use it afterwards, and it's probably a good
idea to explode with a null object error if we do.
> [dv] Rename stored copy of run phase

- doc/conf.py
We were using the old html_context which has been deprecated
for a while. This PR switches to html_css_files instead.
See sphinx-doc/sphinx#8885 for more information.
> Fix deprecated sphinx html_context usage in conf.py

- dv/verilator/pcount/cpp/ibex_pcounts.cc
- examples/simple_system/rtl/ibex_simple_system.sv
It's probably clearer if this 64-bit counter is treated as a uint64_t,
not an int64_t (the code using it downstream expects non-negative
values).
Fixes #1282.
> [simple_system] Fix type for mhpmcounter_get

- rtl/ibex_controller.sv
- rtl/ibex_id_stage.sv
Prior to this change Ibex had multiple feedthrough paths from the data
memory interface to the instruction memory interface. This existed
because Ibex would hold off doing a instruction fetch for a jump or
branch if there was a outstanding memory request. It would wait for the
response to be available so either the jump or branch would occur or an
exception was taken.
With this change the branch or jump will speculatively begin the
instruction fetch whilst there is an outstanding memory request. Should
an exception result from the memory request the fetch will be discarded
and the exception taken as normal.
An alternative fix would not factor the data error response
(data_err_i) directly into the controller logic for branches and jumps.
With this option new stall cycles would be …
> [rtl] Remove paths between dmem and imem signals

- examples/sw/simple_system/common/common.mk
Anyone who needs to disassemble their generated ELF can probably just
call objdump directly and the precise set of flags have already
confused at least one potential contributor[1].
We're keeping the canned objdump command for "engineers that know
where to look" because some have said they find it useful.
[1] https://github.com/lowRISC/ibex/issues/1263
Fixes #1263 (marking as a fix because the question becomes moot!)
> Don't automatically generate disassembly in the example Makefile

- dv/uvm/core_ibex/Makefile
- dv/uvm/core_ibex/sim.py
Currently, the `cov` step in the DV Makefile will only merge coverage
databases emitted directly from Ibex simulations, and will not pick up
any coverage databases generated by the RISCV-DV functional coverage
flow.
This PR updates the `gen_cov()` function in `sim.py` to recursively
search for any generated coverage directories and then merges them all.
Resultant coverage reports include all code coverage, Ibex functional
coverage, and RISCV-DV functional coverage.
The coverage-related targets in the Makefile have also been renamed to
improve clarity.
> [dv/ibex] update how coverage is merged

- dv/uvm/core_ibex/Makefile
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/sim.py
- util/ibex_config.py
This PR adds functionality to filter out tests during regressions for a
particular config.
e.g. if a full regression is kicked off using the `small` config, we
don't want to attempt to run any PMP and bitmanip tests as the RTL
parameter-set will not support it.
To do this, a new YAML field called `rtl_params` is added to relevant
test entries, to indicate what parameters (if any) are required to be
able to run the particular test, along with the required value of said
parameters.
`sim.py` will then parse this field (if it exists), and using
information from `ibex_configs.yaml` pertaining to the current config,
will remove tests from being run on-the-fly.
This also gives us the convenient side effect of not having to re-run
instruction generation if there is a parameter/config mismatch, we …
> [dv/ibex] filter out tests on a per-config basis

- rtl/ibex_icache.sv
Changes the ECC granularity in the data RAMs from 64bit to 32bit. This
is to align with an upcoming change in bus ECC. Relates to
lowRISC/opentitan#5450
> [rtl/icache] Switch ECC granularity to 32bits

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
this test is arbitrarily failing in regressions on a Spike timeout,
temporarily remove this to avoid blocking.
@udinator to fix this in the near future.
> [ci/ibex] temporarily remove pmp_full_random_test

- doc/03_reference/security.rst
Bullet points now appear properly for the last paragraph under the Data Independent Timing section in `security.rst`.
> Fix spacing for bullet points to appear

- doc/03_reference/cs_registers.rst
- dv/cs_registers/model/register_model.cc
- dv/cs_registers/reg_driver/csr_listing.def
- rtl/ibex_cs_registers.sv
- rtl/ibex_pkg.sv
This is the top 32 bits of MSECCFG. It currently has no specified bits
so reads as 0 and ignores writes.
Fixes #1297
> [rtl] Add MSECCFGH CSR

- dv/uvm/icache/data/ibex_icache_testplan.hjson
With this change, we no longer use "sanity" in non-vendored code.
> Avoid encumbered name in ibex_icache_testplan.hjson

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/.github/workflows/metrics-regress.yml
- vendor/google_riscv-dv/.metrics.json
- vendor/google_riscv-dv/pygen/pygen_src/isa/riscv_compressed_instr.py
- vendor/google_riscv-dv/pygen/pygen_src/isa/riscv_instr.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_asm_program_gen.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_data_page_gen.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_directed_instr_lib.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_illegal_instr.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_gen_config.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_pkg.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_sequence.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_stream.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_load_store_instr_lib.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_signature_pkg.py
- vendor/google_riscv-dv/pygen/pygen_src/riscv_utils.py
- vendor/google_riscv-dv/pygen/pygen_src/target/multi_harts/riscvOVPsim.ic
- vendor/google_riscv-dv/pygen/pygen_src/target/multi_harts/riscv_core_setting.py
- vendor/google_riscv-dv/pygen/pygen_src/target/rv32i/riscv_core_setting.py
- vendor/google_riscv-dv/pygen/pygen_src/test/riscv_instr_base_test.py
- vendor/google_riscv-dv/pygen/pygen_src/test/riscv_rand_instr_test.py
- vendor/google_riscv-dv/run.py
- vendor/google_riscv-dv/scripts/genMetricsList.py
- vendor/google_riscv-dv/scripts/metrics-regress.py
- vendor/google_riscv-dv/src/riscv_illegal_instr.sv
- vendor/google_riscv-dv/test/riscv_instr_cov_test.sv
- vendor/google_riscv-dv/yaml/iss.yaml
- vendor/google_riscv-dv/yaml/simulator.yaml
This updates the vendored riscv-dv, which should fix up the part of https://github.com/lowRISC/ibex/pull/1284 that we don't want to patch locally. Once this is merged, we can rebase that PR and hopefully that will be good to go.
dv to revision 59dcd8c813484eb6dcca67e7e36089fe772b9cc8
* Update scripts for Metrics CI regression:  bug fixes, change ISS to
spike in CI regression (Aimee Sutton)
* Add illegal and load store instruction (aneels3)
* Avoid generating hint instruction when RV32C is turned off
(google/riscv-dv#787) (taoliug)
* Fix illegal opcode issue in the cov_test (google/riscv-dv#786)
(taoliug)
* [questa] Remove -access=rwc from vlog command line arguments (Rupert
Swarbrick)
* [ci] temporarily disable CI flow …
> Update google_riscv-dv to google/riscv-dv@59dcd8c

- rtl/ibex_compressed_decoder.sv
This signal is used to gate several assertions related to unknown/invalid selector signals. We want to be sure to catch any X
values entering the compressed decoder and ultimately ID.
This is related to lowRISC/Ibex#540.
> [rtl] Add SVA to ensure valid_i in compressed decoder is known

- dv/uvm/core_ibex/riscv_dv_extension/ibex_log_to_trace_csv.py
- dv/uvm/core_ibex/sim.py
When the simulator terminates with an error code that is reported as a
test failure and the regression continues. Previously it would kill the
whole regression.
> [dv] Don't kill regression on sim error

- rtl/ibex_top.sv
- syn/tcl/yosys_run_synth.tcl
1. Missing prim_assert in ibex_top.sv (more of an rtl bug but only found
in running synthesis scripts)
2. Write out the pre-mapped netlist before mapping latches
Relates to #1335
> Fix a couple of synthesis bugs

- README.md
- doc/01_overview/index.rst
Since this part of the README was written the design moved on. Let's
update it. This update follows the text at https://ibex-core.readthedocs.io/en/latest/index.html.
I also removed the block diagram, since it is misleadingly showing only
the 2 stage design.
> Update README to match design

- dv/uvm/core_ibex/riscv_dv_extension/csr_description.yaml
The value of `misa` will change depending on whether M or B are enabled.
The presence and read values of other CSRs may also depend upon the Ibex
configuration. A fix is required to allow riscv_csr_test to deal with
different CSR descriptions for different Ibex configurations. For now
just comment out `misa` from the descriptions file to enable
riscv_csr_test to run on a wider range of configurations.
> [dv] Remove MISA from csr_description.yaml

- ibex_top.core
- rtl/ibex_top.sv
Certain synthesis tools like DC are very smart at optimizing away redundant logic.
Hence, we have to insert an optimization barrier at the IOs of the lockstep Ibex.
This is achieved by manually buffering each bit using `prim_buf`.
Our Xilinx and DC synthesis flows make sure that these buffers cannot be optimized
away using `keep` attributes (Vivado) and `size_only` constraints (DC).
> [lockstep] Introduce optimization barrier around lockstep Ibex

- dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
Hey!
In this PR I added cast to enum, because we can't assign non-enum to enum LRM 6.19.3
Signed-off-by: Dawid Zimonczyk <dawidz@aldec.com.pl>
> Add cast to enum

- doc/02_user/integration.rst
- dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- examples/fpga/artya7/rtl/top_artya7.sv
- examples/simple_system/rtl/ibex_simple_system.sv
- rtl/ibex_lockstep.sv
- rtl/ibex_top_tracing.sv
Better to have the tracing top consistent with the non-tracing top.
> [rtl] Wire scan_rst_ni through ibex_top_tracing

- rtl/ibex_tracer.sv
- rtl/ibex_tracer_pkg.sv
These go over the 100 character limit in our style guide (and will
cause Verible lint warnings when vendored into OpenTitan).
> [rtl] Break long lines in Ibex tracer

- rtl/ibex_cs_registers.sv
DbgTriggerEn has no impact on whether this is an illegal csr op.
Fixes #1379
> [rtl] Fix typo in MCOUNTEREN

- dv/uvm/core_ibex/Makefile
- dv/uvm/core_ibex/collect_results.py
- dv/uvm/core_ibex/compare.py
- dv/uvm/core_ibex/list_tests.py
- dv/uvm/core_ibex/sim.py
The interesting commit is the second last. Here's its message:
This patch teaches Make which tests we're actually running (via the
`list_tests.py` script), which means that we can compare the ISS and RTL
results in parallel rather than serially.
There's a bit of duplicated code (both `list_tests.py` and `sim.py`
currently contain the code to get a list of tests and then filter by
Ibex configuration), but this should go away with a later patch that
runs the RTL simulations in parallel in a similar way.
Note: This might seem a little silly: trace comparison takes way less
time than the RTL simulation! The point is that it's probably easier
to work "from the bottom" than to start by parallelising the
simulations themselves.
@GregAC: This is in draft because it probably clashes quite badly …
> Teach core_ibex testbench to run the comparison step in parallel

- dv/uvm/core_ibex/Makefile
- dv/uvm/core_ibex/compare.py
- dv/uvm/core_ibex/run_rtl.py
- dv/uvm/core_ibex/sim.py
- dv/uvm/core_ibex/sim_cmd.py
- dv/uvm/core_ibex/test_entry.py
This is a follow-up to #1372 and exposes the RTL simulation part of the run to Make so that it can run in parallel. I just tried it locally with `time make SEED=1 TEST=riscv_arithmetic_basic_test ITERATIONS=2 VERBOSE=1 -j2` and everything ran nicely.
> [core_ibex,dv] Allow running RTL simulations in parallel

- dv/uvm/core_ibex/collect_results.py
Commit 700f29b changed things so that details of the various tests
that ran ended up in separate files. This is nice (and important for
running things in parallel), but isn't massively helpful if you use
regr.log to understand what happened from a CI run!
This patch adds the logs again, splitting them up so that failing
tests come before passing ones (since you usually just care about the
failures).
> Append logs for tests to regr.log

- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
The test loops around waiting for the core to sleep then sending
interrupts to wake it. In some cases, the sequence sends an interrupt
that isn't enabled. It never gets back to try again with a new interrupt
since the test is waiting to see wfi first. This change removes that
requirement since it is redundant anyway (have to see wfi to sleep).
> [dv/uvm/core_ibex] Fix timeout issue in wfi tests

- dv/uvm/core_ibex/Makefile
- dv/uvm/core_ibex/collect_results.py
- dv/uvm/core_ibex/compare.py
- dv/uvm/core_ibex/test_run_result.py
- python-requirements.txt
Here's what the intermediate YAML files look like:
```
name:            riscv_arithmetic_basic_test
idx:             0
seed:            10547
binary:          out/seed-10547/instr_gen/asm_test/riscv_arithmetic_basic_test_0.o
uvm_log:         out/seed-10547/rtl_sim/riscv_arithmetic_basic_test.10547/sim.log
rtl_trace:       out/seed-10547/rtl_sim/riscv_arithmetic_basic_test.10547/trace_core_00000000.log
rtl_trace_csv:   out/seed-10547/rtl_sim/riscv_arithmetic_basic_test.10547/trace_core_00000000.csv
iss_trace:       out/seed-10547/instr_gen/spike_sim/riscv_arithmetic_basic_test.0.log
iss_trace_csv:   out/seed-10547/instr_gen/spike_sim/riscv_arithmetic_basic_test.0.csv
comparison_log:  
passed:          False
failure_message: |-
[FAILED]: Log processing failed: [Errno 2] No such file or …
```
> Ibex dv report format

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
We're already redirecting stdout to sim.log in run_rtl.py. Specifying
'`-l`' as well meant that VCS opened sim.log in a separate FD.
Suprisingly enough, this mostly worked, but not always! Just write
once :-)
Fixes #1390.
> [dv,core_ibex] Only write sim.log once

- examples/sw/led/Makefile
- examples/sw/simple_system/common/common.mk
This invocation would break:
make -C examples/sw/led/ CC=/opt/lowrisc-toolchain-gcc-rv32imc-20210412-1/bin/riscv32-unknown-elf-gcc 
because the "-gcc" occurence inside the directory name would also be replaced.
Fix by using pattern substitution.
Signed-off-by: Leon Woestenberg <leon@sidebranch.com>
> Fix toolchain substitution. Was broken for specific file paths.

- formal/riscv-formal/Makefile
No guarantees that this actually does anything useful, but at least
the Makefile works again.
> Get riscv-formal flow working again

- ci/vars.yml
Use the same dependencies as we use in OpenTitan to make it easier to
diagnose potential issues. No change in behavior expected.
> [ci] Update dependencies to match OpenTitan

- azure-pipelines.yml
The toplevel core file got renamed, but the experimental verible-format
CI job wasn't updated in sync. Fix that.
> Fix the verible-format CI job

- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- rtl/ibex_lockstep.sv
- rtl/ibex_top.sv
There are two patches here - one is a minor cleanup, the other adds a register slice on the outputs from the lockstep shadow core.
@tjaychen @eunchan The register slice is something we discussed a long time ago when some timing issues showed up in the shadow core. LMK if you think this is worth doing or not.
> [rtl] Minor lockstep-related updates

- rtl/ibex_load_store_unit.sv
Previously the raw incremented address was used which is the calculated
address + 4. This is confusing as it refers to a byte that wouldn't be
accessed (e.g. a lw at 0x8000009e which faults on the access to
0x8000000a0, would report an mtval of 0x8000000a2). With this change
mtval will refer to the first byte on the other half of the word
boundary the unaligned access crosses.
Relevant bits from the spec:
> If mtval is not hardwired to zero, then when a breakpoint, address-misaligned, access-fault, or page-
fault exception occurs on an instruction fetch, load, or store, mtval is written with the faulting
virtual address.
> For misaligned loads and stores that cause access-fault or page-fault exceptions, mtval will contain
the virtual address of the portion of the access that caused the …
> [rtl] Fix mtval for unaligned accesses

- .github/workflows/pr_lint_review.yml
- .github/workflows/pr_trigger.yml
This PR adds CI scripts that use [Verible Lint Action](https://github.com/chipsalliance/verible-linter-action)
to automatically review the changes in `.v` and `.sv` files.
You can see an example of how this works here:
https://github.com/antmicro/gha-playground/pull/20
In order to post comments, the action needs a proper token.
Due to restrictions described [in the docs](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token) It's not possible to create comments
in the context of `pull_request` from an external repository.
To tackle this problem we create two workflows:
The first workflow triggered by `pull_request` stores information
about the PR in artifact and triggers the main workflow.
The main workflow runs the Action using a token …
> [ci] Add GHA workflows to review PRs using Verible

- .github/workflows/pr_lint_review.yml
We observed problems with the action in this PR: https://github.com/lowRISC/ibex/pull/1434
Then, another issue with errors reported with wrong line numbers appeared here: https://github.com/lowRISC/ibex/pull/1435
It looks like the previous version of the action did not handle git remotes properly and that was the root of the problems observed in both PRs. This is fixed in the new release of the action:
https://github.com/chipsalliance/verible-linter-action/releases
The two PRs were recreated here:
https://github.com/antmicro/gha-playground/pull/90
https://github.com/antmicro/gha-playground/pull/88
I can see that the line-length errors are reported for the expected line numbers.
However, it's expected that line-length error won't be reported for a one line comment, so not getting the error …
> Bump Verible action version

- .github/workflows/pr_lint_review.yml
Yet again we're solving the problems discussed here:
https://github.com/lowRISC/ibex/pull/1434
Turns out we had updated Verible to a version in which it switched from using `stdout` to `stderr` for printing rule violations, so the output wasn't passed to Reviewdog as expected.
Right now the action uses `stderr`, as it should.
EDIT:
The things above remain true, but we're changing the version to 'main' to make it easier to apply fixes without incrementing the version each time.
> Set Verible action version to 'main'

- rtl/ibex_tracer.sv
There is an unnecessary use of RD in branch instruction in `ibex_tracer.sv` which is removed. This PR resolves this issue #1441.
https://github.com/lowRISC/ibex/blob/ac8934459b028220ce9fd20683bb018244b59756/rtl/ibex_tracer.sv#L493
> Remove unused RD in branch insn from tracer

- rtl/ibex_alu.sv
- rtl/ibex_decoder.sv
- rtl/ibex_pkg.sv
- rtl/ibex_tracer.sv
- rtl/ibex_tracer_pkg.sv
Add support for the Zba extension added in v0.93 of the bit manipulation
specification (unchanged in v1.0.0). The new instructions added are:
- sh1add: rd = (rs1 << 1) + rs2
- sh2add: rd = (rs1 << 2) + rs2
- sh3add: rd = (rs1 << 3) + rs2
The instructions are single cycle and have been implemented using the
adder in the ALU.
Signed-off-by: Michael Munday <mike.munday@lowrisc.org>
> [bitmanip][zba] Add support for Zba (address calculation) extension

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/scripts/gen_csr_test.py
- vendor/google_riscv-dv/src/isa/riscv_zbb_instr.sv
- vendor/google_riscv-dv/src/isa/riscv_zbs_instr.sv
dv to revision 605301400555c235564f9336cc5fc220af7e951c
* [style] Break long lines in newly added files (Michael Schaffner)
> Update google_riscv-dv to google/riscv-dv@6053014

- rtl/ibex_register_file_fpga.sv
This resolves lowRISC/Ibex#1485.
Note: I've tested that these changes don't impact the Vivado's capability to infer LUTRAM for the FPGA regfile.
> [rtl] Replace always_ff with always @(posedge .. in FPGA regfile

- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
instr_req_out no longer exists now PMP is handled on the IF/ID
interface.
The way co-sim deals with PMP errors will still need adjusting but wanted this fix in as private CI breaks without it.
> [dv] Fix bad reference to instr_req_out

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
Vendored in VIP from OpenTitan is very noisy at default UVM_MEDIUM
level, producing multi-GB log files in some instances.
This will hopefully fix the nightly regression.
> [dv] Set UVM_VERBOSITY to UVM_LOW

- README.md
- doc/01_overview/compliance.rst
- doc/01_overview/targets.rst
- doc/03_reference/instruction_decode_execute.rst
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- ibex_configs.yaml
- rtl/ibex_alu.sv
- rtl/ibex_decoder.sv
- rtl/ibex_pkg.sv
- syn/syn_yosys.sh
This PR adds a new configuration for OpenTitan that enables all bitmanip sub-extensions except for Zbe. The documentation on the bitmanip support is updated and new area numbers have been gathered.
At the moment, we can't verify the bitmanip implementation in CI as we need to switch the Spike version used in default CI and get an updated toolchain (work in progress). However, I've successfully verified the new configuration locally.
> [bitmanip] Add new OpenTitan config, update documentation on bitmanip support and area numbers

- rtl/ibex_tracer.sv
...whose return value is ignored. This cleans up a compile time warning.
Signed-off-by: Srikrishna Iyer <sriyer@google.com>
> [ibex_tracer] Void cast function calls

- ci/install-build-deps.sh
Private CI is broken without this. The public CI runs on azure agents
which already have this installed.
> [ci] Add missing python3-dev dependency

- doc/03_reference/cosim.rst
We're going to want to make a couple more releases of Spike, cleaving
a bit closer to the upstream repository. Let's be explicit about which
version people should get.
> Refer to a specific tag for the ibex-cosim version of Spike

- rtl/ibex_if_stage.sv
- rtl/ibex_top.sv
A sufficiently agressive optimiser may optimise these away as under
normal functioning they effectively don't do anything. They are purely
to detect the presence of induced faults.
> [rtl] Add prim_buf for security critical signals

- doc/03_reference/security.rst
When the icache is enabled and data independent timing is required
variable fetch latency due to cache hit or miss may introduce
undesirable timing behaviour. This adds explicit mention of this to the
documentation.
> [doc] Add details about icache latency to DIT docs

- rtl/ibex_top.sv
Ensure all top-level inputs and outputs are known when they are
expected to be known.
Seems to work fine with some quick tests. I'll do a full regression once this is merged in.
> [dv] Add X assertions for top-level IO

- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_agent_pkg.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_agent.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_agent_cfg.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_driver.sv
Defining agent configuration for any agent is a standard UVM flow and is
a cleaner flow for defining delay between driving sequence items,
passing virtual interface etc.
Agent configuration has been added to the existing agent to make delay
configuration more flexible in the future.
Signed-off-by: Prajwala Puttappa <prajwalaputtappa@lowrisc.org>
> [ibex, dv] Added agent configuration for ibex_mem_intf_response_agent

- rtl/ibex_if_stage.sv
This is triggered by the fact that if the `ICache` parameter is false
then we don't instantiate the `ibex_icache` module. For verilator
simulations, the module is then discarded entirely, which means that
its two DPI functions are not defined. That's unfortunate because
we're also compiling the code in `scrambled_ecc32_mem_area.cc`, which
expects the functions to be defined.
The obvious solution (don't include `scrambled_ecc32_mem_area.cc` if you
don't have an icache) isn't easy to do, because FuseSoc doesn't
currently allow us to use parameters to configure its dependency
tree (see [fusesoc issue 438](https://github.com/olofk/fusesoc/issues/438) for a discussion).
The super-clever solution that I came up with before(!) was to declare
these symbols as weak in the C++ code. That way, we …
> [icache] Define some fake DPI functions to simplify linking

- dv/uvm/core_ibex/tests/core_ibex_new_seq_lib.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
- dv/uvm/core_ibex/tests/core_ibex_test_pkg.sv
- dv/uvm/core_ibex/tests/core_ibex_vseq.sv
Added an independent base test with following capabilities:
* chooses between single run, multiples runs or infinite runs (existing sequence
does this via the `num_of_interations` variable).
* interval between runs can be fixed or random, with 0 delay between runs possible.
For random intervals there should be a way to bias them more towards 0 delay
(e.g. specify 75% of delays should 0 with the rest randomly chosen).
Added an interrupt sequence that inherits from the above base sequence.
It has following capabilities:
* chooses the number of interrupts to raise
* specifies the interval between interrupt being raised and dropped
* a mask to specify interrupts that shouldn't be raised.
Added a debug sequence with the only functionality to specify the interval between
the debug request being …
> [ibex, dv] Added new base, interrupt, debug and mem error sequences

- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_agent_pkg.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_agent.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_agent_cfg.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_driver.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_seq_lib.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_sequencer.sv
This commit adds functionalty to the memory response agent to make delays more
configurable.
There are two delays
- Delay between req and gnt
- Delay between gnt and rvalid
For each of these delays we have three modes:
* Fully random delay
* Fixed delay
* Biased delay. Randomised delays but allow biasing towards 0 delay, to give a mix of runs with back
to back transfers with no delay and some with delays.
> [ibex, dv] Makes delays between req, gnt and rvalid configurable

- dv/uvm/core_ibex/tests/core_ibex_new_seq_lib.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
Ibex has a top-level `fetch_enable_i` input. When set to on (noting it's a multi-bit signal for
security hardening though only the bottom bit is looked at for non secure ibex) Ibex executes
normally. When set to off Ibex will stop executing. Randomly toggling it should have no functional
effect on Ibex's behaviour.
The fetch enable sequence will randomly toggle the value of `fetch_enable_i` with a configurable
bias between the 'On' value and all other values.
> [ibex, dv] Added a sequence to toggle fetch_enable_i pin

- examples/fpga/artya7/rtl/top_artya7.sv
The "alert_major" port was split into "internal" and "bus" parts back
in commit 9943f9a. Update the example to match.
Fixes #1553.
> Fix port list in top_artya7 example

- dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
- examples/simple_system/rtl/ibex_simple_system.sv
- rtl/ibex_core.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_load_store_unit.sv
- rtl/ibex_lockstep.sv
- rtl/ibex_top.sv
Previously integrity checks for incoming memory reads and integrity
generation for outgoing memory writes were handled within ibex_lockstep
and weren't duplicated.
This moves the integrity checks and generation into the core so they are
replicated and checked as part of the lockstep mechanism.
Additionally it generates a bus error on any memory integrity check
failure. This will result in Ibex taking an exception if any data read
or instruction fetch has bad integrity.
> [rtl] Move memory ECC checks and generation into core

- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_monitor.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_req_item.sv
- dv/uvm/icache/dv/ibex_icache_mem_agent/seq_lib/ibex_icache_mem_resp_seq.sv
Earlier the design supported single clock cycle error responses from PMP
block whenever a read was done from blocked memory. Now there is at
least one clock cycle delay after the request has been granted for the
error to be asserted. Therefore, this commit removes the support for
single clock cycle PMP error response.
> [icache, dv] Removed support for single clock cycle PMP error response

- dv/uvm/icache/dv/env/ibex_icache_env.sv
- dv/uvm/icache/dv/env/ibex_icache_env_cfg.sv
- dv/uvm/icache/dv/env/ibex_icache_env_pkg.sv
- dv/uvm/icache/dv/tb/ic_top.sv
- dv/uvm/icache/dv/tb/tb.sv
This commit adds a new scrambling agent to drive scrambling key and valid to the data and tag memory interfaces.
> [icache, dv] Added scrambling agent to verify scrambling in RAMs

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
Fixes a bug where both Xcelium and Python open the same sim.log file and race to
write the simulation results into it. This change makes Python the sole writer of this
file using the captured stdout/stderr from the subprocess.run call in
run_rtl.py.
This bug was also previously present for VCS but was fixed in 90ff7ca6c.
Goes towards #1571
> Remove logfile param in Ibex RTL Sim for Xcelium

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
This enables to have a coverage report in instances where we have
different types of tests in a single iteration.
> [dv,xlm] Save each UCM file in <test_name>.<seed>

- examples/simple_system/ibex_simple_system.core
This is necessary for having VCS support with simple system example.
Because in the ibex_simple_system_main.cc we are including some
Verilator exclusive header files.
> Include the main C++ file only with Verilator

- dv/uvm/core_ibex/Makefile
Enables us to work with only xlm licences when doing the coverage.
> [dv,xlm] Pass simulator flag to cov.py in Makefile

- dv/uvm/core_ibex/sim.py
Enables us to save coverage groups text file which helps easily see the overall
coverage in a regression.
> Fix cov_report directory in sim.py

- dv/uvm/core_ibex/Makefile
- dv/uvm/core_ibex/construct_makefile.py
Improves the core-ibex dv Makefile by adding parallelism to the running of the riscv-dv instruction generator, and also the running of the test binaries using the iss.
This saves approximately 45 mins on a private-ci job with SIMULATOR=xlm ITERATIONS=20 SEED=1 TEST=all COV=1. This particularly helps to better scale to the number of Xcelium licenses available. 
The .stamp files are also renamed through the file to be more consistent.
This PR also makes the whitespace in this makefile more consistent.
> Core ibex dv parallelism improvements

- dv/uvm/core_ibex/Makefile
This was forcing rebuilds continuously
> Fixup .rtl.tb_compile vars.mk filename

- dv/uvm/core_ibex/Makefile
Commit f49f452f2 greatly tidied up the file, which is nice, but also
introduced some whitespace around the first argument to `vars-prereq`.
In Make, this causes chaos!
In particular, we ended up checking whether a variable called
something like "`$(last-   gen  -vars-loaded)`" was defined. It isn't,
but `$(last-gen-vars-loaded)` is.
Call strip in the `vars-prereq` function to get rid of the whitespace at
the "entry point" for all this machinery.
> Fix spurious rebuilds from dumped vars

- dv/uvm/core_ibex/Makefile
I accidentally deleted this in commit 9e0e0cd01.
> Replace dump-vars line for ISS runs

- rtl/ibex_pkg.sv
This is done to match the encoding update done in the OpenTitan repo
here: [#12153](https://github.com/lowRISC/opentitan/pull/12153)
> Update fetch enable encoding

- util/ibex_config.py
This didn't quite work properly for Xcelium (giving strings with an
embedded space: `'-define IBEX_CFG_RV32M=ibex_pkg::RV32MSingleCycle'`).
It turned out not to matter because we were evaluating one time too
often in the shell, but we're about to stop doing that.
> Fix quoting in ibex_config.py

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
This is a bit of an overlap with the existing `sim.log` files that we're
creating (which contain slightly more information), but it turns out
that if you don't say anything then you get an `xrun.log` in the current
working directory.
> Avoid creating xrun.log files in core_ibex directory

- dv/uvm/core_ibex/list_tests.py
No functional change, but the point is that we can vendor this into
OpenTitan where dvsim can load up the Python library and get something
sensible without having to call a subprocess and mess around with
string parsing.
> Factor out guts of list_tests.py

- examples/simple_system/rtl/ibex_simple_system.sv
Verilator complains about MHPMCounterNum being not used. Passing it to the instantiated core solves the issue
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
> Sim: Simple system: handle unused parameter

- dv/riscv_compliance/ibex_riscv_compliance.core
- dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/verilator/simple_system_cosim/ibex_simple_system_cosim.core
- examples/simple_system/ibex_simple_system.core
- examples/simple_system/rtl/ibex_simple_system.sv
- ibex_configs.yaml
- ibex_core.core
- ibex_top.core
- ibex_top_tracing.core
- rtl/ibex_core.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_lockstep.sv
- rtl/ibex_pkg.sv
- rtl/ibex_top.sv
- rtl/ibex_top_tracing.sv
This pull request adds Core-V X-Interface for Ibex. It consists of three separate commits, one for compressed interface, one for issue, commit, and result interfaces, and the other for memory and memory result interface.
By the time I make this pull request only the first two commits are available.
For the first commit of compressed interface, it passes the verification without accelerator and with an external pseudo compressed decoder.
For other two commits, they pass only the verification without accelerator.
This is still a draft of the implementation, I am keep working on further verification.
> CORE-V Extension Interface - Add Compressed Interface

- dv/uvm/core_ibex/scripts/scripts_lib.py
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- examples/simple_system/ibex_simple_system.cc
This allows us to model stuff more closely. This depends on Spike
version ibex-cosim-v0.2 (which is rebased onto a master branch commit
supporting these more specific ISA strings).
> Update ISA strings from Xbitmanip to XZb*

- dv/uvm/core_ibex/Makefile
This seems like something you'd want to enable explicitly, to avoid
filling up a disk on a big run.
> [core_ibex] Disable waves by default

- dv/uvm/core_ibex/scripts/run-instr-gen.py
- dv/uvm/core_ibex/scripts/scripts_lib.py
I was previously just dumping them to /dev/null because the
code always worked but... predictably I was wrong! Write them
somewhere more useful for debug.
> Dump riscv-dv generation messages to a log file

- doc/02_user/integration.rst
Description field for the IcacheScramble instruction rendered incorrectly in the [html version of this page](https://ibex-core.readthedocs.io/en/latest/02_user/integration.html). Fixed the issue in the github rendered version (see rich diff) which will presumable also fix the problem in the HTML version.
> Fix Formatting of IcacheScramble Description

- doc/03_reference/cosim.rst
- doc/03_reference/verification.rst
- dv/cosim/spike_cosim.cc
- dv/cosim/spike_cosim.h
This commit switches to an updated Spike version with support for ePMP.
~I suspect that this PR won't pass CI because the updated Spike version is not yet available on the tool NAS. I just created a new `ibex-cosim-v0.3` tag for that new version.~ ~Related to that I just realized that I probably made mistake when rebasing as I replaced previous call we had to `get_max_xlen()` with `get_xlen()`. I only discovered now that `get_max_xlen()` has been moved to `isa_parser.h` within Spike. I need fix this.~ This is now done.
This is related to #1579.
> Switch to updated Spike version

- dv/uvm/core_ibex/riscv_dv_extension/riscv_core_setting.sv
- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/pygen/pygen_src/riscv_instr_pkg.py
- vendor/google_riscv-dv/src/riscv_instr_pkg.sv
- vendor/google_riscv-dv/src/riscv_pmp_cfg.sv
- vendor/google_riscv-dv/src/riscv_privil_reg.sv
- vendor/google_riscv-dv/target/ml/riscv_core_setting.sv
- vendor/google_riscv-dv/target/multi_harts/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv32i/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv32imafdc/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv32imc/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv32imc_sv32/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv32imcb/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv64gc/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv64gcv/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv64imafdc/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv64imc/riscv_core_setting.sv
- vendor/google_riscv-dv/target/rv64imcb/riscv_core_setting.sv
This update is required to enable ePMP verification in Ibex.
> Update google_riscv-dv to google/riscv-dv@0b2b3d6

- dv/uvm/core_ibex/scripts/run-iss.py
- dv/uvm/core_ibex/scripts/run-rtl.py
- dv/uvm/core_ibex/scripts/scripts_lib.py
Sometimes spike does not terminate when you might expect.
This is a bit of a hack to get CI dailies to fail in a reasonable time.
> Subprocess timeout feature

- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
Before the change the indentation of the second line would be printed as spaces in the fatal message.
> Fix multi-line string formatting in $sformatf for uvm_fatal macro

- rtl/ibex_core.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_pkg.sv
- mtval is a bit more useful for double fault situations
as on the second exception we can still "remember" the
data address and PC of the first exception.
see https://github.com/lowRISC/ibex/issues/1117
> Update crash dump to contain mtval

- rtl/ibex_pkg.sv
This commit changes parameter type from 'int' to 'unsigned int'
according to CV-XIF standard update.
>  CORE-V Extension Interface - Change parameter type

- doc/03_reference/coverage_plan.rst
- dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
- rtl/ibex_controller.sv
Includes coverpoints for:
- Hardware trigger point matches
- Debug simple step entrance in controller
- Cross for seeing different insns while single stepping
Also updates on coverage plan to fill up missing mentions of
coverpoints/crosses
> [fcov] Adding debug related functional coverage

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
(Ignore first commit, it is #1688 and needs merging before this PR.)
Create a test that uses riscv-dv to create an exception-causing instruction stream, while using the UVM testbench to create external interrupt and debug request stimulus.
The interrupt and debug stimulus are driven as pulses with randomised interval and duration. 
This test would benefit from a way for the interrupts to be de-asserted in response to the ISR's being executed. (See #1570)
Goes towards #1568.
> Create interrupts/debug/exceptions test

- .github/workflows/pr_lint_review.yml
The file `rules.vbl` existed in previous commits, but was renamed in later vendored in code.
> [lint] Point to correct Verible rules for lint workflow

- dv/verilator/simple_system_cosim/ibex_simple_system_cosim_checker.sv
Previously any traps seen on RVFI were skipped over. This was old
behaviour. With the latest cosim setup traps must be passed to the
`step` function.
Note the UVM environment does do this correctly so this bug isn't related to the cosim exception issues people have been seeing.
> [dv] Fix traps in simple system cosim

- doc/03_reference/coverage_plan.rst
- dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
- rtl/ibex_load_store_unit.sv
Adds some signal to the load store unit to catch when we have the
fetch error signals from both first and second part of the misaligned
load/store access cases.
Resolves #1697
> [dv,fcov] Implement Misaligned Mem Error coverage

- dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
- dv/uvm/core_ibex/riscv_dv_extension/riscv_core_setting.sv
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
First commit fixes how we collect a certain condition in the case of core not having a clock. Second commit enables generating `FENCE.I` instruction in riscv-dv.
> [dv] Various coverage hole fixes

- dv/cosim/spike_cosim.cc
- dv/cosim/spike_cosim.h
Seperate concerns so the flow of stepping spike and checking against
the ibex RVFI data is clearer. One 'step' of either system produces
different amounts of progress, and this conditional-checking-and-stepping
is needed to tie up the flows.
Closes #1687
> Rework SpikeCosim::step() to handle exception on 1st ISR instr

- dv/uvm/core_ibex/compare.py
- dv/uvm/core_ibex/riscv_dv_extension/csr_description.yaml
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/scripts/run-instr-gen.py
Some issues I came across whilst working on https://github.com/lowRISC/ibex/issues/1663
Commenting out mcause in the CSR description will be temporary but I thought it'd be good to get that test passing.
The `ignore_cosim_log` in the testlist is a bit of a hack (ideally there would be one setting that disables cosim which deal with both the sim option setting and ignore the cosim log) but we will aim to have cosim enabled for all tests so it's a temporary solution for now.
> Riscv csr test fixes

- dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
This commit fixes how we catch an instruction at WB stage. Before this fix
we were effectively checking opcode of decoded instruction instead.
> [dv,fcov] Fix `cp_mem_raw_hz` implementation

- rtl/ibex_top.sv
Some aspects of the memory response are only relevant to reads. This
introduces outstanding request tracking so we know which outstanding
requests are reads and applies X checks appropriately.
Fixes #1645
> [dv] Fix IbexDataRPayloadX assertion

- dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
This commit makes sure that different IRQs are collected in a single
`fcov_irqs` bus correctly. Also changes nmi_taken coverpoint to catch
interrupt taken case for NMI types from the same bus.
> [dv,fcov] IRQ and NMI detection fixes for fcov

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
In various places within Ibex we use unpacked arrays. We weren't dumping
these in Xcelium.
> [dv] Make Xcelium wave dumping includes unpacked arrays

- dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv
- rtl/ibex_pmp.sv
In ePMP spec, it specifies as:
```
Executing code with Machine mode privileges is only possible from memory
regions with a matching Mmode-only rule or a locked Shared-Region rule
with executable privileges. Executing code from a region without a
matching rule or with a matching S/U-mode-only rule is denied.
```
This change provides that.
Resolves #1736 
> [rtl] Deny no-match X access in M-Mode while MML=1

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
This commit sets two different riscv-dv knob to make sure we hit
some holes in our coverpoints.
Activating `enable_timer_irq` for everytime we enable other
interrupts makes sure that we respond to it just like we respond
to other interrupts.
Setting `tw=0` makes it so that we would allow WFI in user mode. We
were already randomizing it but for some certain tests, we actually
want to be in a sleep state, which wouldn't happen if tw=1 in user
mode.
> [dv,testlist] Enable irq_timer, allow WFI in Umode

- rtl/ibex_controller.sv
The relevant page [Debug Spec v1.0.0-STABLE, p.53] gives the following
priorities for resolving multiple concurrent reasons for entering debug mode....
> DCSR.cause : Explains why Debug Mode was entered.
> 
> When there are multiple reasons to enter Debug Mode in a single cycle,
> hardware should set cause to the cause with the highest priority.
> 1: An ebreak instruction was executed.                        (priority 3)
> 2: A Trigger Module trigger fired with action=1.              (priority 4)
> 3: The debugger requested entry to Debug Mode using haltreq.  (priority 1)
> 4: The hart single stepped because step was set.              (priority 0, lowest)
> 5: The hart halted directly out of reset due to resethaltreq. (priority 2)
>    It is also acceptable to report 3 when this happens. …
> Fix incorrect debug_cause priority against riscv-debug 1.0.0-STABLE

- dv/uvm/core_ibex/common/ibex_cosim_agent/spike_cosim_dpi.cc
This extends our memory range to be between 0 and
0xFFFF_FFFF. This is needed because in the case of
no match between UVM memory model and spike memory
model, we see a mismatch.
> [dv,cosim] Add memory region to match UVM env

- dv/uvm/core_ibex/riscv_dv_extension/ibex_asm_program_gen.sv
- dv/uvm/core_ibex/scripts/run-instr-gen.py
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
Use the address (signature_addr - 0x4) for a TEST_PASS handshake.
Create seperate subscriber port for test_done functionality
By creating a new, distinct port and subscribing to all incoming memory items,
the existing wait_for_mem_txn() can be used with minor modifications to be
able to choose the port to wait on as an argument to the task.
Because the wait_for_mem_txn() implementation currently uses get() to pop the
latest item from the item_collected queue, having two different forked processes
that both await on this queue is not possible. The simplest solution is to
create a new, seperate port which also subscribes to the sequence_items
broadcast by the mem_if monitor.
Possible improvements / todo:
- Create a seperate plusarg for this test_done address (don't just assume …
> Change test_done mechanism to use riscvdv handshake, not ecall

- dv/uvm/icache/dv/tb/tb.sv
- rtl/ibex_core.sv
- rtl/ibex_icache.sv
- rtl/ibex_if_stage.sv
- rtl/ibex_lockstep.sv
- rtl/ibex_top.sv
Previously on any invalidation request a new scrambling key for icache
was requested. This causes issues if it happens half way through an
ongoing icache invalidation. This fix ensure the scrambling key request
is only sent if we are starting a new invalidation.
> [rtl] Fix scrambling key request on icache inval

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
We're seeing many timeouts in this test. This is causing issues for the
nightly regression. Keep the test in so we're aware of any major issues
with it but with far fewer timeouts to help keep the regression healthy.
We'll revisit the required iterations once we've sorted out the issues
with the test.
> [dv] Reduce riscv_pmp_full_random_test iterations

- dv/uvm/core_ibex/riscv_dv_extension/csr_description.yaml
With the new WARL functionality for the RISCV-DV CSR test generator we
can bring back these CSRs into the test.
Fixes #1663
> [dv] Add MCAUSE and MSTATUS to the riscv_csr_test

- ci/install-build-deps.sh
Due to a failure of mirror syncing the co-sim package cannot be
installed. This downloads it directly from the master server and
installs it manually.
> [ci] Fix co-sim install

- dv/uvm/core_ibex/scripts/merge_cov.py
- dv/uvm/core_ibex/scripts/setup_imports.py
- python-requirements.txt
We'll need this for integrating into OpenTitan DV: https://github.com/lowRISC/opentitan/issues/11794
> [dv] Use lowRISC IP dir from imports instead of re-deriving it

- dv/uvm/core_ibex/Makefile
- dv/uvm/core_ibex/common/ibex_cosim_agent/ibex_cosim_agent_pkg.sv
- dv/uvm/core_ibex/common/ibex_cosim_agent/ibex_cosim_cfg.sv
- dv/uvm/core_ibex/common/ibex_cosim_agent/ibex_cosim_scoreboard.sv
- dv/uvm/core_ibex/env/core_ibex_env.sv
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
We are running with cosim by default now, and no longer support COSIM=0. Hence
this option and all downstream conditional paths are no longer required.
~~This also removes the +disable_cosim flag from all tests, as we are working towards all tests running under cosimulation anyway~~. For the bitmanipulation and csr test, any failures are now no-longer due to cosimulation and should be tracked separately. For bitmanipulation, it appears the tests for the `opentitan` configuration are all passing.
`+disable_cosim=1` has it's behaviour changed to de-escelate cosim mismatches from fatal-errors to info messages. This can be useful for debugging, and remains in place as the default for riscv_csr_test as that test has known failures.
Closes #1566
> Remove the final cosim flags from core_ibex uvm environment

- dv/uvm/core_ibex/scripts/run_rtl.py
This takes it from 15 to 30 minutes
It reduces the total number of timeouts we see. We should still look at fixing up the long running tests but this will give us a healthier regression.
Draft for now whilst we look into impacts on regression run times.
> [dv] Double timeout for an RTL run in regression flow

- dv/uvm/core_ibex/tests/core_ibex_seq_lib.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
- dv/uvm/core_ibex/tests/core_ibex_vseq.sv
core_ibex_directed_test has a 'disable fork' that was killing processes that were running sequences. Another part of the testbench waits for those sequences to finish. When this 'disable fork' happens too early the sequences are killed before they finish so the testbench never terminated and times out. Instead ensure the sequences have finished before doing the 'disable fork'.
> [dv] Fix timeout issues

- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_id_stage.sv
RISC-V debug modules may utilise dynamically changing code. Don't cache any instructions in debug mode to correctly support this.
Fixes #1472
> [rtl] Don't cache instructions in debug mode

- dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv
The `pmp_*_mode_cross` coverpoints check whether for iside, iside2 and dside there is a match for each region with each mode. However, matching to a region is not possible when the region is set to off, so this should be set as illegal.
> [pmp] Remove off mode from pmp_*_mode_cross coverpoints

- formal/riscv-formal/Makefile
When doing the command `make -C formal/riscv-formal` without this fix the `sv2v` tool complains with the following error:
```
sv2v --define=RISCV_FORMAL -I../../vendor/lowrisc_ip/ip/prim/rtl -I../../vendor/lowrisc_ip/dv/sv/dv_utils ../../rtl/ibex_pkg.sv ../../vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_pkg.sv \
../../rtl/ibex_top.sv > build/ibex_top.v
sv2v: could not find package "prim_secded_pkg"
CallStack (from HasCallStack):
error, called at src/Convert/Package.hs:663:42 in main:Convert.Package
make: *** [Makefile:69: build/ibex_top.v] Error 1
```
> [formal] Added missing prim secded package

- doc/03_reference/cs_registers.rst
- rtl/ibex_cs_registers.sv
- rtl/ibex_pkg.sv
Observing the following spec change:
RISC-V Debug Support Version 1.0.0-STABLE
1.2.1.4 New Features from 0.13 to 1.0
8. Move scontext, renaming original to mscontext, and create hcontext.
MSCONTEXT is a backwards-compatible alias to SCONTEXT. [[1]](https://github.com/riscv/riscv-debug-spec/blob/c40847add0c3e3dcafb6ce568c3979412bb6f341/xml/hwbp_registers.xml#L246)
In Ibex, SCONTEXT is a read-only zero register. Hence MSCONTEXT has the same behaviour.
> Update SCONTEXT address, add MSCONTEXT csr to match riscv_debug 1.0

- dv/uvm/core_ibex/scripts/check_logs.py
- dv/uvm/core_ibex/scripts/collect_results.py
- dv/uvm/core_ibex/scripts/metadata.py
- dv/uvm/core_ibex/scripts/run_rtl.py
- dv/uvm/core_ibex/scripts/scripts_lib.py
- dv/uvm/core_ibex/scripts/test_run_result.py
This commit adds a new field to the trr (test-run-result) structured data
that records the failure_mode of a testcase. If the test failed due to a
timeout, print a small addendum {T} to each log-line in the summary.
eg.
```
23.33% PASS 7 PASSED, 23 FAILED
riscv_debug_basic_test.21259:                     PASS
riscv_debug_basic_test.21260:                     FAILED {T}
riscv_debug_basic_test.21261:                     PASS
riscv_debug_basic_test.21262:                     FAILED {T}
riscv_debug_basic_test.21263:                     FAILED {T}
riscv_debug_instr_test.21259:                     FAILED {T}
riscv_debug_instr_test.21260:                     FAILED {T}
riscv_debug_instr_test.21261:                     FAILED {T}
riscv_debug_instr_test.21262:                     PASS …
```
> Record test failure due to timeout in regr.log

- rtl/ibex_if_stage.sv
Ibex was checking the wrong bit when looking at PMP errors and when to count the error it received from instruction fetch +2.
Closes: https://github.com/lowRISC/ibex/issues/1837
> [if,pmp] Check second bit instead of third for instruction alignment

- doc/03_reference/coverage_plan.rst
- dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv
Added coverpoints for large NAPOT address modes. This is based on Table 3.11 in RISC-V privileged spec.
> [pmp] Add coverpoints for large NAPOT regions

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/src/isa/riscv_instr.sv
- vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
dv to revision c6acc1897429f5245cc89b2ecee2e3eefdefd18d
* Add plusarg to enable ECALL insn in main randomized body (Harry
Callahan)
Signed-off-by: Harry Callahan <hcallahan@lowrisc.org>
> Update google_riscv-dv to google/riscv-dv@c6acc18

- dv/uvm/core_ibex/riscv_dv_extension/csr_description.yaml
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
Note that riscv_csr_test is still broken due to https://github.com/lowRISC/ibex/issues/1846 but when that is sorted we should see it pass.
> Fixup some DV tests

- doc/03_reference/load_store_unit.rst
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_agent.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_agent_cfg.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_driver.sv
- rtl/ibex_controller.sv
- rtl/ibex_core.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_load_store_unit.sv
- rtl/ibex_top.sv
Previously Ibex signaled a major alert on an integrity error (where incoming read data doesn't match its integrity bits) for both read and write responses. This was removed as the data part of a response to a write is ignored.
This brings it back in a more measured way. This provides a little extra fault injection hardening as an attacker glitching the memory bus will generate an alert on both read and write responses.
See https://github.com/lowRISC/opentitan/issues/14611 for some more background on this.
> [rtl/dv] Bring back data integrity check on write responses

- rtl/ibex_controller.sv
This commit changes when we catch the debug causes. Since `debug_cause_o` only gets saved when `csr_save_cause_o` is high, it would work if we change the cause with a mux that is connected to the input signals.
Resolves #1772
> [rtl] Change how we record debug causes

- dv/uvm/core_ibex/env/core_ibex_dut_probe_if.sv
- dv/uvm/core_ibex/env/core_ibex_env.sv
- dv/uvm/core_ibex/env/core_ibex_env_cfg.sv
- dv/uvm/core_ibex/env/core_ibex_env_pkg.sv
- dv/uvm/core_ibex/env/core_ibex_scoreboard.sv
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
Add a new scoreboard component to the core_ibex uvm environment, which contains a double_fault detector task. This uses the top-level output 'double_fault_seen_o' to count the number of total and consecutive double_faults seen within a test. A helper task allows the base_test to wait upon each of these counters reaching the configured thresholds, and then to end the test.
The default thresholds are 100 for consecutive faults, and 1000 for total faults.
When either threshold is reached, the test will fail by default.
A plusarg '+enable_double_fault_detector=1' enables/disables the checker.
The double_fault detector is ~~disabled~~ enabled by default.
A plusarg '+is_double_fault_detected_fatal=1' controls the result of reaching the thresholds. '0' will make the test end with a passing …
> Add a double_fault detector to core_ibex uvm environment

- dv/uvm/core_ibex/scripts/run_rtl.py
- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/src/isa/riscv_csr_instr.sv
- vendor/google_riscv-dv/src/riscv_instr_pkg.sv
This commit fixes couple of bugs in how we handle command generation for VCS, also has updated riscv-dv to have VCS compiling on that as well.
Fixes https://github.com/lowRISC/ibex/issues/1826
> [dv] VCS Fix for Ibex DV

- dv/uvm/core_ibex/common/ibex_cosim_agent/ibex_cosim_agent.sv
- dv/uvm/core_ibex/common/ibex_cosim_agent/ibex_cosim_agent_pkg.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_agent_pkg.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_pkg.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_agent_cfg.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_seq_lib.sv
- dv/uvm/core_ibex/ibex_dv.f
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/tests/core_ibex_test_pkg.sv
Reading uninit DMEM returns a random value.
Reading uninit IMEM returns returns `{2{C.unimp}}`.
[~Integrity errors are no-longer generated.~](https://github.com/lowRISC/ibex/pull/1855#discussion_r995967300)
Integrity errors are now generated by default, but this behaviour can be disabled by settings the plusarg `+enable_bad_intg_on_uninit_access=0`
Goes towards #1846
> Change ibex_mem_intf_response_seq to handle uninit memory differently

- dv/uvm/core_ibex/common/date.c
- dv/uvm/core_ibex/common/date_dpi.svh
- dv/uvm/core_ibex/ibex_dv.f
- dv/uvm/core_ibex/riscv_dv_extension/ibex_log_to_trace_csv.py
- dv/uvm/core_ibex/scripts/check_logs.py
- dv/uvm/core_ibex/scripts/collect_results.py
- dv/uvm/core_ibex/scripts/run_rtl.py
- dv/uvm/core_ibex/scripts/test_run_result.py
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
Adding the key 'timeout_s' to the testlist.yaml file for each test now sets the timeout for all iterations of that test. Value in seconds.
Add a wall-clock timeout mechanism within the simulation itself, by using DPI calls to unix 'date' to get the unix timestamp. This allows the test to end gracefully, which ensures all logs and coverage are generated.
e.g.
Set all iterations of the pmp_full_random test to have a 10s timeout.
```
- test: riscv_pmp_full_random_test
timeout_s: 10
```
This will be very helpful in increasing the number of seeds tested in PMP tests without the inevitable timing-out tests taking up a whole thread for 30 mins (the default timeout for all tests set in metadata.py)
Resolves #1861
> Add mechanism for test-specific timeout

- dv/cosim/spike_cosim.cc
- dv/cosim/spike_cosim.h
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- rtl/ibex_core.sv
This draft PR gives us the basis of https://github.com/lowRISC/ibex/issues/1654 and https://github.com/lowRISC/ibex/issues/1761. We should look to expand the number of tests we're writing cpuctrlsts so the things it controls get randomly changed under more scenarios.
This also gives us part of: https://github.com/lowRISC/ibex/issues/1760 as it implements the double fault behaviour for cosim.
Also note it's based on https://github.com/lowRISC/ibex/pull/1807 so that needs merging first
> Cpuctrlsts write

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/src/riscv_asm_program_gen.sv
- vendor/google_riscv-dv/src/riscv_instr_gen_config.sv
- vendor/google_riscv-dv/src/riscv_instr_pkg.sv
- vendor/google_riscv-dv/src/riscv_pmp_cfg.sv
Bump vendored version to include PMP changes from https://github.com/google/riscv-dv/pull/903
Update code from upstream repository https://github.com/google/riscv- dv to revision ada58fc57a6bc1265e6c261b0f468a79c946a640
* [pmp] Fix plusarg detection for MML and MMWP (Marno van der Maas)
* [pmp] Add missing line return (Marno van der Maas)
* [pmp] Improve formatting of PMP addresses for debug (Marno van der Maas)
* [pmp] Add a register for loop counter in PMP traps instead of mscratch (Marno van der Maas)
* [pmp] Add illegal TOR and NAPOT address mode constraints (Marno van der Maas)
* [pmp] Try to skip instruction if no PMP match and in MMWP (Marno van der Maas)
* [pmp] Store and load faults caused by locked PMP regions now skip to next instruction (Marno van der Maas)
* [pmp] Check for …
> Update google_riscv-dv to google/riscv-dv@ada58fc

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
From an initial triage and test regression run these tests benefit from this.
> [dv] Disable bad integrity on uninitialised memory for selected tests

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
Add 60s timeout for pmp_full_random tests (this sees a reasonable pass-rate)
Tweaked to latest api for double_fault detector
Squashed changes from Marno's ongoing work:
- [pmp] Adjust full random PMP to use random memory addresses [pmp] Enable double fault detecter for MML read only test
- [dv,pmp] Add double fault pass flag
- [dv,pmp] Different parameters for pmp full random test
> Tweak regressions around PMP, allow for double_faults, uninit_accesses

- dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv
1st commit adds the default case in which we ignore PMP checking while in M mode with MMWP&MML both set to 0.
2nd commit samples the cross where we check for mprv bit functionality only when that bit is high. Also adds ignore bins for non-changing privilege levels and non-changing denies/allows.
> [fcov] PMP Coverage Enhancements 

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/src/riscv_instr_pkg.sv
This includes the code-changes initially proposed in #1875 
Update code from upstream repository https://github.com/google/riscv- dv to revision be9c75fe6911504c0e6e9b89dc2a7766e367c500
* Reserve one extra word when pushing GPRs to kernel stack (Harry Callahan)
* Store user-stack-pointer on kernel stack when pushing/popping GPRs (Harry Callahan)
Signed-off-by: Harry Callahan <hcallahan@lowrisc.org>
> Update google_riscv-dv to google/riscv-dv@be9c75f

- rtl/ibex_controller.sv
Previously it was asserted when an instruction in ID would cause an exception but an earlier instruction in WB also causes an exception which takes priority.
This didn't cause a functional bug as the `id_exception_o` signal was used in a single place ORed with `wb_exception_o`. However it was confusing behaviour and could cause killed instructions to appear on the RVFI causing false cosim mismatches.
> [rtl] Fix id_exception_o signal

- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_agent.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_agent_cfg.sv
- dv/uvm/core_ibex/riscv_dv_extension/ibex_asm_program_gen.sv
- dv/uvm/core_ibex/riscv_dv_extension/ibex_debug_triggers_overrides.sv
- dv/uvm/core_ibex/riscv_dv_extension/ibex_directed_instr_lib.sv
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/riscv_dv_extension/user_extension.svh
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
Overrides some riscv-dv classes to create a custom debug_rom for this test
specifically, which is used to setup the breakpoint registers.
It is difficult to get stimulus of this hardware feature without a more directed test.
~~This test currently sets `+disable_cosim=1` because there is a cosimulation bug around setting the trigger address correctly.
That bug will be solved separately.~~
~~Also, the coverpoint `cp_insn_trigger_exception` does not get hit yet because that coverpoint is not possible to hit. It's implementation needs to be rethought, though I believe the stimulus here does trigger the intended behaviour for this coverpoint.~~ Coverpoint was broken, removed & replaced with a new coverpoint in #1872 
To test:
```bash
make TEST=riscv_debug_triggers_test
```
Goes towards #1701
> [dv,debug] Add new uvm test to hit hardware breakpoints coverpoints

- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
> After [removing the integrity-errors generated](https://github.com/lowRISC/ibex/pull/1874/files) from uninit memory accesses, the nested_interrupt test was still failing reliably.
> I think I found the reason why this test was accessing uninit memory in the first place, and propose a solution in this PR.
> 
> Note that I am making this PR with changes directly to the vendored RISCV-DV code, with a view to upstream shortly.
Upstream PR merged [here](https://github.com/google/riscv-dv/pull/906), now vendored into Ibex [here](https://github.com/lowRISC/ibex/pull/1880).
> 
> The problem with this test currently is that riscv-dv has routines to push and pop the GPR's to the kernel-stack upon entering and exiting an interrupt handler, storing the pointer to this effective stack-frame in …
> Nested interrupt test fixes

- dv/cosim/spike_cosim.cc
- dv/cosim/spike_cosim.h
When DCSR is set such that ebreak will enter debug mode we were getting cosim mismatches. This was because Ibex produces the ebreak on the RVFI interface and spike effectively skips right over it and executes the first instruction of the debug handler immediately. Traps have similar but not identical behaviour so we need a special case in the step function to handle this.
> [cosim] Fixup ebreak behaviour

- dv/uvm/core_ibex/common/ibex_cosim_agent/ibex_cosim_agent.sv
- dv/uvm/core_ibex/common/ibex_cosim_agent/ibex_cosim_scoreboard.sv
- dv/uvm/core_ibex/env/core_ibex_env.sv
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
- dv/uvm/core_ibex/tests/core_ibex_vseq.sv
Slightly refactor the reset handling to allow a single routine in the base_test to sequence the bring-up of the testbench components after a reset. This ensures a deterministic bring-up of the testbench env, for example, that the cosim agent has it's memory-model reloaded with the test binary after it has been re-initialized (ie. free'd and re-built).
This is by no-means a perfect solution, but a small improvement to get the `riscv_reset_test` working reliably , which applies on-the-fly reset stimulus. A more idiomatic UVM solution could be applied in the future, using e.g. OT for reference.
Closes #1775
> [dv] Small rework to UVM env to fixup reset handling

- rtl/ibex_core.sv
- rtl/ibex_lockstep.sv
- rtl/ibex_register_file_ff.sv
- rtl/ibex_register_file_fpga.sv
- rtl/ibex_register_file_latch.sv
- rtl/ibex_top.sv
- rtl/ibex_wb_stage.sv
Previously there was a single dummy_instr_id_o signal from ibex_core which the register file used to determine if it could write to the zero register (which reads as zero always for real instructions). However a write occurs in the writeback stage so this signal was not asserted correctly.
This adds a dummy_instr_wb_o signal to control the write to zero register. dummy_instr_id_o remains as it's still employed for register reads for dummy instructions.
> [rtl] Fix dummy instructions

- dv/uvm/core_ibex/riscv_dv_extension/ibex_directed_instr_lib.sv
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
The main idea is to see some writes to `mseccfg` CSR while operating on the `pmp_full_random test` to enhance our stimulus generation and see coverage increases around sticky bit features + some no region match crosses.
Also now we enable randomising `mstatus.mprv` bit in `pmp_full_random_test` with second commit which should improve the coverage on `mprv_effect_cross`
Third commit is about increasing coverage in pmpcfg0 region, enables us to see NA4 region getting configured for instruction channel with randomised execute access.
Note that these changes reduces the pass rate while increasing the coverage.
> [pmp] Add directed instr streams to increase PMP coverage

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
This PR addresses #1755 by verifying that a glitch on the PC of Ibex raises an internal major alert in the core.
> [dv] Add test glitching PC of Ibex

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
Requires the fixes in #1890 , else the coverage will fail to merge.
With the latest changes in #1886 , we achieve the following coverage on a nightly regression...
```
name                                                CoverGroup Average   CoverGroup Covered   
-----------------------------------------           ------------------------------------------
riscv_instr_pkg                                     72.57%               66.17% (7498/11331)  
push_pull_agent_pkg                                 100.00%              100.00% (3/3)        
core_ibex_fcov_if                                   92.05%               46.68% (1095/2346)   
core_ibex_pmp_fcov_if.g_pmp_cgs_T                   90.00%               80.85% (76/94)       
core_ibex_pmp_fcov_if.g_pmp_cgs_T.g_pmp_region_fcov 92.08% …
```
> Increase iterations for PMP tests to improve coverage

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
The `-access rw` option allows Xcelium to access signals in the design (e.g., with `uvm_hdl_read` or `uvm_hdl_force`) without having to dump waves (which substantially increases the run time).  See [1] for the background discussion.
[1]: https://github.com/lowRISC/ibex/pull/1879#issuecomment-1300216022
> [xlm] Enable access to signals without dumping waves

- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_monitor.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_driver.sv
- dv/uvm/core_ibex/common/irq_agent/irq_monitor.sv
- dv/uvm/core_ibex/common/irq_agent/irq_request_driver.sv
- dv/uvm/core_ibex/env/core_ibex_scoreboard.sv
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
The isolation fork ensures the `disable fork` only effects the processes inside the isolation fork. Without it it may terminate other processes that weren't intended to be killed.
> [dv] Add missing isolation forks

- dv/cosim/spike_cosim.cc
In debug mode, we are not supposed to record sync_exc_seen field even if we see sync exceptions.
> [dv] Don't set sync_exc_seen in Debug Mode

- doc/03_reference/coverage_plan.rst
- dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- rtl/ibex_core.sv
- rtl/ibex_if_stage.sv
This commit adds coverpoints and crosses for security countermeasures implemented in the design.
Resolves #1762 
> [dv] V2S Coverage Implementation

- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
When interrupt taken is nmi, then MPIE might not necessarily be 1, so modifying the condition with the check when cause code is nmi, this check would be ignored.
A test in CI pipeline was failing due to this, now its passed.
> [dv] fixed uvm check for mstatus.MPIE when interrupt is nmi

- rtl/ibex_tracer.sv
They only have 5 bit immediates so use the shift form for I format decode.
> [rtl] Fix zbs bitmanip instruction tracer output

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/src/isa/riscv_compressed_instr.sv
- vendor/google_riscv-dv/src/isa/riscv_zbb_instr.sv
- vendor/google_riscv-dv/test/riscv_instr_cov_test.sv
Update code from upstream repository https://github.com/google/riscv- dv to revision d7c50c1eb9abe85bd6673878fe2e98489cf5f07e
* Fix `update_src_regs` for ZBB (Greg Chadwick)
* Sample bitmanip instruction coverage (Greg Chadwick)
* Fix for issue google/riscv-dv#826, illegal rs1 in C_JALR (Henrik Fegran)
Signed-off-by: Greg Chadwick <gac@lowrisc.org>
> Update google_riscv-dv to google/riscv-dv@d7c50c1

- dv/uvm/core_ibex/common/ibex_cosim_agent/ibex_cosim_scoreboard.sv
- dv/uvm/core_ibex/env/core_ibex_dut_probe_if.sv
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
When a writeback exception occurs when the instruction in ID/EX has seen an instruction fetch error we need to ensure that error doesn't get notified to cosim. This requires watching for a writeback exception and removing the latest iside error from the queue if needed.
> [dv] Fix iside error notification to cosim

- rtl/ibex_id_stage.sv
Without this an instruction executed immediately after the MSECCFG write doesn't have the new MSECCFG setup applied to its execute permission.
> [rtl] Flush pipe on MSECCFG CSR write

- vendor/google_riscv-dv.lock.hjson
- vendor/google_riscv-dv/src/riscv_pmp_cfg.sv
- vendor/google_riscv-dv/src/riscv_privileged_common_seq.sv
Update code from upstream repository https://github.com/google/riscv- dv to revision 68ab8230c52ec66b393c04394aef4d6082ee53b4
* [pmp] Ensure MML PMP configurations don't dominate. (Greg Chadwick)
* [pmp] Add option to constrain addresses to stay in 32-bit space (Greg Chadwick)
* randomizing mstatus.MIE when priv mode is lower than machine (Saad Khalid)
Signed-off-by: Greg Chadwick <gac@lowrisc.org>
> Update google_riscv-dv to google/riscv-dv@68ab823

- dv/uvm/core_ibex/riscv_dv_extension/ibex_directed_instr_lib.sv
- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
It randomly writes to fields of cpuctrlsts to enable and disable data independent timing, dummy instruction insertion and the icache. This is used in riscv_debug_basic_test and riscv_single_interrupt_test to see interrupts and debug requests when dummy instruction insertion and data independent timing is enabled.
> [dv] Add instruction stream to toggle Ibex specific features

- doc/03_reference/index.rst
- doc/03_reference/verification.rst
- doc/03_reference/verification_stages.rst
There's still some actions outstanding from V2/V2S but it's getting close.
I wanted to get this out as PR so there's a chance for people to raise objections to the checklist or the way I've presented this within the Ibex documentation.
We still need some OT doc updates to point to the Ibex documentation for the V2/V2S checklists.
Merging this PR will declare V2/V2S for Ibex.
> [doc] Add V2/V2S checklists and declare V2S

- rtl/ibex_cs_registers.sv
- rtl/ibex_pmp.sv
Xprop is a simulation feature that improves the SV semantics when conditions contain 'X values. Change RTL or DV code to enable more xprop instrumentation.
This addresses lowRISC/opentitan#16791 and some of lowRISC/opentitan#16723.
This is work by @matutem imported from https://github.com/lowRISC/opentitan/pull/16777.
> [rtl] Change code to be more xprop-friendly

- rtl/ibex_wb_stage.sv
Previously, it was possible to glitch data_rvalid_i at the interconnect level and if the data integrity bits happened to be valid, Ibex would write the current data_rdata_i into the register file even if it wasn't doing a load. Since the glitch is inserted at the interconnect level, both the main and the shadow core are affected equally.
This commit changes the WB stage to only forward the LSU write enable, which is generated from data_rvalid_i, when Ibex is actually waiting for an interconnect response for a load instruction. This substantially narrows down the window for attacks at the interconnect level.
> [rtl] Improve FI hardening around data_rvalid_i

- ci/install-build-deps.sh
Starting with setuptools version 66.0.0, legacy package version names such as 0.23ubuntu1 are no longer supported. Since some of our Python dependencies use this format, we pin the setuptools version to the last version before this change. This unblocks CI and gives us time to upgrade/rebase our dependencies.
> [python-requirements] Pin setuptools version to < 66.0.0

- dv/cosim/spike_cosim.cc
Override mtvec and misa CSRs to match the Ibex behavior. Inconsistency with Spike was due misa and mtvec having following behaviour in Ibex:
* misa is hardwired
* mtvec has a mask such that it is 256 byte aligned and always vectored
These issues were caught when misa and mtvec are written and read back in the test.
> Override misa and mtvec CSRs in cosim

- dv/uvm/core_ibex/directed_tests/custom_macros.h
- dv/uvm/core_ibex/directed_tests/directed_testlist.yaml
- dv/uvm/core_ibex/directed_tests/empty/empty.S
- dv/uvm/core_ibex/directed_tests/gen_testlist.py
- dv/uvm/core_ibex/directed_tests/ibex_macros.h
- dv/uvm/core_ibex/directed_tests/pmp_mseccfg_test/pmp_mseccfg_test.S
Added a directed test for covering all scenarios of mml=1 with rlb=0/1 with all combinations of PMP.LXWR and accessing that configured PMP region with RW accesses.
> Directed test for PMP.LXWR transitions when mseccfg.mml is 1

- rtl/ibex_cs_registers.sv
All RV32B configs include non-ratified sub-extensions so the 'X' bit MISA must be set for all of them.
This will fix the failure in private CI
> [rtl] Fix MISA X bit for balanced bitmanip config

- rtl/ibex_controller.sv
Hi there!
Some tools modify module names during their flow, or allow to do it optionally, such as the `-p` flag of [Morty](https://github.com/pulp-platform/morty).
However, there is one display occurrence which refers to explicit module names, which breaks compatibility with such passes.
Arguably this is a problem of the tool, but:
* Such absolute references are rare across designs and appear only here in Ibex afaik.
* It looks much easier to fix in Ibex than in the tools.
Please feel free to edit the fix in place!
Flavien
> Avoid explicit module names references to signals

- README.md
- dv/uvm/core_ibex/scripts/report_lib/svg.py
I've manually edited the current summary.svg to be what it would be with the svg tweaks in this PR. If the nightly runs before we merge this we'll be back to the one with the bold black names on the labels and a bunch of whitespace.
> Ibex readme regression

- README.md
The block diagram now represents both the 2 and 3 stage Ibex configurations.
> [doc] Remove misleading sentence above block diagram

- dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv
Execute access would be permitted in M-mode when,
* mml is low
* region is unlocked
Included only `R, W, WR` among unlocked regions as unlocked region with PMP.X is already in illegal bin `illegal_deny_exec` and also PMP_NONE in bin `illegal_machine_deny_exec`.
> Removed few uncoverable ePMP fcov 

- python-requirements.txt
The latest v3 is producing CI failures, pin to compatible with 2.13 for now to fix this.
> [ci] Specify typeguard version

- examples/sw/simple_system/common/simple_system_common.c
- examples/sw/simple_system/common/simple_system_common.h
The `pcount_enable` function can be used to selectively enable performance counters only for a specific code segment.  For example:
```c
pcount_enable(0);
pcount_reset();
pcount_enable(1);
/* code to be measured */
pcount_enable(0);
```
The `pcount_enable` function consists of a single CSR instruction, so the overhead and thus the impact on the measurement is potentially low. When the function is called, however, many instructions have to be executed in addition to the single CSR instruction, which influences measurements.
This commit moves the `pcount_enable` function to the `simple_system_common.h` header file and declares it as `inline` (and `static`, to prevent link-time collisions when the header file is included in multiple compilation units).  This helps the compiler inline the …
> [sw/simple_system] Declare `pcount_enable` function as inline

- rtl/ibex_if_stage.sv
The include is needed for a FCOV related macro. Lack of this include can cause issues in some simulators.
> [rtl] Add missing `include to ibex_if_stage

- rtl/ibex_core.sv
When there is an interrupt followed by an nmi interrupt or a debug request (which if detected before the first instruction of trap handler was executed), the already captured previous interrupt info needs to be updated with nmi_interrupt or debug_request.
As RTL seems to follow this priority: debug_request << nmi_interrupt << other interrupts (to confirm from documentation), so Spike needs to be fed with captured info for the upcoming nmi_interrupt or debug_request.
> Fix capture info for ibex cosim in case of multiple interrupts

- rtl/ibex_core.sv
- rtl/ibex_id_stage.sv
- rvfi_trap now correctly handled for writeback
- issue created to track coverpoint for pmpcfg reserved bits writes.
- flush pipe on debug CSR writes is reasonable
For the debug CSR write it may be a pipeline flush isn't required but it's safer to do so and doesn't present any real performance concerns so we may as well leave it in.
> Remove TODOs

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
We ended up with the Unicode fix twice because of two colliding PR merges. We only need one copy of the -CFLAGS argument, and VCS generates a rather strange message about an unknown argument if you use it twice. Fortunately, it's easy to fix once you've worked out how to get the system to print out what it's doing.
> Drop a double entry in rtl_simulation.yaml

- dv/uvm/core_ibex/scripts/scripts_lib.py
It seems that typeguard now spots if `env` happens to be None. We can just relax things: we're only using `env` by passing it through to `subprocess.run`, which handles a None `env` in the expected way.
> Correct type in scripts_lib.py's run_one

- doc/03_reference/cosim.rst
Some code we've got in Ibex uses some stuff we added to Spike last October. That, in turn, is now tagged in our riscv-isa-sim repository as ibex-cosim-v0.5. Update the version requirement here to match.
> Bump Spike minimum version

- dv/uvm/core_ibex/common/ibex_cosim_agent/ibex_cosim_scoreboard.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_agent_pkg.sv
- dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
- dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv
- dv/uvm/core_ibex/riscv_dv_extension/ibex_asm_program_gen.sv
- dv/uvm/core_ibex/riscv_dv_extension/ibex_debug_triggers_overrides.sv
We're not quite there yet, but it's much closer*! I've put sensible comments on all the commits in the PR, but they are mostly to do with cleaving more carefully to the IEEE SystemVerilog spec and not assuming things that happen to be true for a different simulator.
(*) With the current code, running something like `make IBEX_CONFIG=opentitan SIMULATOR=vcs ISS=spike ITERATIONS=1 SEED=1 TEST=riscv_arithmetic_basic_test WAVES=0 COV=0` gets as far as actually generating some binaries. Next: getting sensible trace logs!
> Tweaks to Ibex to get core_ibex UVM to build with VCS

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
This helps hit more coverage more reliably in particular for the priv_mode_irq_cross cross coverage.
A better fix would adjust riscv_mem_intg_error_test to utilize U mode more but it's a quick test for run so this suffices for now.
> [dv, fcov] Increase iterations of riscv_mem_intg_error_test

- examples/simple_system/rtl/ibex_simple_system.sv
- shared/rtl/sim/simulator_ctrl.sv
These changes are mostly in `simple_system`, to get Xcelium to build it into something sensible.
(I should confess that I've not actually managed to get the simulation to *do* anything useful yet, but hopefully this is a step in the right direction!)
> Minor tweaks to fix some Xcelium build warnings

- CREDITS.md
Add names of missing contributors. Currently there are only a few letters which are not represented with the first names of Ibex contributors: J, O, Q, W and X. If your first name starts with any of those letters make a contribution to Ibex to help us round of this list, and if your name does not start with those letters than still do make your contribution because that's the beauty of open source!
Please also do accept my apologies if I have missed your name from browsing through the commit history, feel free to add your name to this file through a PR.
Thank you to everyone who has contributed to Ibex over the years!
> [credits] Add names of recent contributors

- ibex_core.core
- ibex_top.core
The recent versions of Verible that I've tried die when they are given an empty waiver file. The error message is "Fatal error: Broken waiver config handle". I can't see a way to add a comment ("// No waiver" or similar), so I think the best way to keep everything alive is to delete the empty file.
(This is motivated by trying to get a separate change that I was working on to pass CI. The first step was to reproduce the CI lint check that was failing for it!)
> Remove (empty) Verible waiver file

- dv/uvm/core_ibex/scripts/ibex_cmd.py
This shouldn't change the behaviour when it works. On a failure, we now print out a bit more about what's going on.
When asked to do something impossible now, I think the output is a bit clearer. For example, if you try to run riscv_bitmanip_full_test with an OpenTitan configuration (which doesn't have full bitmanip), the warning message is now:
WARNING:ibex_cmd:Rejecting test: riscv_bitmanip_full_test. It specifies rtl_params of ['ibex_pkg::RV32BFull'], which doesn't contain the expected 'ibex_pkg::RV32BOTEarlGrey'.
(The following stuff that appears is a bit messy, but at least the first line is now clearer!)
Triggered by issue #2071.
> Tweak ibex_cmd.py to fail more cleanly

- tool_requirements.py
It turns out that we use split_var in the code, which was added in version 4.030 (and several bugs were fixed in following versions). Change the minimum required version to match what we're using in CI (and presumably works!)
Closes #2080.
> [doc] Bump minimum Verilator version

- dv/uvm/core_ibex/scripts/directed_test_schema.py
- python-requirements.txt
> Port directed_test_schema.py to recent versions of Pydantic

- lint/verilator_waiver.vlt
- rtl/ibex_tracer.sv
This waives/fixes a couple of warnings that appear with recent versions of Verilator. See the commit messages for details.
Fixes #2091.
> Fix a couple of Verilator warnings

- dv/uvm/core_ibex/scripts/report_lib/util.py
- dv/verilator/pcount/cpp/ibex_pcounts.cc
- examples/simple_system/rtl/ibex_simple_system.sv
This comes in two commits, but the first is a silly typo fix. The commit message for the second is:
> [dv] Fix performance counter printing in simple system
> 
> This will avoid printing out a load of spurious zeros if the Ibex
> config doesn't enable the corresponding counter.
Partial fix for #2101.
> [dv] Fix performance counter printing in simple system

- .github/workflows/ci.yml
- .github/workflows/pr_lint.yml
This change updates the GitHub actions workflows to run on PR updates and within the GitHub merge queue, but not on the push to the master branch.
Because we use merge queues, the re-run for the master branch would be redundant.
> [ci] Run CI in merge queue and not master

- python-requirements.txt
- util/check_tool_requirements.py
`distutils` is deprecated and will generate warnings when used. Replace it with packaging.version instead.
pip3 command line invocation is replaced with importlib.metadata, which removes dependency on pip3 being present.
> [util] Update check_tool_requirements.py

- doc/03_reference/verification.rst
Not sure if this is helpful, but:
Currently, the verification documentation recommends to using ibex-cosim-v0.3. However, this version of spike causes some compilation issues for `spike_cosim `on my side:
`class "processor_t" has no member "set_mhpm_counter_num`
when calling `make` in `dv/uvm/core_ibex/`.
This issue occurs when using the latest pre-build lowrisc toolchain "20231205-1" or "20230427-1".
When using ibex-cosim-v0.5 DV works.
> [doc] Update cosim version

- .github/workflows/private-ci.yml
The private CI works by using workflow dispatch to trigger a CI on another repository.
Pending status checks are created before calling the dispatch to indicate their queued status before they are picked up in private CI, and also serves to block merge group from success.
> [ci] introduce GitHub actions based private CI

- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
We do not actively use or test these commands and tools, so they probably broke some time ago.
> Fixup the questa build/sim command templates in rtl_simulation.yaml

- dv/uvm/core_ibex/scripts/merge_cov.py
1. In [`metadata.py`](dv/uvm/core_ibex/scripts/metadata.py), class `RegressionMetadata` has a field named `dir_cov`, not `cov_dir`:
https://github.com/lowRISC/ibex/blob/38da151a251de5b13afeedf9c5947707f87c5992/dv/uvm/core_ibex/scripts/metadata.py#L117
https://github.com/lowRISC/ibex/blob/38da151a251de5b13afeedf9c5947707f87c5992/dv/uvm/core_ibex/scripts/metadata.py#L153
But in [`merge_cov.py`](dv/uvm/core_ibex/scripts/merge_cov.py), it refers to a field named `cov_dir` that does not exist in class `RegressionMetadata`:
https://github.com/lowRISC/ibex/blob/38da151a251de5b13afeedf9c5947707f87c5992/dv/uvm/core_ibex/scripts/merge_cov.py#L45-L47
This results in an `AttributeError` during dv process:
> AttributeError: 'RegressionMetadata' object has no attribute 'cov_dir'
---
2. In …
> [dv] Fix paths in `merge_cov.py`

- ci/vars.env
- ci/vars.yml
- tool_requirements.py
To be consistent between projects, this PR updates the Verilator version to 4.210, which is also used by OpenTitan. The reason for this change is that in #2129 Verilator linting issues occured that did not occur in OpenTitan.
Closes #2131.
> Update verilator version

- dv/uvm/core_ibex/ibex_dv.f
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- ibex_top.core
- rtl/ibex_core.sv
- rtl/ibex_lockstep.sv
- rtl/ibex_pkg.sv
Currently, the dual-core lockstep FI mitigation is enabled/disabled using a single bit. For transient bit-flips, this is not problematic, as one bit-flip into this signal and one bit into the Ibex is required to threaten the security of the system.
However, a permanent stuck-at-0 fault could disable the lockstep completely by targeting this signal. Then, only a single, additional fault (transient or permanent) is required.
This PR enhances the FI resilience of the Ibex lockstep by encoding this single bit into a `ibex_mubi_t` signal, i.e., a 4-bit multi-bit signal. Note that the MUXes:
https://github.com/lowRISC/ibex/blob/2fbf04636b329bdb643501ab0ef3ee7d6b3303a9/rtl/ibex_lockstep.sv#L138
and
https://github.com/lowRISC/ibex/blob/2fbf04636b329bdb643501ab0ef3ee7d6b3303a9/rtl/ibex_lockstep.sv# …
> [rtl] Harden lockstep enable against FI

- doc/requirements.txt
The previous ~= 4.2 was failing build on readthedocs
This will (hopefully) fix https://github.com/lowRISC/ibex/issues/2132
> [doc] Require sphinx version >= 7.0

- .github/workflows/private-ci.yml
This is a very rare condition where GitHub triggers the workflow a little bit too fast before the asynchronous mergeability check has completed (only an issue for pull_request_target because pull_request would block on mergeability check completion). To address this issue I added a polling loop to do a few retries.
An example run is here: https://github.com/nbdd0121/ibex/actions/runs/7728003457/job/21067811451 (it fails in a later step due to lack of secrets, but that's expected).
> Fix stale merge commit issue in private CI

- examples/sw/benchmarks/README.md
- examples/sw/benchmarks/coremark/ibex/core_portme.c
- examples/sw/simple_system/common/simple_system_common.h
A collection of small fixes/changes produced whilst I was running coremark to get the latest Ibex performance numbers across different configurations.
> Misc fixes

- doc/03_reference/cs_registers.rst
The commit 70186c57 renamed the CSR `cpuctrl` to `cpuctrlsts` but did not update the table in `doc/03_reference/cs_registers.rst`. Fix that.
> Update old `cpuctrl` CSR name in `cs_registers.rst`

- rtl/ibex_tracer.sv
Modify the tracer to use the appropriate read/write masks when logging load/store traffic from the Load Store Unit.
The logging code was using the wrong strobes when appending the loaded/stored values to the report as may be seen in the following snippet from a core trace:
```
249402	    104397	000081cc	0062ae23	sw	x6,28(x5)	  x5:0x30470000  x6:0x03b9aca0 PA:0x3047001c store:0x03b9aca0 load:0x00000000
249404	    104398	000081d0	4305	c.li	x6,1	  x6=0x00000001
249442	    104417	000081d2	0062aa23	sw	x6,20(x5)	  x5:0x30470000  x6:0x00000001 PA:0x30470014 store:0x00000001 load:0x00000000
249444	    104418	000081d6	30134537	lui	x10,0x30134	 x10=0x30134000
249554	    104473	000081da	3d852283	lw	x5,984(x10)	 x10:0x30134000  x5=0x00000000 PA:0x301343d8 store:0x00000000
```
Specifically, when …
> [tracer] Fix reporting of load/store data

- ci/install-build-deps.sh
We are switching to use non-root GitHub action runners, which need sudo for global package installation.
> [ci] Add missing sudo in CI

- dv/riscv_compliance/ibex_riscv_compliance.core
- dv/verilator/simple_system_cosim/ibex_simple_system_cosim.core
- examples/simple_system/ibex_simple_system.core
This sets the C++ standard that's being used for a compiler that's building a Verilator simulation. Recent versions of Verilator (since 5.020) require the compiler to be in C++14 mode, so passing -std=c++11 breaks the build with them.
Looking at history, -std=c++14 has been supported since GCC 6.1 (released in 2016), so I don't think this argument is going to cause any tooling problems.
Fixes #2153.
> [simple_system] Bump C++ version in core files

- dv/uvm/icache/dv/fcov/ibex_icache_fcov_if.sv
- rtl/ibex_core.f
- rtl/ibex_counter.sv
- util/Makefile
These four files were missing copyright headers and license tags.
I can see from https://github.com/lowRISC/ibex/blob/master/vendor/google_riscv-dv/files.f that `.f` files can have `//`-style comments.
> Add missing copyright headers

- rtl/ibex_top.sv
This parameter allows integrators controlling the number of PRINCE half rounds in the scrambled ICache SRAM primitives, e.g., to balance timing impact and security guarantees.
> [rtl] Expose ICacheScrNumPrinceRoundsHalf parameter

- rtl/ibex_core.sv
- rtl/ibex_ex_block.sv
- rtl/ibex_id_stage.sv
- rtl/ibex_multdiv_fast.sv
- rtl/ibex_multdiv_slow.sv
- rtl/ibex_wb_stage.sv
With this change all memory responses are only acted on if Ibex is expecting them for all secure configurations. Previously an error response that was injected onto the bus would trigger an exception that shouldn't occur (in particular breaking the functioning of the multiply state machine). In addition for configurations without the writeback stage an injected load data response could trigger an incorrect write to the register file.
This is only applied to the secure configurations, non-secure configurations assume correct adherence to the bus protocol meaning a response will only be seen if a request is outstanding.
Fixes https://github.com/lowRISC/ibex/issues/2144
> [rtl] Guard against false memory responses for secure configurations

- README.md
The OpenTitan docs updated a while back and this link was missed.
> [doc] Fix C++ style guide link in README

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
This tests new hardening added to the register file around read and write control signals.
> [dv] Add riscv_rf_ctrl_intg_test

- dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
This test injects a fault into different MuBi encoded signals within the prim_ram_1p_scr and prim_ram_1p_adv and checks whether a fatal alert is triggered.
I have excluded the addr_match signal from FI as its encoding  is not directly checked. If the signal was a MuBi True, a fault into it is treated by the mubi4_and_hi as a False. If the signal was a MuBi False, a fault into it is treated by the mubi4_and_hi also as a False. Hence, no address collision occurs and the holding register is not returned.
This PR is based on #2182 and closes #2173.
> [dv] Add riscv_ram_intg_test

- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_monitor.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_request_driver.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_agent.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_agent_cfg.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_driver.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_seq_lib.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_sequencer.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_seq_item.sv
- dv/uvm/core_ibex/env/core_ibex_env_cfg.sv
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/tests/core_ibex_vseq.sv
A spurious response is one that isn't associated with any on-going request. With this new feature the memory agent can generate them randomly when the interface is idle (i.e. there are no outstanding requests).
> [dv] Add spurious responses to memory agent

- rtl/ibex_controller.sv
Prior to this commit an ECC failure on the incoming data memory response factored directly into the outputs for the instruction memory interfaces. This existed due to a desire to take an NMI on an ECC failure as soon as possible but causes timing issues so it has been altered.
Now rather than directly raise the NMI the same cycle the assertion of 'irq_nm_int' is delayed by a cycle which breaks the feedthrough path.
> [rtl] Remove ECC related data_rdata_i -> instr_X_o feedthroughs

- dv/uvm/icache/dv/fcov/ibex_icache_fcov_if.sv
It appears that VCS require expression after `iff` to be wrapped inside parenthesis otherwise it will complain about syntax error.
This should fix the weekly VCS regression, which seems to be failing [forever](https://github.com/lowRISC/lowrisc-private-ci/actions/workflows/ibex-weekly-vcs.yml) due to this.
> Fix icache regression failure on VCS

- rtl/ibex_register_file_latch.sv
This commit fixes a typo that used the wrong read address (raddr_b instead of raddr_a) for port A.
> [rtl] Fix wrong address in latch RF

- dv/uvm/core_ibex/scripts/compile_tb.py
- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
The previous code here was a bit too hacky, so implement a solution that directly follows the suggestion in the Cadence support article. An example was also added to make it clear what this transformation is achieving.
Additionally, cleanup some of the other code in the module, renaming for clarity and adding comments. Move some variable declarations around to be closer to their use. Add some more typehints.
Fixes #2205
> [dv,py] Tweak ISS linker arg construction for Xcelium

- doc/03_reference/images/blockdiagram.svg
My hackday project, which I think improves the block diagram formatting without doing any major re-organization.
> Block diagram update

- rtl/ibex_register_file_fpga.sv
We should use `WordZeroVal` instead of `0` for reads from register `x0` in the FPGA register file.
This bug was discovered when enabling the `RegFileECC` parameter. When this is enabled, the core performs ECC checks, expecting that `WordZeroVal` is returned for `x0`. Else, we get a major alert.
Fixes lowRISC/opentitan#25146
> [rtl] Fix zero value in FPGA RF

- rtl/ibex_counter.sv
If the counter width is >= 49, we do not use a DSP on the FPGA. Then, we should use an asynchronous reset to initialize the counter.
This bug was detected when enabling the lockstep for the CW340. A lockstep mismatch happend as the mcycle counters of the main and shadow core did not match due to this bug.
> [rtl] Fix counter reset value on FPGA

- rtl/ibex_counter.sv
Reverts lowRISC/ibex#2226 because the scope for counter_q is incorrect resulting in synthesis failure for Xilinx targets.
> Revert "[rtl] Fix counter reset value on FPGA"

- rtl/ibex_counter.sv
When targeting Xilinx FPGAs, we utilize a DSP for counters with a width of less than 49-bit. In this case, a sync. reset is needed. However, currently, there is a bug in the RTL where also a sync. reset is used for the non-DSP counters on the FPGA.
> [rtl] Fix non-DSP reset in ibex_counter

- dv/verilator/pcount/cpp/ibex_pcounts.cc
Although the current code isn't wrong as far as I can tell, it would be better to initialize the lognest_name_length variable when it is declared to avoid a build warning with older Verilator versions.
> ibex_pcounts: resolve uninitialize warning

- rtl/ibex_register_file_fpga.sv
These errors aren't detected or reported if the mux is disabled, but the RTL didn't actually drive them at all.
Fixes #2239.
> [rtl] Drive oh_raddr_*_err if RdataMuxCheck=0

- rtl/ibex_tracer.sv
Without, this causes warnings in xcelium:
```
Local static variable with initializer requires 'static' keyword.
```
> [ibex_tracer] Use static variables in always/final blocks

- rtl/ibex_register_file_fpga.sv
These were noticed by someone responding to issue #2230. I think the author's original logic was to point out that there's a path from e.g. raddr_a_i to rdata_a_o which doesn't depend on any clock, so is "asynchronous".
But that's the same in the other modes and also for the other register file implementations, which don't have analogous comments.
Drop these ones.
> [ibex_register_file_fpga] Drop two confusing comments

- rtl/ibex_core.sv
This assertion wasn't quite correct if SecureIbex is false because it was checking for the magic IbexMuBiOn value instead of just looking at the bottom bit.
Fixes #2249.
> [ibex_core] Fix assertion when SecureIbex is false

- rtl/ibex_controller.sv
This removes several assertions from `ibex_controller`. They aimed to ensure that controller behaviour was correct on exception behaviour (e.g. ensuring that a pending interrupt will actually trigger an interrupt). However they've proved to be flaky and hard to maintain with multiple edge cases needing to be accounted for.
The co-simulation checking in functional verification will catch the same issues these assertions catch. The assertions (when working correctly) would cause a failure directly when the bug happens which makes debugging easier. However they've added significant effort in regression triage due to their many false failures so it's not worth the maintenance burden.
Within formal they don't really add any value now we have the full end-to-end formal flow.
I decided this was …
> [rtl] Remove low utility assertions

- dv/cosim/cosim.h
The concept of pre and post MIP values was introduced a while ago but the comments in the interface weren't updated to explain what they are.
> [cosim] Update comment on `set_mip` in Cosim interface

- dv/verilator/simple_system_cosim/ibex_simple_system_cosim.core
- examples/simple_system/ibex_simple_system.core
- rtl/ibex_core.sv
- rtl/ibex_lockstep.sv
Our current version of Verilator issues "IMPERFECTSCH" warnings, which sometimes appear spurious. According to the [manual](https://verilator.org/guide/latest/warnings.html#cmdoption-arg-IMPERFECTSCH) this warning is disabled by default, but we explicitly enabled it a while back in https://github.com/lowRISC/ibex/pull/1250 and created some RTL workarounds to avoid it in https://github.com/lowRISC/ibex/pull/2129.
Now, the same warning has reappeared at the same point due to the changes in https://github.com/lowRISC/ibex/pull/2267. However, this PR does not touch the code that leads to the warning, which is why I propose removing the warning altogether now and updating Verilator in the near future. Alternatively, we could disable it for the specific lines where it appears in …
> Disable Verilator's IMPERFECTSCH warnings

- doc/03_reference/cs_registers.rst
- rtl/ibex_core.sv
- rtl/ibex_cs_registers.sv
- rtl/ibex_pkg.sv
- rtl/ibex_top.sv
Instead of using default values from a package, create a top-level parameter to define these and pass them down. This allows integrators to specify them on a per-instance basis.
> [ibex] Pass mvendorid and mimpid as top-level params

- dv/formal/verify.tcl
The MType_{Div,DivU,Rem,RemU}_PC properties were proving very slow before this. They were proving with Hp 45, which was very slow. This change groups them together so that the engines can help each other out, the N engine helps with proving these properties much faster than with Hp alone. In the long-term it is better to capture a relavant assumption in the proof files instead of putting this in the TCL script.
> [dv/formal] Performance improvement for divide PC

- examples/simple_system/ibex_simple_system.cc
- examples/simple_system/ibex_simple_system.h
- examples/simple_system/ibex_simple_system_main.cc
Correct the base address and size of the RAM memory model within the simulator environment. Previously the error in the RAM size was masking the incorrect base address (zero) and it simulated as intended but could fail if the base address and/or RAM size were modified.
> [simple_system] Use correct RAM base address and size

- dv/formal/check/peek/alt_lsu.sv
- dv/formal/check/peek/mem.sv
- dv/formal/check/protocol/mem.sv
- dv/formal/check/top.sv
While going through the formal flow I resolved a few warnings that Jasper complains about. This PR doesn't resolve everything, but makes a start.
Besides a few simple fixes it mainly does a rearranging of the protocol/mem.sv, peek/mem.sv and peek/alt_lsu.sv files.
> [dv/formal] Lint cleanup

- rtl/ibex_lockstep.sv
- rtl/ibex_top.sv
Otherwise an alert is raised if a core has a different configuration than zero. There, the primary core would return the non-zero value but the lockstep core zero. This difference causes an alert.
This PR fixes this bug and passes the mvendirid and mimpid parameters also to the lockstep core so that they are in sync
> [ibex] Pass mvendorid and mimpid also to lockstep core

- dv/uvm/core_ibex/fcov/core_ibex_fcov_bind.sv
- dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv
- rtl/ibex_pmp.sv
Accesses to the debug module in debug mode should never be denied by the PMP unit. This commit implements fcov to confirm we have stimulated this particular behaviour in relevant related states.
Illegal bins are used for incorrect behaviour (e.g. denied access in debug mode). Other behaviours such as debug module accesses outside of debug mode are left as ignore_bins for now. This is not explicitly disallowed by the specification, and our implementation does not have any opinion about its validity, but external debug modules opine that it should not be allowed. We could possibly expand the stimulus in the future to test this condition, but it is low priority.
This PR does not include stimulus to hit the new coverage bins. That will come in another request.
Goes towards #2233
> [fcov] Add fcov for the interaction of pmp with debug module accesses

- dv/cs_registers/Makefile
- dv/cs_registers/tb_cs_registers.core
- dv/riscv_compliance/ibex_riscv_compliance.core
- dv/verilator/simple_system_cosim/ibex_simple_system_cosim.core
- examples/simple_system/ibex_simple_system.core
This change updates the C++ language version to C++17, project wide. Previously, C++14 was used.
The same update is being made to OpenTitan via https://github.com/lowRISC/opentitan/pull/27530.
> [c++] Enable project wide C++17 Support

- dv/cosim/spike_cosim.cc
- dv/uvm/core_ibex/riscv_dv_extension/ibex_directed_instr_lib.sv
- dv/uvm/core_ibex/riscv_dv_extension/riscv_core_setting.tpl.sv
- dv/uvm/core_ibex/scripts/run_instr_gen.py
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/uvm/core_ibex/tests/core_ibex_base_test.sv
- dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
- dv/uvm/core_ibex/tests/core_ibex_vseq.sv
- dv/uvm/core_ibex/yaml/rtl_simulation.yaml
- rtl/ibex_core.sv
- util/ibex_config.py
- vendor/google_riscv-dv/euvm/riscv/gen/riscv_instr_pkg.d
- vendor/google_riscv-dv/src/riscv_instr_pkg.sv
- vendor/patches/google_riscv-dv/0003-ibex-csrs.patch
Continued from https://github.com/lowRISC/ibex/pull/2286:
This PR fixes up Ibex UVM support for DSim simulator. Several things had to be fixed:
- Simulator compatibility: DSim requires that enum values must use enum constants
- Use `ZERO` enum constant instead of `'0` and `0` for instr enums: [dv/uvm/core_ibex/riscv_dv_extension/ibex_directed_instr_lib.sv](https://github.com/lowRISC/ibex/pull/2286/files#diff-cdd6748ace94acd8de318154673012ab57d1cc2b087742d0d9f14f22cb1af84e)
- Add Ibex-specific CSRs (`CPUCTRLSTS`, `SECURESEED`) to `privileged_reg_t` and replace enum constants into `implemented_csr[]`: [vendor/google_riscv-dv/src/riscv_instr_pkg.sv](https://github.com/lowRISC/ibex/pull/2286/files#diff-c06d7c563009dd742c6749fbab5eb261d2957a7c5938534bf787b21766b7921e), …
> Fix DSim support

- dv/uvm/core_ibex/common/ibex_cosim_agent/ibex_cosim_agent_pkg.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_agent_pkg.sv
- dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_pkg.sv
- dv/uvm/core_ibex/common/irq_agent/irq_agent_pkg.sv
- dv/uvm/core_ibex/env/core_ibex_dut_probe_if.sv
- dv/uvm/core_ibex/env/core_ibex_env_pkg.sv
- dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- dv/uvm/core_ibex/tests/core_ibex_seq_lib.sv
This PR adds support for testbench elaboration using [Verific](https://www.verific.com/), which is the backbone of many EDA tools that do static analysis on SystemVerilog.
Verific is a bit more strict than other parsers about DV includes. It also does not support functional coverage binding. I've added the necessary includes and protection around functional coverage binding assigns.
Let me know if any changes are needed!
> Support testbench elaboration with Verific
